// Package db opens PostgreSQL pools (pgx v5) for the processes. Every process logs in with its own
// role and URL and never switches role at run time (R66, R87): DATABASE_URL (logitrack_app),
// MIGRATE_DATABASE_URL (logitrack_migrator), ETL_DATABASE_URL (logitrack_etl). System transactions
// (WithSystem) arrived with T05, request transactions (WithPrincipal) arrive with T07; queries are
// generated by sqlc into dbq and the domain repo packages.
package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/smartcode54-bit/logi-track-plateform/logitrack-api/internal/platform/db/dbq"
)

// Roles that log in (deploy/postgres-init/00-roles.sql, R66).
const (
	RoleMigrator = "logitrack_migrator"
	RoleApp      = "logitrack_app"
	RoleETL      = "logitrack_etl"
	RoleReadonly = "logitrack_readonly"
)

// Open connects a pool tagged with application_name and checks one connection. Errors never carry
// the URL, which holds a password.
func Open(ctx context.Context, url, appName string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, errors.New("db: the connection URL is not a valid postgres URL")
	}
	cfg.ConnConfig.RuntimeParams["application_name"] = appName
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("db: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("db: connect: %w", err)
	}
	return pool, nil
}

// Options tune a pool built by NewPool; zero values keep the pgx defaults (DATABASE_MAX_CONNS,
// DATABASE_MIN_CONNS, main spec §16.1).
type Options struct {
	MaxConns int32
	MinConns int32
}

// NewPool builds a pool tagged with application_name without dialling: the first query, or the
// readiness probe, connects. A long-running process therefore starts while PostgreSQL is still coming
// up and reports it through /readyz instead of exiting. Errors never carry the URL.
func NewPool(ctx context.Context, url, appName string, o Options) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, errors.New("db: the connection URL is not a valid postgres URL")
	}
	cfg.ConnConfig.RuntimeParams["application_name"] = appName
	if o.MaxConns > 0 {
		cfg.MaxConns = o.MaxConns
	}
	if o.MinConns > 0 {
		cfg.MinConns = o.MinConns
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("db: %w", err)
	}
	return pool, nil
}

// Login is the role a connection runs as.
type Login = dbq.CurrentLoginRow

// CurrentLogin reports the role of the connection behind q.
func CurrentLogin(ctx context.Context, q dbq.DBTX) (Login, error) {
	l, err := dbq.New(q).CurrentLogin(ctx)
	if err != nil {
		return Login{}, fmt.Errorf("db: current login: %w", err)
	}
	return l, nil
}
