// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package ssedb

import (
	"context"

	"github.com/google/uuid"
)

const chatAudience = `-- name: ChatAudience :one
SELECT tenant_id, driver_id
FROM chats
WHERE id = $1
`

type ChatAudienceRow struct {
	TenantID uuid.UUID
	DriverID *uuid.UUID
}

// The tenant and the driver of a chat, for an explicit chat:{id} topic of GET /v1/events and
// GET /v1/mobile/events (T12). It runs in the request principal's WithPrincipal transaction, so RLS
// decides whether the row is returned at all: staff see the chats of their tenant reach, a driver its
// own chat (Appendix C §C.3.5).
func (q *Queries) ChatAudience(ctx context.Context, id uuid.UUID) (ChatAudienceRow, error) {
	row := q.db.QueryRow(ctx, chatAudience, id)
	var i ChatAudienceRow
	err := row.Scan(&i.TenantID, &i.DriverID)
	return i, err
}
