export default {
    // ========================
    // First Mile - Main Page
    // ========================
    "firstMile.title": "First Mile Tasks",
    "firstMile.subtitle": "Assign drivers to pick up from Hubs and deliver to SOCs (First Step of Day Trip).",
    "firstMile.newAssignment": "New Assignment",

    // Filters
    "firstMile.filters": "Filters",
    "firstMile.filter.date": "Date",
    "firstMile.filter.pickDate": "Pick a date",
    "firstMile.filter.destination": "Destination (SOC)",
    "firstMile.filter.allSOCs": "All SOCs",
    "firstMile.filter.sourceHub": "Source Hub",
    "firstMile.filter.selectHub": "Select Hub...",
    "firstMile.filter.allHubs": "All Hubs",

    // Table Headers
    "firstMile.table.date": "Date",
    "firstMile.table.sourceHub": "Source Hub",
    "firstMile.table.destination": "Destination",
    "firstMile.table.time": "Time",
    "firstMile.table.type": "Type",
    "firstMile.table.shipmentId": "Shipment ID",
    "firstMile.table.licensePlate": "License Plate",
    "firstMile.table.driver": "Driver",
    "firstMile.table.phone": "Phone",
    "firstMile.table.actions": "Actions",
    "firstMile.table.edit": "Edit",
    "firstMile.table.noTasks": "No tasks found. Create one or import from Excel.",

    // ========================
    // Import Dialog
    // ========================
    "firstMile.import.button": "Import Excel",
    "firstMile.import.title": "Import Assignments from Excel",
    "firstMile.import.description": "Upload a spreadsheet with Plan specific columns (Date, Source, Destination, etc.).",
    "firstMile.import.templateHint": "Please use the template to ensure correct data format.",
    "firstMile.import.downloadTemplate": "Download Template",
    "firstMile.import.clickUpload": "Click to Upload Excel File",
    "firstMile.import.formatsSupported": ".xlsx, .xls formats supported",
    "firstMile.import.recordsFound": "records found",
    "firstMile.import.error": "Error",
    "firstMile.import.parseError": "Failed to parse Excel file. Please check the format.",
    "firstMile.import.pushError": "Failed to push data to database.",
    "firstMile.import.uploading": "Uploading...",
    "firstMile.import.cancel": "Cancel",
    "firstMile.import.upload": "Upload",
    "firstMile.import.records": "Records",
    "firstMile.import.unknown": "Unknown",
    "firstMile.import.invalid": "Invalid",

    // Import Table Headers
    "firstMile.import.table.row": "Row",
    "firstMile.import.table.date": "Date",
    "firstMile.import.table.source": "Pickup Location",
    "firstMile.import.table.dest": "Dest",
    "firstMile.import.table.time": "Time",
    "firstMile.import.table.truckType": "Truck Type",
    "firstMile.import.table.taskId": "First Mile Task ID",
    "firstMile.import.table.driver": "Driver",
    "firstMile.import.table.status": "Status",

    // ========================
    // Task Dialog (Create/Edit)
    // ========================
    "firstMile.task.createTitle": "New Assignment",
    "firstMile.task.editTitle": "Edit Assignment",
    "firstMile.task.createDesc": "Create a new first mile task.",
    "firstMile.task.editDesc": "Update task details.",
    "firstMile.task.date": "Date",
    "firstMile.task.pickDate": "Pick a date",
    "firstMile.task.time": "Time (HH:MM)",
    "firstMile.task.selectTime": "Select Time",
    "firstMile.task.sourceHub": "Pickup Point",
    "firstMile.task.selectHub": "Select hub",
    "firstMile.task.searchHub": "Search hub...",
    "firstMile.task.noHub": "No hub found.",
    "firstMile.task.destination": "Destination (SOC)",
    "firstMile.task.selectSOC": "Select SOC",
    "firstMile.task.truckType": "Truck Type",
    "firstMile.task.selectTruckType": "Select truck type",
    "firstMile.task.taskId": "First Mile Task ID (Auto-generated)",
    "firstMile.task.autoGenerated": "Auto-generated",
    "firstMile.task.driverInfo": "Driver Info",
    "firstMile.task.driverName": "Name",
    "firstMile.task.selectDriver": "Select Driver",
    "firstMile.task.phone": "Phone",
    "firstMile.task.licensePlate": "License Plate",
    "firstMile.task.cancel": "Cancel",
    "firstMile.task.create": "Create Assignment",
    "firstMile.task.save": "Save Changes",

    // ========================
    // Hub Dialog (Add Source)
    // ========================
    "firstMile.hub.title": "Add New Pickup Point",
    "firstMile.hub.titleEdit": "Edit Pickup Point",
    "firstMile.hub.description": "Register a new source location with coordinates.",
    "firstMile.hub.descriptionEdit": "Update source ID, name, coordinates, and station type.",
    "firstMile.hub.sourceId": "Source ID",
    "firstMile.hub.sourceIdPlaceholder": "e.g. SPX01",
    "firstMile.hub.spxName": "SPX Name",
    "firstMile.hub.spxNamePlaceholder": "e.g. Bangkok Hub",
    "firstMile.hub.nameThai": "Source Name (Thai)",
    "firstMile.hub.nameThaiPlaceholder": "e.g. ศูนย์คัดแยกกรุงเทพ",
    "firstMile.hub.location": "Location",
    "firstMile.hub.stationType": "Station Type",
    "firstMile.hub.stationTypePlaceholder": "Select type",
    "firstMile.hub.stationType.HUB": "Hub",
    "firstMile.hub.stationType.SOC": "SOC",
    "firstMile.hub.cancel": "Cancel",
    "firstMile.hub.save": "Save Source",

    // ========================
    // Sources Page
    // ========================
    "firstMile.sources.title": "Pickup Location Management",
    "firstMile.sources.newSource": "New Pickup Point",
    "firstMile.sources.dbSources": "Database Pickup Points",
    "firstMile.sources.search": "Search pickup points...",
    "firstMile.sources.table.sourceId": "Pickup Point ID",
    "firstMile.sources.table.nameSPX": "Name (SPX)",
    "firstMile.sources.table.nameThai": "Name (Thai)",
    "firstMile.sources.table.coordinates": "Coordinates",
    "firstMile.sources.table.stationType": "Station Type",
    "firstMile.sources.table.actions": "Actions",
    "firstMile.sources.loading": "Loading...",
    "firstMile.sources.noData": "No database sources found. Create one to get started.",
    "firstMile.sources.noCoords": "No coords",
    "firstMile.sources.edit": "Edit",
};
