// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package storagedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const revokeStandbyEvidence = `-- name: RevokeStandbyEvidence :execrows
UPDATE standby_records SET evidence_token_revoked_at = $1::timestamptz
 WHERE id = $2 AND evidence_token IS NOT NULL AND evidence_token_revoked_at IS NULL
`

type RevokeStandbyEvidenceParams struct {
	RevokedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeStandbyEvidence(ctx context.Context, arg RevokeStandbyEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeStandbyEvidence, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTripEvidence = `-- name: RevokeTripEvidence :execrows
UPDATE trip_records SET evidence_token_revoked_at = $1::timestamptz
 WHERE id = $2 AND evidence_token IS NOT NULL AND evidence_token_revoked_at IS NULL
`

type RevokeTripEvidenceParams struct {
	RevokedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeTripEvidence(ctx context.Context, arg RevokeTripEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeTripEvidence, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStandbyEvidenceToken = `-- name: SetStandbyEvidenceToken :execrows
UPDATE standby_records SET evidence_token = $1::text, evidence_token_revoked_at = NULL WHERE id = $2
`

type SetStandbyEvidenceTokenParams struct {
	Token string
	ID    uuid.UUID
}

func (q *Queries) SetStandbyEvidenceToken(ctx context.Context, arg SetStandbyEvidenceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStandbyEvidenceToken, arg.Token, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTripEvidenceToken = `-- name: SetTripEvidenceToken :execrows
UPDATE trip_records SET evidence_token = $1::text, evidence_token_revoked_at = NULL WHERE id = $2
`

type SetTripEvidenceTokenParams struct {
	Token string
	ID    uuid.UUID
}

// A minted token replaces a revoked one and clears the revocation (the next forced LINE send).
func (q *Queries) SetTripEvidenceToken(ctx context.Context, arg SetTripEvidenceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTripEvidenceToken, arg.Token, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const standbyByEvidenceToken = `-- name: StandbyByEvidenceToken :one
SELECT id, tenant_id, evidence_token_revoked_at, created_at FROM standby_records WHERE evidence_token = $1::text
`

type StandbyByEvidenceTokenRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	EvidenceTokenRevokedAt *time.Time
	CreatedAt              time.Time
}

func (q *Queries) StandbyByEvidenceToken(ctx context.Context, token string) (StandbyByEvidenceTokenRow, error) {
	row := q.db.QueryRow(ctx, standbyByEvidenceToken, token)
	var i StandbyByEvidenceTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvidenceTokenRevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const tripByEvidenceToken = `-- name: TripByEvidenceToken :one

SELECT id, tenant_id, evidence_token_revoked_at, created_at FROM trip_records WHERE evidence_token = $1::text
`

type TripByEvidenceTokenRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	EvidenceTokenRevokedAt *time.Time
	CreatedAt              time.Time
}

// Evidence tokens (R30, R47): trip_records and standby_records, read and written under db.WithSystem (the
// gallery has no principal; revocation is authorised in Go before it runs).
func (q *Queries) TripByEvidenceToken(ctx context.Context, token string) (TripByEvidenceTokenRow, error) {
	row := q.db.QueryRow(ctx, tripByEvidenceToken, token)
	var i TripByEvidenceTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EvidenceTokenRevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
