// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package storagedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const commitFile = `-- name: CommitFile :exec
UPDATE file_objects
   SET status = 'committed', committed_at = $1::timestamptz, expires_at = NULL,
       owner_kind = $2::text, owner_id = $3::uuid, content_type = $4::text,
       size_bytes = $5::bigint
 WHERE id = $6 AND status = 'pending'
`

type CommitFileParams struct {
	CommittedAt time.Time
	OwnerKind   string
	OwnerID     uuid.UUID
	ContentType string
	SizeBytes   int64
	ID          uuid.UUID
}

func (q *Queries) CommitFile(ctx context.Context, arg CommitFileParams) error {
	_, err := q.db.Exec(ctx, commitFile,
		arg.CommittedAt,
		arg.OwnerKind,
		arg.OwnerID,
		arg.ContentType,
		arg.SizeBytes,
		arg.ID,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM file_objects WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const extendPending = `-- name: ExtendPending :one
UPDATE file_objects SET expires_at = $1::timestamptz
 WHERE id = $2 AND status = 'pending'
RETURNING id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend
`

type ExtendPendingParams struct {
	ExpiresAt time.Time
	ID        uuid.UUID
}

// Re-signing a pending key (offline retry): the row lives another 24 h from now.
func (q *Queries) ExtendPending(ctx context.Context, arg ExtendPendingParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, extendPending, arg.ExpiresAt, arg.ID)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend FROM file_objects WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (FileObject, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const getFileByKey = `-- name: GetFileByKey :one
SELECT id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend FROM file_objects
 WHERE object_key = $1 AND deleted_at IS NULL
 ORDER BY (status = 'committed') DESC, created_at DESC, id DESC
 LIMIT 1
`

// Keys are unique per bucket; across the two buckets the same key never occurs in practice (app_releases/ lives
// only in the public one), and a committed row wins over a pending one.
func (q *Queries) GetFileByKey(ctx context.Context, objectKey string) (FileObject, error) {
	row := q.db.QueryRow(ctx, getFileByKey, objectKey)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const insertPending = `-- name: InsertPending :one

INSERT INTO file_objects (bucket, object_key, tenant_id, purpose, content_type, size_bytes, sha256, visibility,
                          status, uploaded_by, expires_at, storage_backend)
VALUES ($1, $2, $3::uuid, $4, $5::text, $6::bigint,
        $7::text, 'private', 'pending', $8::uuid, $9::timestamptz, $10)
RETURNING id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend
`

type InsertPendingParams struct {
	Bucket         string
	ObjectKey      string
	TenantID       *uuid.UUID
	Purpose        string
	ContentType    string
	SizeBytes      int64
	Sha256         *string
	UploadedBy     uuid.UUID
	ExpiresAt      time.Time
	StorageBackend string
}

// file_objects (R1) as the storage service reads and writes it, always under db.WithSystem (Appendix C §C.3.2):
// callers' rights are checked in Go before any of these run (a file is readable iff its referencing row is, C.3.5).
// POST /v1/uploads/presign: a pending upload; storage.gc removes it (and its object) after expires_at.
func (q *Queries) InsertPending(ctx context.Context, arg InsertPendingParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, insertPending,
		arg.Bucket,
		arg.ObjectKey,
		arg.TenantID,
		arg.Purpose,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.UploadedBy,
		arg.ExpiresAt,
		arg.StorageBackend,
	)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const isDirectSubtenant = `-- name: IsDirectSubtenant :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE id = $1 AND contractor_tenant_id = $2::uuid)
`

type IsDirectSubtenantParams struct {
	TenantID     uuid.UUID
	ContractorID uuid.UUID
}

// Contractor reach (R60): tenant is a carrier working for contractor (one level).
func (q *Queries) IsDirectSubtenant(ctx context.Context, arg IsDirectSubtenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDirectSubtenant, arg.TenantID, arg.ContractorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listExpiredPending = `-- name: ListExpiredPending :many
SELECT id FROM file_objects
 WHERE status = 'pending' AND expires_at < $1::timestamptz AND storage_backend = ANY($2::text[])
 ORDER BY expires_at, id
 LIMIT $3::int
`

type ListExpiredPendingParams struct {
	Now      time.Time
	Backends []string
	RowLimit int32
}

// storage.gc candidates (index file_objects_gc) on the backends this process has.
func (q *Queries) ListExpiredPending(ctx context.Context, arg ListExpiredPendingParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredPending, arg.Now, arg.Backends, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredPending = `-- name: LockExpiredPending :one
SELECT id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend FROM file_objects
 WHERE id = $1 AND status = 'pending' AND expires_at < $2::timestamptz
 FOR UPDATE SKIP LOCKED
`

type LockExpiredPendingParams struct {
	ID  uuid.UUID
	Now time.Time
}

// One candidate at a time; a row a commit holds is skipped (next run), a re-signed one no longer matches.
func (q *Queries) LockExpiredPending(ctx context.Context, arg LockExpiredPendingParams) (FileObject, error) {
	row := q.db.QueryRow(ctx, lockExpiredPending, arg.ID, arg.Now)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const lockFileByKey = `-- name: LockFileByKey :one
SELECT id, bucket, object_key, tenant_id, purpose, owner_kind, owner_id, content_type, size_bytes, sha256, visibility, status, legacy_url, uploaded_by, expires_at, committed_at, created_at, deleted_at, storage_backend FROM file_objects
 WHERE object_key = $1 AND deleted_at IS NULL
 ORDER BY (status = 'committed') DESC, created_at DESC, id DESC
 LIMIT 1
 FOR UPDATE
`

// The commit inside the entity transaction: the row is locked, so storage.gc (SKIP LOCKED) and a second commit
// wait for this transaction.
func (q *Queries) LockFileByKey(ctx context.Context, objectKey string) (FileObject, error) {
	row := q.db.QueryRow(ctx, lockFileByKey, objectKey)
	var i FileObject
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.TenantID,
		&i.Purpose,
		&i.OwnerKind,
		&i.OwnerID,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Visibility,
		&i.Status,
		&i.LegacyUrl,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.StorageBackend,
	)
	return i, err
}

const lockPendingLocalUpload = `-- name: LockPendingLocalUpload :one
SELECT id FROM file_objects
 WHERE object_key = $1 AND storage_backend = 'local' AND status = 'pending' AND deleted_at IS NULL
 LIMIT 1
 FOR UPDATE
`

// The local upload route renames the staged bytes into place while it holds this lock, the one Commit takes
// (LockFileByKey): a commit never verifies bytes a concurrent PUT is about to replace, and a committed row refuses
// the PUT.
func (q *Queries) LockPendingLocalUpload(ctx context.Context, objectKey string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPendingLocalUpload, objectKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const pendingLocalUpload = `-- name: PendingLocalUpload :one
SELECT id, size_bytes, content_type FROM file_objects
 WHERE object_key = $1 AND storage_backend = 'local' AND status = 'pending' AND deleted_at IS NULL
 LIMIT 1
`

type PendingLocalUploadRow struct {
	ID          uuid.UUID
	SizeBytes   *int64
	ContentType *string
}

// The local upload route accepts bytes only for a pending row of the local backend.
func (q *Queries) PendingLocalUpload(ctx context.Context, objectKey string) (PendingLocalUploadRow, error) {
	row := q.db.QueryRow(ctx, pendingLocalUpload, objectKey)
	var i PendingLocalUploadRow
	err := row.Scan(&i.ID, &i.SizeBytes, &i.ContentType)
	return i, err
}
