// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storagedb

import (
	"time"

	"github.com/google/uuid"
)

type FileObject struct {
	ID             uuid.UUID
	Bucket         string
	ObjectKey      string
	TenantID       *uuid.UUID
	Purpose        string
	OwnerKind      *string
	OwnerID        *uuid.UUID
	ContentType    *string
	SizeBytes      *int64
	Sha256         *string
	Visibility     string
	Status         string
	LegacyUrl      *string
	UploadedBy     *uuid.UUID
	ExpiresAt      *time.Time
	CommittedAt    *time.Time
	CreatedAt      time.Time
	DeletedAt      *time.Time
	StorageBackend string
}
