// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package outboxdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const backlog = `-- name: Backlog :one
SELECT count(*)::bigint AS pending,
       coalesce(extract(epoch FROM now() - min(created_at)), 0)::float8 AS lag_seconds
  FROM outbox_events
 WHERE published_at IS NULL
`

type BacklogRow struct {
	Pending    int64
	LagSeconds float64
}

// outbox_pending and outbox_lag_seconds (partial index outbox_events_unpublished).
func (q *Queries) Backlog(ctx context.Context) (BacklogRow, error) {
	row := q.db.QueryRow(ctx, backlog)
	var i BacklogRow
	err := row.Scan(&i.Pending, &i.LagSeconds)
	return i, err
}

const claimInbox = `-- name: ClaimInbox :execrows
INSERT INTO consumer_inbox (consumer, message_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type ClaimInboxParams struct {
	Consumer  string
	MessageID string
}

// consumer_inbox: the first statement of a consumer's side-effect transaction; 0 rows = duplicate.
func (q *Queries) ClaimInbox(ctx context.Context, arg ClaimInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimInbox, arg.Consumer, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO outbox_events (exchange, routing_key, aggregate_type, aggregate_id, event_type, tenant_id,
                           payload, headers, realtime_topics)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
RETURNING id, event_id
`

type InsertEventParams struct {
	Exchange       string
	RoutingKey     string
	AggregateType  string
	AggregateID    string
	EventType      string
	TenantID       *uuid.UUID
	Payload        []byte
	Headers        []byte
	RealtimeTopics []string
}

type InsertEventRow struct {
	ID      int64
	EventID uuid.UUID
}

// outbox.Append: the only way to emit (main spec §7.1); the AFTER INSERT trigger NOTIFYs outbox_new.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Exchange,
		arg.RoutingKey,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.TenantID,
		arg.Payload,
		arg.Headers,
		arg.RealtimeTopics,
	)
	var i InsertEventRow
	err := row.Scan(&i.ID, &i.EventID)
	return i, err
}

const lockBatch = `-- name: LockBatch :many
SELECT id, event_id, exchange, routing_key, aggregate_type, aggregate_id, event_type, tenant_id,
       payload, headers, realtime_topics, created_at
  FROM outbox_events
 WHERE published_at IS NULL
 ORDER BY id
 LIMIT $1::int
   FOR UPDATE SKIP LOCKED
`

type LockBatchRow struct {
	ID             int64
	EventID        uuid.UUID
	Exchange       string
	RoutingKey     string
	AggregateType  string
	AggregateID    string
	EventType      string
	TenantID       *uuid.UUID
	Payload        []byte
	Headers        []byte
	RealtimeTopics []string
	CreatedAt      time.Time
}

// The relay batch: oldest unpublished rows first, skipping rows another transaction holds.
func (q *Queries) LockBatch(ctx context.Context, batchSize int32) ([]LockBatchRow, error) {
	rows, err := q.db.Query(ctx, lockBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockBatchRow{}
	for rows.Next() {
		var i LockBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Exchange,
			&i.RoutingKey,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.TenantID,
			&i.Payload,
			&i.Headers,
			&i.RealtimeTopics,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox_events SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markPublished, ids)
	return err
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM outbox_events
 WHERE id IN (SELECT o.id FROM outbox_events AS o
               WHERE o.published_at IS NOT NULL AND o.published_at < $1::timestamptz
               ORDER BY o.published_at LIMIT $2::int)
`

type PruneEventsParams struct {
	Cutoff    time.Time
	BatchSize int32
}

// outbox.prune (Appendix B §B.5.6): published rows older than the cutoff, one batch per call.
func (q *Queries) PruneEvents(ctx context.Context, arg PruneEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEvents, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneInbox = `-- name: PruneInbox :execrows
DELETE FROM consumer_inbox
 WHERE (consumer, message_id) IN (SELECT i.consumer, i.message_id FROM consumer_inbox AS i
                                   WHERE i.processed_at < $1::timestamptz
                                   ORDER BY i.processed_at LIMIT $2::int)
`

type PruneInboxParams struct {
	Cutoff    time.Time
	BatchSize int32
}

// inbox.prune (Appendix B §B.5.6): rows processed before the cutoff, one batch per call.
func (q *Queries) PruneInbox(ctx context.Context, arg PruneInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneInbox, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordFailure = `-- name: RecordFailure :exec
UPDATE outbox_events SET attempts = attempts + 1, last_error = $1 WHERE id = $2
`

type RecordFailureParams struct {
	LastError *string
	ID        int64
}

func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure, arg.LastError, arg.ID)
	return err
}
