// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package securitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSecurityEvent = `-- name: InsertSecurityEvent :exec

INSERT INTO security_events (event_type, severity, summary, details, actor_user_id, actor_email, target_user_id,
                             tenant_id, request_id, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10)
`

type InsertSecurityEventParams struct {
	EventType    string
	Severity     string
	Summary      string
	Details      []byte
	ActorUserID  *uuid.UUID
	ActorEmail   *string
	TargetUserID *uuid.UUID
	TenantID     *uuid.UUID
	RequestID    *string
	CreatedAt    time.Time
}

// security_events (Appendix A 0008_platform, Appendix C §C.4.13, R85): append-only; this package is its
// only writer. Rows are appended in the caller's WithSystem transaction, with the change they describe.
func (q *Queries) InsertSecurityEvent(ctx context.Context, arg InsertSecurityEventParams) error {
	_, err := q.db.Exec(ctx, insertSecurityEvent,
		arg.EventType,
		arg.Severity,
		arg.Summary,
		arg.Details,
		arg.ActorUserID,
		arg.ActorEmail,
		arg.TargetUserID,
		arg.TenantID,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}
