// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scopedb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ScopeDriver struct {
	ID            uuid.UUID  `json:"id"`
	TenantID      uuid.UUID  `json:"tenantId"`
	FullNameTh    *string    `json:"fullNameTh"`
	FirstName     string     `json:"firstName"`
	LastName      string     `json:"lastName"`
	Mobile        string     `json:"mobile"`
	Status        string     `json:"status"`
	ActiveTruckID *uuid.UUID `json:"activeTruckId"`
}

type ScopeIncident struct {
	ID                        uuid.UUID  `json:"id"`
	TenantID                  uuid.UUID  `json:"tenantId"`
	TripID                    *uuid.UUID `json:"tripId"`
	DriverID                  *uuid.UUID `json:"driverId"`
	DelayCause                *string    `json:"delayCause"`
	Description               *string    `json:"description"`
	Lat                       *float64   `json:"lat"`
	Lng                       *float64   `json:"lng"`
	TruckID                   *uuid.UUID `json:"truckId"`
	TruckLicensePlateSnapshot *string    `json:"truckLicensePlateSnapshot"`
	MapPhotoFileID            *uuid.UUID `json:"mapPhotoFileId"`
	Situation1PhotoFileID     *uuid.UUID `json:"situation1PhotoFileId"`
	Situation2PhotoFileID     *uuid.UUID `json:"situation2PhotoFileId"`
	ReportedByKind            string     `json:"reportedByKind"`
	CreatedAt                 time.Time  `json:"createdAt"`
}

type ScopeStandby struct {
	ID                        uuid.UUID  `json:"id"`
	TenantID                  uuid.UUID  `json:"tenantId"`
	DriverID                  *uuid.UUID `json:"driverId"`
	TaskID                    *uuid.UUID `json:"taskId"`
	TripID                    *uuid.UUID `json:"tripId"`
	JobCategory               *string    `json:"jobCategory"`
	StartLocationRaw          *string    `json:"startLocationRaw"`
	EndLocationRaw            *string    `json:"endLocationRaw"`
	StartedAt                 *time.Time `json:"startedAt"`
	EndedAt                   *time.Time `json:"endedAt"`
	DurationMinutes           *int32     `json:"durationMinutes"`
	Note                      *string    `json:"note"`
	Status                    string     `json:"status"`
	Lat                       *float64   `json:"lat"`
	Lng                       *float64   `json:"lng"`
	TruckID                   *uuid.UUID `json:"truckId"`
	TruckLicensePlateSnapshot *string    `json:"truckLicensePlateSnapshot"`
	CreatedAt                 time.Time  `json:"createdAt"`
}

type ScopeTask struct {
	ID                         uuid.UUID   `json:"id"`
	TenantID                   uuid.UUID   `json:"tenantId"`
	TaskNo                     *string     `json:"taskNo"`
	TaskType                   string      `json:"taskType"`
	JobCategory                *string     `json:"jobCategory"`
	Status                     string      `json:"status"`
	PlanAt                     time.Time   `json:"planAt"`
	PlanDate                   pgtype.Date `json:"planDate"`
	PlanTime                   *string     `json:"planTime"`
	ActualPickupAt             *time.Time  `json:"actualPickupAt"`
	SourceHubRaw               string      `json:"sourceHubRaw"`
	SourceHubID                *uuid.UUID  `json:"sourceHubId"`
	DestinationRaw             string      `json:"destinationRaw"`
	DestinationHubID           *uuid.UUID  `json:"destinationHubId"`
	DestinationSocKey          *string     `json:"destinationSocKey"`
	TruckID                    *uuid.UUID  `json:"truckId"`
	TruckType                  *string     `json:"truckType"`
	LicensePlateSnapshot       *string     `json:"licensePlateSnapshot"`
	DriverID                   *uuid.UUID  `json:"driverId"`
	HelperDriverID             *uuid.UUID  `json:"helperDriverId"`
	RunOrder                   *int32      `json:"runOrder"`
	CheckInAt                  *time.Time  `json:"checkInAt"`
	CheckInPhotoFileID         *uuid.UUID  `json:"checkInPhotoFileId"`
	CheckInAppScreenshotFileID *uuid.UUID  `json:"checkInAppScreenshotFileId"`
	CheckInLat                 *float64    `json:"checkInLat"`
	CheckInLng                 *float64    `json:"checkInLng"`
	IsMultiDelivery            bool        `json:"isMultiDelivery"`
	CreatedAt                  time.Time   `json:"createdAt"`
	UpdatedAt                  time.Time   `json:"updatedAt"`
}

type ScopeTenant struct {
	ID     uuid.UUID `json:"id"`
	Kind   string    `json:"kind"`
	Code   *string   `json:"code"`
	NameTh string    `json:"nameTh"`
	NameEn *string   `json:"nameEn"`
}

type ScopeTrip struct {
	ID                        uuid.UUID      `json:"id"`
	TenantID                  uuid.UUID      `json:"tenantId"`
	TripNo                    string         `json:"tripNo"`
	Status                    string         `json:"status"`
	JobType                   string         `json:"jobType"`
	JobCategory               *string        `json:"jobCategory"`
	TaskID                    *uuid.UUID     `json:"taskId"`
	DriverID                  *uuid.UUID     `json:"driverId"`
	OriginRaw                 *string        `json:"originRaw"`
	OriginHubID               *uuid.UUID     `json:"originHubId"`
	DestinationRaw            *string        `json:"destinationRaw"`
	DestinationHubID          *uuid.UUID     `json:"destinationHubId"`
	DestinationSocKey         *string        `json:"destinationSocKey"`
	SealCode                  *string        `json:"sealCode"`
	PartnerCode               *string        `json:"partnerCode"`
	TruckID                   *uuid.UUID     `json:"truckId"`
	TruckLicensePlateSnapshot *string        `json:"truckLicensePlateSnapshot"`
	VehicleClass              *string        `json:"vehicleClass"`
	ParcelCount               *int32         `json:"parcelCount"`
	TotalWeightKg             pgtype.Numeric `json:"totalWeightKg"`
	LoadingLat                *float64       `json:"loadingLat"`
	LoadingLng                *float64       `json:"loadingLng"`
	Std                       *time.Time     `json:"std"`
	Sta                       *time.Time     `json:"sta"`
	Ata                       *time.Time     `json:"ata"`
	DeliveredAt               *time.Time     `json:"deliveredAt"`
	DeliveredLat              *float64       `json:"deliveredLat"`
	DeliveredLng              *float64       `json:"deliveredLng"`
	IsMultiDelivery           bool           `json:"isMultiDelivery"`
	CreatedAt                 time.Time      `json:"createdAt"`
	UpdatedAt                 time.Time      `json:"updatedAt"`
}

type ScopeTruck struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenantId"`
	LicensePlate string    `json:"licensePlate"`
	Province     string    `json:"province"`
	VehicleClass *string   `json:"vehicleClass"`
	TypeRaw      string    `json:"typeRaw"`
	Status       string    `json:"status"`
}
