// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_tasks.sql

package scopedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getScopeTask = `-- name: GetScopeTask :one
SELECT id, tenant_id, task_no, task_type, job_category, status, plan_at, plan_date, plan_time, actual_pickup_at, source_hub_raw, source_hub_id, destination_raw, destination_hub_id, destination_soc_key, truck_id, truck_type, license_plate_snapshot, driver_id, helper_driver_id, run_order, check_in_at, check_in_photo_file_id, check_in_app_screenshot_file_id, check_in_lat, check_in_lng, is_multi_delivery, created_at, updated_at FROM scope_tasks WHERE id = $1
`

func (q *Queries) GetScopeTask(ctx context.Context, id uuid.UUID) (ScopeTask, error) {
	row := q.db.QueryRow(ctx, getScopeTask, id)
	var i ScopeTask
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TaskNo,
		&i.TaskType,
		&i.JobCategory,
		&i.Status,
		&i.PlanAt,
		&i.PlanDate,
		&i.PlanTime,
		&i.ActualPickupAt,
		&i.SourceHubRaw,
		&i.SourceHubID,
		&i.DestinationRaw,
		&i.DestinationHubID,
		&i.DestinationSocKey,
		&i.TruckID,
		&i.TruckType,
		&i.LicensePlateSnapshot,
		&i.DriverID,
		&i.HelperDriverID,
		&i.RunOrder,
		&i.CheckInAt,
		&i.CheckInPhotoFileID,
		&i.CheckInAppScreenshotFileID,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.IsMultiDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScopeTasks = `-- name: ListScopeTasks :many

SELECT id, tenant_id, task_no, task_type, job_category, status, plan_at, plan_date, plan_time, actual_pickup_at, source_hub_raw, source_hub_id, destination_raw, destination_hub_id, destination_soc_key, truck_id, truck_type, license_plate_snapshot, driver_id, helper_driver_id, run_order, check_in_at, check_in_photo_file_id, check_in_app_screenshot_file_id, check_in_lat, check_in_lng, is_multi_delivery, created_at, updated_at FROM scope_tasks
 WHERE ($1::timestamptz IS NULL
        OR (plan_at, id) < ($1::timestamptz, $2::uuid))
 ORDER BY plan_at DESC, id DESC
 LIMIT $3
`

type ListScopeTasksParams struct {
	BeforePlanAt *time.Time `json:"beforePlanAt"`
	BeforeID     *uuid.UUID `json:"beforeId"`
	RowLimit     int32      `json:"rowLimit"`
}

// Dispatcher and customer-scope reads of tasks: the scope_tasks projection only (Appendix C §C.3.7, R85).
// Rows come from p_scope_read under the caller's RLS (security_invoker); every file named scope_*.sql
// reads scope_* views only, and sqlc vet (rule scope-views-only) fails on a base table.
func (q *Queries) ListScopeTasks(ctx context.Context, arg ListScopeTasksParams) ([]ScopeTask, error) {
	rows, err := q.db.Query(ctx, listScopeTasks, arg.BeforePlanAt, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeTask{}
	for rows.Next() {
		var i ScopeTask
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TaskNo,
			&i.TaskType,
			&i.JobCategory,
			&i.Status,
			&i.PlanAt,
			&i.PlanDate,
			&i.PlanTime,
			&i.ActualPickupAt,
			&i.SourceHubRaw,
			&i.SourceHubID,
			&i.DestinationRaw,
			&i.DestinationHubID,
			&i.DestinationSocKey,
			&i.TruckID,
			&i.TruckType,
			&i.LicensePlateSnapshot,
			&i.DriverID,
			&i.HelperDriverID,
			&i.RunOrder,
			&i.CheckInAt,
			&i.CheckInPhotoFileID,
			&i.CheckInAppScreenshotFileID,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.IsMultiDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
