// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_fleet.sql

package scopedb

import (
	"context"

	"github.com/google/uuid"
)

const scopeDriversByID = `-- name: ScopeDriversByID :many

SELECT id, tenant_id, full_name_th, first_name, last_name, mobile, status, active_truck_id FROM scope_drivers WHERE id = ANY ($1::uuid[]) ORDER BY id
`

// Drivers, trucks and carrier names as a scope principal may see them: the scope_drivers, scope_trucks and
// scope_tenants projections (no ID card, licence, birth date, insurance, tax or cost columns; Appendix C
// §C.3.7). Drivers and trucks are visible only through recent in-scope work (app_recent_work_in_scope).
func (q *Queries) ScopeDriversByID(ctx context.Context, ids []uuid.UUID) ([]ScopeDriver, error) {
	rows, err := q.db.Query(ctx, scopeDriversByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeDriver{}
	for rows.Next() {
		var i ScopeDriver
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FullNameTh,
			&i.FirstName,
			&i.LastName,
			&i.Mobile,
			&i.Status,
			&i.ActiveTruckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeTenantsByID = `-- name: ScopeTenantsByID :many
SELECT id, kind, code, name_th, name_en FROM scope_tenants WHERE id = ANY ($1::uuid[]) ORDER BY id
`

func (q *Queries) ScopeTenantsByID(ctx context.Context, ids []uuid.UUID) ([]ScopeTenant, error) {
	rows, err := q.db.Query(ctx, scopeTenantsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeTenant{}
	for rows.Next() {
		var i ScopeTenant
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Code,
			&i.NameTh,
			&i.NameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scopeTrucksByID = `-- name: ScopeTrucksByID :many
SELECT id, tenant_id, license_plate, province, vehicle_class, type_raw, status FROM scope_trucks WHERE id = ANY ($1::uuid[]) ORDER BY id
`

func (q *Queries) ScopeTrucksByID(ctx context.Context, ids []uuid.UUID) ([]ScopeTruck, error) {
	rows, err := q.db.Query(ctx, scopeTrucksByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeTruck{}
	for rows.Next() {
		var i ScopeTruck
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LicensePlate,
			&i.Province,
			&i.VehicleClass,
			&i.TypeRaw,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
