// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_standby.sql

package scopedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listScopeStandby = `-- name: ListScopeStandby :many

SELECT id, tenant_id, driver_id, task_id, trip_id, job_category, start_location_raw, end_location_raw, started_at, ended_at, duration_minutes, note, status, lat, lng, truck_id, truck_license_plate_snapshot, created_at FROM scope_standby
 WHERE ($1::timestamptz IS NULL
        OR (created_at, id) < ($1::timestamptz, $2::uuid))
 ORDER BY created_at DESC, id DESC
 LIMIT $3
`

type ListScopeStandbyParams struct {
	BeforeCreatedAt *time.Time `json:"beforeCreatedAt"`
	BeforeID        *uuid.UUID `json:"beforeId"`
	RowLimit        int32      `json:"rowLimit"`
}

// Dispatcher and customer-scope reads of standby records: the scope_standby projection only (no billing_*,
// Appendix C §C.3.7).
func (q *Queries) ListScopeStandby(ctx context.Context, arg ListScopeStandbyParams) ([]ScopeStandby, error) {
	rows, err := q.db.Query(ctx, listScopeStandby, arg.BeforeCreatedAt, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeStandby{}
	for rows.Next() {
		var i ScopeStandby
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DriverID,
			&i.TaskID,
			&i.TripID,
			&i.JobCategory,
			&i.StartLocationRaw,
			&i.EndLocationRaw,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
			&i.Note,
			&i.Status,
			&i.Lat,
			&i.Lng,
			&i.TruckID,
			&i.TruckLicensePlateSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
