// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_incidents.sql

package scopedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listScopeIncidents = `-- name: ListScopeIncidents :many

SELECT id, tenant_id, trip_id, driver_id, delay_cause, description, lat, lng, truck_id, truck_license_plate_snapshot, map_photo_file_id, situation1_photo_file_id, situation2_photo_file_id, reported_by_kind, created_at FROM scope_incidents
 WHERE ($1::timestamptz IS NULL
        OR (created_at, id) < ($1::timestamptz, $2::uuid))
 ORDER BY created_at DESC, id DESC
 LIMIT $3
`

type ListScopeIncidentsParams struct {
	BeforeCreatedAt *time.Time `json:"beforeCreatedAt"`
	BeforeID        *uuid.UUID `json:"beforeId"`
	RowLimit        int32      `json:"rowLimit"`
}

// Dispatcher and customer-scope reads of incident reports: incidents of visible trips only, through the
// scope_incidents projection (Appendix C §C.3.7).
func (q *Queries) ListScopeIncidents(ctx context.Context, arg ListScopeIncidentsParams) ([]ScopeIncident, error) {
	rows, err := q.db.Query(ctx, listScopeIncidents, arg.BeforeCreatedAt, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeIncident{}
	for rows.Next() {
		var i ScopeIncident
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TripID,
			&i.DriverID,
			&i.DelayCause,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.TruckID,
			&i.TruckLicensePlateSnapshot,
			&i.MapPhotoFileID,
			&i.Situation1PhotoFileID,
			&i.Situation2PhotoFileID,
			&i.ReportedByKind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
