// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope_trips.sql

package scopedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getScopeTrip = `-- name: GetScopeTrip :one
SELECT id, tenant_id, trip_no, status, job_type, job_category, task_id, driver_id, origin_raw, origin_hub_id, destination_raw, destination_hub_id, destination_soc_key, seal_code, partner_code, truck_id, truck_license_plate_snapshot, vehicle_class, parcel_count, total_weight_kg, loading_lat, loading_lng, std, sta, ata, delivered_at, delivered_lat, delivered_lng, is_multi_delivery, created_at, updated_at FROM scope_trips WHERE id = $1
`

func (q *Queries) GetScopeTrip(ctx context.Context, id uuid.UUID) (ScopeTrip, error) {
	row := q.db.QueryRow(ctx, getScopeTrip, id)
	var i ScopeTrip
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TripNo,
		&i.Status,
		&i.JobType,
		&i.JobCategory,
		&i.TaskID,
		&i.DriverID,
		&i.OriginRaw,
		&i.OriginHubID,
		&i.DestinationRaw,
		&i.DestinationHubID,
		&i.DestinationSocKey,
		&i.SealCode,
		&i.PartnerCode,
		&i.TruckID,
		&i.TruckLicensePlateSnapshot,
		&i.VehicleClass,
		&i.ParcelCount,
		&i.TotalWeightKg,
		&i.LoadingLat,
		&i.LoadingLng,
		&i.Std,
		&i.Sta,
		&i.Ata,
		&i.DeliveredAt,
		&i.DeliveredLat,
		&i.DeliveredLng,
		&i.IsMultiDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScopeTrips = `-- name: ListScopeTrips :many

SELECT id, tenant_id, trip_no, status, job_type, job_category, task_id, driver_id, origin_raw, origin_hub_id, destination_raw, destination_hub_id, destination_soc_key, seal_code, partner_code, truck_id, truck_license_plate_snapshot, vehicle_class, parcel_count, total_weight_kg, loading_lat, loading_lng, std, sta, ata, delivered_at, delivered_lat, delivered_lng, is_multi_delivery, created_at, updated_at FROM scope_trips
 WHERE ($1::timestamptz IS NULL
        OR (created_at, id) < ($1::timestamptz, $2::uuid))
 ORDER BY created_at DESC, id DESC
 LIMIT $3
`

type ListScopeTripsParams struct {
	BeforeCreatedAt *time.Time `json:"beforeCreatedAt"`
	BeforeID        *uuid.UUID `json:"beforeId"`
	RowLimit        int32      `json:"rowLimit"`
}

// Dispatcher and customer-scope reads of trip records: the scope_trips projection only (Appendix C §C.3.7).
func (q *Queries) ListScopeTrips(ctx context.Context, arg ListScopeTripsParams) ([]ScopeTrip, error) {
	rows, err := q.db.Query(ctx, listScopeTrips, arg.BeforeCreatedAt, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScopeTrip{}
	for rows.Next() {
		var i ScopeTrip
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TripNo,
			&i.Status,
			&i.JobType,
			&i.JobCategory,
			&i.TaskID,
			&i.DriverID,
			&i.OriginRaw,
			&i.OriginHubID,
			&i.DestinationRaw,
			&i.DestinationHubID,
			&i.DestinationSocKey,
			&i.SealCode,
			&i.PartnerCode,
			&i.TruckID,
			&i.TruckLicensePlateSnapshot,
			&i.VehicleClass,
			&i.ParcelCount,
			&i.TotalWeightKg,
			&i.LoadingLat,
			&i.LoadingLng,
			&i.Std,
			&i.Sta,
			&i.Ata,
			&i.DeliveredAt,
			&i.DeliveredLat,
			&i.DeliveredLng,
			&i.IsMultiDelivery,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
