// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bridge.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignLegacyAuthUID = `-- name: AssignLegacyAuthUID :one
UPDATE users SET legacy_auth_uid = id::text
WHERE id = $1 AND legacy_auth_uid IS NULL
RETURNING legacy_auth_uid::text
`

// The first custom token of a user created in Go (C.6.3), or its first mirrored account (C.6.4): the
// Firebase uid becomes users.id::text. A uid that is already set is kept.
func (q *Queries) AssignLegacyAuthUID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, assignLegacyAuthUID, id)
	var legacy_auth_uid string
	err := row.Scan(&legacy_auth_uid)
	return legacy_auth_uid, err
}

const getBridgeUser = `-- name: GetBridgeUser :one

SELECT u.id, u.legacy_auth_uid, u.email, u.email_verified, u.display_name, u.status, u.must_change_password,
       u.password_changed_at, u.auth_version,
       EXISTS (SELECT 1 FROM auth_identities i WHERE i.user_id = u.id AND i.provider = 'firebase_legacy') AS imported
FROM users u
WHERE u.id = $1
`

type GetBridgeUserRow struct {
	ID                 uuid.UUID
	LegacyAuthUid      *string
	Email              *string
	EmailVerified      bool
	DisplayName        *string
	Status             string
	MustChangePassword bool
	PasswordChangedAt  *time.Time
	AuthVersion        int32
	Imported           bool
}

// Firebase bridge (T08, Appendix C §C.6): the Firebase side of a user, the facts behind the legacy claim
// object (C.6.3) and the account-status writes the mirror follows (C.6.4). Every statement runs inside
// db.WithSystem, like the rest of auth (R12).
// The user's Firebase uid (users.legacy_auth_uid, kept forever, R55) and whether the account was imported
// from Firebase Auth: cmd/etl auth-import writes an auth_identities row of provider firebase_legacy for
// every exported account (main spec §4.11), and nothing else does, so a user created in Go is never
// "imported" even after the bridge gives it a Firebase uid.
func (q *Queries) GetBridgeUser(ctx context.Context, id uuid.UUID) (GetBridgeUserRow, error) {
	row := q.db.QueryRow(ctx, getBridgeUser, id)
	var i GetBridgeUserRow
	err := row.Scan(
		&i.ID,
		&i.LegacyAuthUid,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Status,
		&i.MustChangePassword,
		&i.PasswordChangedAt,
		&i.AuthVersion,
		&i.Imported,
	)
	return i, err
}

const getDriverLegacyRef = `-- name: GetDriverLegacyRef :one
SELECT coalesce(legacy_doc_id, id::text)::text AS ref FROM drivers WHERE user_id = $1::uuid
`

// driverId claim of a driver (C.6.3): the Firestore drivers doc id, or the uuid of a driver created in Go
// (its write-back doc id, R25).
func (q *Queries) GetDriverLegacyRef(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDriverLegacyRef, userID)
	var ref string
	err := row.Scan(&ref)
	return ref, err
}

const getTenantLegacy = `-- name: GetTenantLegacy :one
SELECT kind, legacy_doc_id FROM tenants WHERE id = $1
`

type GetTenantLegacyRow struct {
	Kind        string
	LegacyDocID *string
}

// Kind and subcontractors doc id of a tenant: a carrier tenant's legacy_doc_id is the legacy
// partnerScopeId value.
func (q *Queries) GetTenantLegacy(ctx context.Context, id uuid.UUID) (GetTenantLegacyRow, error) {
	row := q.db.QueryRow(ctx, getTenantLegacy, id)
	var i GetTenantLegacyRow
	err := row.Scan(&i.Kind, &i.LegacyDocID)
	return i, err
}

const getUserIDByLegacyUID = `-- name: GetUserIDByLegacyUID :one
SELECT id FROM users WHERE legacy_auth_uid = $1::text AND status <> 'deleted'
`

// Firebase ID token -> user (index users_legacy_uid). Deleted users keep their uid but do not exist here.
func (q *Queries) GetUserIDByLegacyUID(ctx context.Context, legacyAuthUid string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByLegacyUID, legacyAuthUid)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const oldestCustomerScopeLegacyID = `-- name: OldestCustomerScopeLegacyID :one
SELECT coalesce(c.legacy_doc_id, t.legacy_doc_id)::text AS legacy_doc_id
FROM user_scopes s
JOIN billing_parties bp ON bp.id = s.billing_party_id
LEFT JOIN customers c ON c.id = bp.customer_id
LEFT JOIN tenants t ON t.id = bp.tenant_id
WHERE s.user_id = $1 AND s.kind = 'customer'
  AND coalesce(c.legacy_doc_id, t.legacy_doc_id) IS NOT NULL
ORDER BY s.created_at, s.billing_party_id
LIMIT 1
`

// customerScopeId of a customer-scope user (C.6.3): the legacy doc id of its oldest customer scope that
// has one. C.5.5 resolved the legacy value through customers.legacy_doc_id, else tenants.legacy_doc_id,
// so the same two columns give it back.
func (q *Queries) OldestCustomerScopeLegacyID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, oldestCustomerScopeLegacyID, userID)
	var legacy_doc_id string
	err := row.Scan(&legacy_doc_id)
	return legacy_doc_id, err
}

const setTemporaryPassword = `-- name: SetTemporaryPassword :one
UPDATE users
SET password_hash        = $1::text,
    legacy_scrypt_hash   = NULL,
    legacy_scrypt_salt   = NULL,
    must_change_password = true,
    password_changed_at  = $2::timestamptz,
    status               = CASE WHEN status = 'reset_required' THEN 'active' ELSE status END,
    auth_version         = auth_version + 1
WHERE id = $3
RETURNING auth_version
`

type SetTemporaryPasswordParams struct {
	PasswordHash string
	ChangedAt    time.Time
	ID           uuid.UUID
}

// An admin-issued temporary password (R29, R79): like SetPassword, but the user must change it at the
// next sign-in.
func (q *Queries) SetTemporaryPassword(ctx context.Context, arg SetTemporaryPasswordParams) (int32, error) {
	row := q.db.QueryRow(ctx, setTemporaryPassword, arg.PasswordHash, arg.ChangedAt, arg.ID)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET status = 'disabled', disabled_at = $1::timestamptz WHERE id = $2
`

type SetUserDisabledParams struct {
	At time.Time
	ID uuid.UUID
}

// Disable (C.4.7): status disabled from active or reset_required.
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.At, arg.ID)
	return err
}

const setUserEnabled = `-- name: SetUserEnabled :exec
UPDATE users SET status = 'active', disabled_at = NULL WHERE id = $1 AND status = 'disabled'
`

// Enable: a disabled user becomes active again.
func (q *Queries) SetUserEnabled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserEnabled, id)
	return err
}
