// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lockDeviceToken = `-- name: LockDeviceToken :exec

SELECT pg_advisory_xact_lock(hashtextextended('device_tokens:' || $1::text, 0))
`

// Push devices of the caller (Appendix B §B.2.3, Appendix C §C.8, R4): device_tokens PK (user_id,
// install_id), token UNIQUE, driver_id nullable. Written under WithSystem after Go authorization: the
// token may sit on another user's row, which RLS (p_self) would hide.
// Registrations of one token run one at a time (transaction advisory lock on the token's hash), so two
// devices or users racing for it never deadlock or trip the UNIQUE index.
func (q *Queries) LockDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, lockDeviceToken, token)
	return err
}

const pruneUserDevices = `-- name: PruneUserDevices :execrows
DELETE FROM device_tokens dt
WHERE dt.user_id = $1 AND dt.install_id <> $2::text
  AND dt.install_id NOT IN (SELECT k.install_id FROM device_tokens k
                         WHERE k.user_id = $1 AND k.install_id <> $2::text
                         ORDER BY k.last_seen_at DESC, k.install_id
                         LIMIT $3::bigint)
`

type PruneUserDevicesParams struct {
	UserID    uuid.UUID
	InstallID string
	Keep      int64
}

// At most auth.MaxDevicesPerUser rows per user: after a registration the least recently seen rows
// beyond @keep others go (never the install just registered), so a reinstall never fails and no user
// can grow the fan-out of notify.fcm without bound.
func (q *Queries) PruneUserDevices(ctx context.Context, arg PruneUserDevicesParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneUserDevices, arg.UserID, arg.InstallID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseDeviceToken = `-- name: ReleaseDeviceToken :many
DELETE FROM device_tokens
WHERE token = $1
  AND ((user_id = $2::uuid AND install_id <> $3::text)
       OR (user_id <> $2::uuid AND install_id = $4::text))
RETURNING user_id, install_id, legacy_source
`

type ReleaseDeviceTokenParams struct {
	Token          string
	UserID         uuid.UUID
	InstallID      string
	SessionInstall *string
}

type ReleaseDeviceTokenRow struct {
	UserID       uuid.UUID
	InstallID    string
	LegacySource *string
}

// The rows a registration may take the token from, deleted in the same transaction so the UNIQUE index
// never fails: the caller's own other rows (a reinstall, the caller's ETL legacy row of the device) and
// another user's row of the install the caller's session is signed in on (shared phone: the previous
// user did not log out). session_install is NULL for a session without an install (web): own rows
// only. Any other holder keeps the token (TokenHeldElsewhere).
func (q *Queries) ReleaseDeviceToken(ctx context.Context, arg ReleaseDeviceTokenParams) ([]ReleaseDeviceTokenRow, error) {
	rows, err := q.db.Query(ctx, releaseDeviceToken,
		arg.Token,
		arg.UserID,
		arg.InstallID,
		arg.SessionInstall,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseDeviceTokenRow{}
	for rows.Next() {
		var i ReleaseDeviceTokenRow
		if err := rows.Scan(&i.UserID, &i.InstallID, &i.LegacySource); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenHeldElsewhere = `-- name: TokenHeldElsewhere :one
SELECT EXISTS (SELECT 1 FROM device_tokens WHERE token = $1 AND user_id <> $2::uuid)::boolean AS held
`

type TokenHeldElsewhereParams struct {
	Token  string
	UserID uuid.UUID
}

// After ReleaseDeviceToken: another user's row still holds the token (409 already_exists).
func (q *Queries) TokenHeldElsewhere(ctx context.Context, arg TokenHeldElsewhereParams) (bool, error) {
	row := q.db.QueryRow(ctx, tokenHeldElsewhere, arg.Token, arg.UserID)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, install_id, token, driver_id, platform, app_flavor, app_version, created_at, last_seen_at)
VALUES ($1, $2, $3,
        (SELECT d.id FROM drivers d WHERE d.user_id = $1::uuid),
        $4, $5, $6, $7, $7)
ON CONFLICT (user_id, install_id) DO UPDATE
SET token = EXCLUDED.token, driver_id = EXCLUDED.driver_id, platform = EXCLUDED.platform,
    app_flavor = EXCLUDED.app_flavor, app_version = coalesce(EXCLUDED.app_version, device_tokens.app_version),
    legacy_source = NULL, last_seen_at = EXCLUDED.last_seen_at
`

type UpsertDeviceTokenParams struct {
	UserID     uuid.UUID
	InstallID  string
	Token      string
	Platform   string
	AppFlavor  *string
	AppVersion *string
	At         time.Time
}

// driver_id is the caller's linked driver read now, never a claim (R4).
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken,
		arg.UserID,
		arg.InstallID,
		arg.Token,
		arg.Platform,
		arg.AppFlavor,
		arg.AppVersion,
		arg.At,
	)
	return err
}
