// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lockDeviceToken = `-- name: LockDeviceToken :exec

SELECT pg_advisory_xact_lock(hashtextextended('device_tokens:' || $1::text, 0))
`

// Push devices of the caller (Appendix B §B.2.3, Appendix C §C.8, R4): device_tokens PK (user_id,
// install_id), token UNIQUE, driver_id nullable. Written under WithSystem after Go authorization: the
// token may sit on another user's row, which RLS (p_self) would hide.
// Registrations of one token run one at a time (transaction advisory lock on the token's hash), so two
// devices or users racing for it never deadlock or trip the UNIQUE index.
func (q *Queries) LockDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, lockDeviceToken, token)
	return err
}

const releaseDeviceToken = `-- name: ReleaseDeviceToken :execrows
DELETE FROM device_tokens
WHERE token = $1 AND (user_id <> $2::uuid OR install_id <> $3::text)
`

type ReleaseDeviceTokenParams struct {
	Token     string
	UserID    uuid.UUID
	InstallID string
}

// A token held by another (user, install) moves to the caller in the same transaction (shared phone,
// re-login as someone else, an ETL legacy row of the same device): the UNIQUE index never fails.
func (q *Queries) ReleaseDeviceToken(ctx context.Context, arg ReleaseDeviceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseDeviceToken, arg.Token, arg.UserID, arg.InstallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, install_id, token, driver_id, platform, app_flavor, app_version, created_at, last_seen_at)
VALUES ($1, $2, $3,
        (SELECT d.id FROM drivers d WHERE d.user_id = $1::uuid),
        $4, $5, $6, $7, $7)
ON CONFLICT (user_id, install_id) DO UPDATE
SET token = EXCLUDED.token, driver_id = EXCLUDED.driver_id, platform = EXCLUDED.platform,
    app_flavor = EXCLUDED.app_flavor, app_version = coalesce(EXCLUDED.app_version, device_tokens.app_version),
    legacy_source = NULL, last_seen_at = EXCLUDED.last_seen_at
`

type UpsertDeviceTokenParams struct {
	UserID     uuid.UUID
	InstallID  string
	Token      string
	Platform   string
	AppFlavor  *string
	AppVersion *string
	At         time.Time
}

// driver_id is the caller's linked driver read now, never a claim (R4).
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken,
		arg.UserID,
		arg.InstallID,
		arg.Token,
		arg.Platform,
		arg.AppFlavor,
		arg.AppVersion,
		arg.At,
	)
	return err
}
