// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getGoogleIdentityUser = `-- name: GetGoogleIdentityUser :one

SELECT user_id FROM auth_identities
WHERE provider = 'google' AND provider_subject = $1::text
`

// External identities (auth_identities, Appendix A §A.2.1; Appendix C §C.4.10). Google sign-in resolves the
// Google `sub` first, then links the user whose email the token verified (no self-signup). Every statement
// runs inside db.WithSystem (R12).
func (q *Queries) GetGoogleIdentityUser(ctx context.Context, subject string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getGoogleIdentityUser, subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserGoogleSubject = `-- name: GetUserGoogleSubject :one
SELECT provider_subject FROM auth_identities
WHERE user_id = $1 AND provider = 'google'
`

// The Google account already linked to a user (UNIQUE (user_id, provider): at most one).
func (q *Queries) GetUserGoogleSubject(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserGoogleSubject, userID)
	var provider_subject string
	err := row.Scan(&provider_subject)
	return provider_subject, err
}

const insertGoogleIdentity = `-- name: InsertGoogleIdentity :exec
INSERT INTO auth_identities (user_id, provider, provider_subject, email_at_link, linked_at, last_used_at)
VALUES ($1, 'google', $2::text, $3::text, $4::timestamptz,
        $4::timestamptz)
`

type InsertGoogleIdentityParams struct {
	UserID      uuid.UUID
	Subject     string
	EmailAtLink string
	At          time.Time
}

func (q *Queries) InsertGoogleIdentity(ctx context.Context, arg InsertGoogleIdentityParams) error {
	_, err := q.db.Exec(ctx, insertGoogleIdentity,
		arg.UserID,
		arg.Subject,
		arg.EmailAtLink,
		arg.At,
	)
	return err
}

const touchGoogleIdentity = `-- name: TouchGoogleIdentity :execrows
UPDATE auth_identities SET last_used_at = $1::timestamptz
WHERE provider = 'google' AND provider_subject = $2::text AND user_id = $3
`

type TouchGoogleIdentityParams struct {
	At      time.Time
	Subject string
	UserID  uuid.UUID
}

// Written by the session transaction of a Google sign-in; 0 rows means the link vanished since it was resolved.
func (q *Queries) TouchGoogleIdentity(ctx context.Context, arg TouchGoogleIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchGoogleIdentity, arg.At, arg.Subject, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
