// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package authdb

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE user_id = $1 AND install_id = $2
`

type DeleteDeviceTokenParams struct {
	UserID    uuid.UUID
	InstallID string
}

// POST /v1/auth/logout removes the push token of the install it signs out (C.8).
func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.UserID, arg.InstallID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, platform, amr, active_tenant_id, install_id, absolute_expires_at, revoked_at
FROM sessions
WHERE id = $1
`

type GetSessionRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Platform          string
	Amr               string
	ActiveTenantID    *uuid.UUID
	InstallID         *string
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Amr,
		&i.ActiveTenantID,
		&i.InstallID,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, purpose, token_hash, expires_at, requested_ip, requested_by, created_at)
VALUES ($1, $2, $3, $4, $5::inet,
        $6, $7)
RETURNING id
`

type InsertPasswordResetTokenParams struct {
	UserID      uuid.UUID
	Purpose     string
	TokenHash   []byte
	ExpiresAt   time.Time
	RequestedIp *netip.Addr
	RequestedBy *uuid.UUID
	CreatedAt   time.Time
}

// Only sha256(token) is stored (C.4.9); the token itself never reaches the database or the outbox.
func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPasswordResetToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.RequestedIp,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (session_id, family_id, token_hash, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertRefreshTokenParams struct {
	SessionID uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	IssuedAt  time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.SessionID,
		arg.FamilyID,
		arg.TokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (user_id, platform, amr, active_tenant_id, install_id, app_version, ip, user_agent,
                      absolute_expires_at, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7::inet, $8, $9,
        $10, $10)
RETURNING id
`

type InsertSessionParams struct {
	UserID            uuid.UUID
	Platform          string
	Amr               string
	ActiveTenantID    *uuid.UUID
	InstallID         *string
	AppVersion        *string
	Ip                *netip.Addr
	UserAgent         *string
	AbsoluteExpiresAt time.Time
	CreatedAt         time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.UserID,
		arg.Platform,
		arg.Amr,
		arg.ActiveTenantID,
		arg.InstallID,
		arg.AppVersion,
		arg.Ip,
		arg.UserAgent,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listLiveSessions = `-- name: ListLiveSessions :many
SELECT id, platform, amr, install_id, device_label, app_version, coalesce(host(ip), '')::text AS ip, user_agent, created_at, last_seen_at
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND absolute_expires_at > $2
ORDER BY last_seen_at DESC, id DESC
`

type ListLiveSessionsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

type ListLiveSessionsRow struct {
	ID          uuid.UUID
	Platform    string
	Amr         string
	InstallID   *string
	DeviceLabel *string
	AppVersion  *string
	Ip          string
	UserAgent   *string
	CreatedAt   time.Time
	LastSeenAt  time.Time
}

func (q *Queries) ListLiveSessions(ctx context.Context, arg ListLiveSessionsParams) ([]ListLiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveSessionsRow{}
	for rows.Next() {
		var i ListLiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Amr,
			&i.InstallID,
			&i.DeviceLabel,
			&i.AppVersion,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPasswordResetToken = `-- name: LockPasswordResetToken :one
SELECT id, user_id, purpose, expires_at, used_at
FROM password_reset_tokens
WHERE token_hash = $1
FOR UPDATE
`

type LockPasswordResetTokenRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	ExpiresAt time.Time
	UsedAt    *time.Time
}

func (q *Queries) LockPasswordResetToken(ctx context.Context, tokenHash []byte) (LockPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetToken, tokenHash)
	var i LockPasswordResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const lockRefreshToken = `-- name: LockRefreshToken :one
SELECT rt.id, rt.session_id, rt.family_id, rt.expires_at, rt.rotated_at, rt.replaced_by, rt.revoked_at,
       s.user_id, s.platform, s.amr, s.active_tenant_id, s.install_id, s.absolute_expires_at,
       s.revoked_at AS session_revoked_at
FROM refresh_tokens rt
JOIN sessions s ON s.id = rt.session_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt, s
`

type LockRefreshTokenRow struct {
	ID                uuid.UUID
	SessionID         uuid.UUID
	FamilyID          uuid.UUID
	ExpiresAt         time.Time
	RotatedAt         *time.Time
	ReplacedBy        *uuid.UUID
	RevokedAt         *time.Time
	UserID            uuid.UUID
	Platform          string
	Amr               string
	ActiveTenantID    *uuid.UUID
	InstallID         *string
	AbsoluteExpiresAt time.Time
	SessionRevokedAt  *time.Time
}

// The presented token and its session, locked so concurrent refreshes of one family serialise. Callers
// hold the user's row lock first (LockUser): every auth transaction locks users -> sessions ->
// refresh_tokens, so a refresh never deadlocks with a revocation, a password change or a tenant switch.
func (q *Queries) LockRefreshToken(ctx context.Context, tokenHash []byte) (LockRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshToken, tokenHash)
	var i LockRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.ReplacedBy,
		&i.RevokedAt,
		&i.UserID,
		&i.Platform,
		&i.Amr,
		&i.ActiveTenantID,
		&i.InstallID,
		&i.AbsoluteExpiresAt,
		&i.SessionRevokedAt,
	)
	return i, err
}

const lockRefreshTokenByID = `-- name: LockRefreshTokenByID :one
SELECT id, rotated_at, revoked_at FROM refresh_tokens WHERE id = $1 FOR UPDATE
`

type LockRefreshTokenByIDRow struct {
	ID        uuid.UUID
	RotatedAt *time.Time
	RevokedAt *time.Time
}

func (q *Queries) LockRefreshTokenByID(ctx context.Context, id uuid.UUID) (LockRefreshTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, lockRefreshTokenByID, id)
	var i LockRefreshTokenByIDRow
	err := row.Scan(&i.ID, &i.RotatedAt, &i.RevokedAt)
	return i, err
}

const refreshTokenUser = `-- name: RefreshTokenUser :one
SELECT s.user_id
FROM refresh_tokens rt
JOIN sessions s ON s.id = rt.session_id
WHERE rt.token_hash = $1
`

// The user of a presented refresh token, without a lock (sessions.user_id never changes): Refresh and
// Logout lock that user before the token and its session (lock order users -> sessions -> refresh_tokens).
func (q *Queries) RefreshTokenUser(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, refreshTokenUser, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeFamily = `-- name: RevokeFamily :many
UPDATE refresh_tokens SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE family_id = $3 AND revoked_at IS NULL
RETURNING token_hash
`

type RevokeFamilyParams struct {
	At       time.Time
	Reason   string
	FamilyID uuid.UUID
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, revokeFamily, arg.At, arg.Reason, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInstallSessions = `-- name: RevokeInstallSessions :many

UPDATE sessions
SET revoked_at = $1::timestamptz, revoked_reason = 'device_relogin'
WHERE user_id = $2 AND install_id = $3::text AND revoked_at IS NULL
RETURNING id
`

type RevokeInstallSessionsParams struct {
	At        time.Time
	UserID    uuid.UUID
	InstallID string
}

// Sessions and refresh-token families (Appendix C §C.4.4, R2, R37, R83). PostgreSQL is the source of truth;
// Redis auth:* keys are a hot index rebuilt from these rows.
// R83: one live session per (user, install); a re-login on the same install revokes the older one first.
func (q *Queries) RevokeInstallSessions(ctx context.Context, arg RevokeInstallSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeInstallSessions, arg.At, arg.UserID, arg.InstallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE id = $3
RETURNING token_hash
`

type RevokeRefreshTokenParams struct {
	At     time.Time
	Reason string
	ID     uuid.UUID
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, arg.At, arg.Reason, arg.ID)
	var token_hash []byte
	err := row.Scan(&token_hash)
	return token_hash, err
}

const revokeSessionTokens = `-- name: RevokeSessionTokens :many
UPDATE refresh_tokens SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE session_id = ANY ($3::uuid[]) AND revoked_at IS NULL
RETURNING token_hash
`

type RevokeSessionTokensParams struct {
	At         time.Time
	Reason     string
	SessionIds []uuid.UUID
}

func (q *Queries) RevokeSessionTokens(ctx context.Context, arg RevokeSessionTokensParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, revokeSessionTokens, arg.At, arg.Reason, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var token_hash []byte
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessions = `-- name: RevokeSessions :many
UPDATE sessions
SET revoked_at = $1::timestamptz, revoked_reason = $2::text, revoked_by = $3
WHERE user_id = $4
  AND revoked_at IS NULL
  AND ($5::uuid[] IS NULL OR id = ANY ($5::uuid[]))
  AND ($6::uuid IS NULL OR id <> $6::uuid)
RETURNING id, install_id
`

type RevokeSessionsParams struct {
	At        time.Time
	Reason    string
	RevokedBy *uuid.UUID
	UserID    uuid.UUID
	OnlyIds   []uuid.UUID
	ExceptID  *uuid.UUID
}

type RevokeSessionsRow struct {
	ID        uuid.UUID
	InstallID *string
}

// Revokes live sessions of one user: all of them, only those in only_ids, and never except_id.
func (q *Queries) RevokeSessions(ctx context.Context, arg RevokeSessionsParams) ([]RevokeSessionsRow, error) {
	rows, err := q.db.Query(ctx, revokeSessions,
		arg.At,
		arg.Reason,
		arg.RevokedBy,
		arg.UserID,
		arg.OnlyIds,
		arg.ExceptID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeSessionsRow{}
	for rows.Next() {
		var i RevokeSessionsRow
		if err := rows.Scan(&i.ID, &i.InstallID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens SET rotated_at = $1::timestamptz, replaced_by = $2::uuid WHERE id = $3
`

type RotateRefreshTokenParams struct {
	At         time.Time
	ReplacedBy uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.At, arg.ReplacedBy, arg.ID)
	return err
}

const sessionAuthState = `-- name: SessionAuthState :one
SELECT u.auth_version, s.revoked_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.user_id = $2
`

type SessionAuthStateParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
}

type SessionAuthStateRow struct {
	AuthVersion int32
	RevokedAt   *time.Time
}

// The PostgreSQL side of the per-request check (C.4.3: never fail open): on a version miss, for a token
// newer than the cached version, and whenever Redis is unreachable.
func (q *Queries) SessionAuthState(ctx context.Context, arg SessionAuthStateParams) (SessionAuthStateRow, error) {
	row := q.db.QueryRow(ctx, sessionAuthState, arg.SessionID, arg.UserID)
	var i SessionAuthStateRow
	err := row.Scan(&i.AuthVersion, &i.RevokedAt)
	return i, err
}

const setActiveTenant = `-- name: SetActiveTenant :exec
UPDATE sessions SET active_tenant_id = $1 WHERE id = $2
`

type SetActiveTenantParams struct {
	TenantID *uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetActiveTenant(ctx context.Context, arg SetActiveTenantParams) error {
	_, err := q.db.Exec(ctx, setActiveTenant, arg.TenantID, arg.ID)
	return err
}

const setSuccessor = `-- name: SetSuccessor :exec
UPDATE refresh_tokens SET replaced_by = $1::uuid WHERE id = $2
`

type SetSuccessorParams struct {
	ReplacedBy uuid.UUID
	ID         uuid.UUID
}

// Grace path (R37): the rotated token now points at the sibling; rotated_at keeps the first rotation time,
// so the 30 s window never grows.
func (q *Queries) SetSuccessor(ctx context.Context, arg SetSuccessorParams) error {
	_, err := q.db.Exec(ctx, setSuccessor, arg.ReplacedBy, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1::timestamptz, ip = coalesce($2::inet, ip) WHERE id = $3
`

type TouchSessionParams struct {
	At time.Time
	Ip *netip.Addr
	ID uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.At, arg.Ip, arg.ID)
	return err
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = $1::timestamptz WHERE id = $2
`

type UsePasswordResetTokenParams struct {
	At time.Time
	ID uuid.UUID
}

func (q *Queries) UsePasswordResetToken(ctx context.Context, arg UsePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, arg.At, arg.ID)
	return err
}
