// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpAuthVersion = `-- name: BumpAuthVersion :one
UPDATE users SET auth_version = auth_version + 1 WHERE id = $1 RETURNING auth_version
`

func (q *Queries) BumpAuthVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpAuthVersion, id)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const getDriverForUser = `-- name: GetDriverForUser :one
SELECT id, tenant_id, mobile FROM drivers WHERE user_id = $1::uuid
`

type GetDriverForUserRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Mobile   string
}

// The principal's DriverID comes from drivers.user_id, never from a uid search (C.1.4).
func (q *Queries) GetDriverForUser(ctx context.Context, userID uuid.UUID) (GetDriverForUserRow, error) {
	row := q.db.QueryRow(ctx, getDriverForUser, userID)
	var i GetDriverForUserRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Mobile)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified, display_name, photo_file_id, password_hash, legacy_scrypt_hash, legacy_scrypt_salt,
       status, must_change_password, auth_version, password_changed_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID                 uuid.UUID
	Email              *string
	EmailVerified      bool
	DisplayName        *string
	PhotoFileID        *uuid.UUID
	PasswordHash       *string
	LegacyScryptHash   []byte
	LegacyScryptSalt   []byte
	Status             string
	MustChangePassword bool
	AuthVersion        int32
	PasswordChangedAt  *time.Time
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.PhotoFileID,
		&i.PasswordHash,
		&i.LegacyScryptHash,
		&i.LegacyScryptSalt,
		&i.Status,
		&i.MustChangePassword,
		&i.AuthVersion,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one

SELECT id, email, password_hash, legacy_scrypt_hash, legacy_scrypt_salt, status, must_change_password, auth_version
FROM users
WHERE email = $1::citext AND status <> 'deleted'
`

type GetUserForLoginRow struct {
	ID                 uuid.UUID
	Email              *string
	PasswordHash       *string
	LegacyScryptHash   []byte
	LegacyScryptSalt   []byte
	Status             string
	MustChangePassword bool
	AuthVersion        int32
}

// Users, credentials and the principal's axes (Appendix C §C.1.3, §C.4.8, §C.5.4). Every statement runs
// inside db.WithSystem: auth reads and writes identity rows before a principal exists (R12).
// Login lookup (C.5.4): deleted users do not exist for login; the partial unique index users_email
// guarantees at most one row.
func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LegacyScryptHash,
		&i.LegacyScryptSalt,
		&i.Status,
		&i.MustChangePassword,
		&i.AuthVersion,
	)
	return i, err
}

const lastActiveTenant = `-- name: LastActiveTenant :one
SELECT active_tenant_id FROM sessions
WHERE user_id = $1 AND active_tenant_id IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The tenant the user worked in most recently: the default tenant of a new login.
func (q *Queries) LastActiveTenant(ctx context.Context, userID uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lastActiveTenant, userID)
	var active_tenant_id *uuid.UUID
	err := row.Scan(&active_tenant_id)
	return active_tenant_id, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT m.tenant_id, m.role, t.kind, t.name_th, t.name_en, t.status AS tenant_status
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1 AND m.status = 'active' AND t.kind <> 'quarantine'
ORDER BY (t.kind = 'own_fleet') DESC, t.name_th, t.id
`

type ListMembershipsRow struct {
	TenantID     uuid.UUID
	Role         string
	Kind         string
	NameTh       string
	NameEn       *string
	TenantStatus string
}

// Active memberships in non-quarantine tenants, own fleet first (the default-tenant order).
func (q *Queries) ListMemberships(ctx context.Context, userID uuid.UUID) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.Role,
			&i.Kind,
			&i.NameTh,
			&i.NameEn,
			&i.TenantStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformRoles = `-- name: ListPlatformRoles :many
SELECT role FROM user_platform_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListPlatformRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlatformRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopes = `-- name: ListScopes :many
SELECT s.kind, s.billing_party_id, coalesce(c.name, t.name_th, '')::text AS party_name
FROM user_scopes s
JOIN billing_parties bp ON bp.id = s.billing_party_id
LEFT JOIN customers c ON c.id = bp.customer_id
LEFT JOIN tenants t ON t.id = bp.tenant_id
WHERE s.user_id = $1
ORDER BY s.kind, s.created_at, s.billing_party_id
`

type ListScopesRow struct {
	Kind           string
	BillingPartyID uuid.UUID
	PartyName      string
}

// Customer scopes and dispatcher grants (R86), with the party name for GET /v1/me.
func (q *Queries) ListScopes(ctx context.Context, userID uuid.UUID) ([]ListScopesRow, error) {
	rows, err := q.db.Query(ctx, listScopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopesRow{}
	for rows.Next() {
		var i ListScopesRow
		if err := rows.Scan(&i.Kind, &i.BillingPartyID, &i.PartyName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id, email, password_hash, legacy_scrypt_hash, legacy_scrypt_salt, status, must_change_password, auth_version
FROM users
WHERE id = $1
FOR NO KEY UPDATE
`

type LockUserRow struct {
	ID                 uuid.UUID
	Email              *string
	PasswordHash       *string
	LegacyScryptHash   []byte
	LegacyScryptSalt   []byte
	Status             string
	MustChangePassword bool
	AuthVersion        int32
}

// Serialises logins, refreshes, password changes, tenant switches and revocations of one user. It is the
// first lock of every auth transaction that writes sessions or refresh_tokens (lock order users ->
// sessions -> refresh_tokens; RevokeInTx callers such as internal/iam follow it too). NO KEY UPDATE
// conflicts with itself and with every UPDATE of users, but not with the KEY SHARE locks that foreign-key
// checks of other tables take, so it serialises auth without blocking unrelated inserts.
func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i LockUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LegacyScryptHash,
		&i.LegacyScryptSalt,
		&i.Status,
		&i.MustChangePassword,
		&i.AuthVersion,
	)
	return i, err
}

const rehashPassword = `-- name: RehashPassword :exec
UPDATE users
SET password_hash = $1::text, legacy_scrypt_hash = NULL, legacy_scrypt_salt = NULL
WHERE id = $2
`

type RehashPasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

// Transparent upgrade of a legacy Firebase-scrypt or weaker Argon2id hash (C.5.4): the plaintext is
// unchanged, so password_changed_at and auth_version stay as they are.
func (q *Queries) RehashPassword(ctx context.Context, arg RehashPasswordParams) error {
	_, err := q.db.Exec(ctx, rehashPassword, arg.PasswordHash, arg.ID)
	return err
}

const setPassword = `-- name: SetPassword :one
UPDATE users
SET password_hash        = $1::text,
    legacy_scrypt_hash   = NULL,
    legacy_scrypt_salt   = NULL,
    must_change_password = false,
    password_changed_at  = $2::timestamptz,
    status               = CASE WHEN status = 'reset_required' THEN 'active' ELSE status END,
    auth_version         = auth_version + 1
WHERE id = $3
RETURNING auth_version
`

type SetPasswordParams struct {
	PasswordHash string
	ChangedAt    time.Time
	ID           uuid.UUID
}

// Every password set (change, reset, ticket change) ends the legacy hash, clears the must-change flag,
// re-activates a reset_required user and bumps auth_version (C.4.7, C.4.8).
func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (int32, error) {
	row := q.db.QueryRow(ctx, setPassword, arg.PasswordHash, arg.ChangedAt, arg.ID)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users
SET last_login_at         = $1::timestamptz,
    last_login_lat        = $2,
    last_login_lng        = $3,
    last_login_geo_source = $4,
    last_login_accuracy_m = $5
WHERE id = $6
`

type TouchLastLoginParams struct {
	At        time.Time
	Lat       *float64
	Lng       *float64
	GeoSource *string
	AccuracyM *float64
	ID        uuid.UUID
}

func (q *Queries) TouchLastLogin(ctx context.Context, arg TouchLastLoginParams) error {
	_, err := q.db.Exec(ctx, touchLastLogin,
		arg.At,
		arg.Lat,
		arg.Lng,
		arg.GeoSource,
		arg.AccuracyM,
		arg.ID,
	)
	return err
}

const updateLastLoginGeo = `-- name: UpdateLastLoginGeo :exec
UPDATE users
SET last_login_lat        = $1,
    last_login_lng        = $2,
    last_login_geo_source = $3,
    last_login_accuracy_m = $4
WHERE id = $5
`

type UpdateLastLoginGeoParams struct {
	Lat       *float64
	Lng       *float64
	GeoSource *string
	AccuracyM *float64
	ID        uuid.UUID
}

func (q *Queries) UpdateLastLoginGeo(ctx context.Context, arg UpdateLastLoginGeoParams) error {
	_, err := q.db.Exec(ctx, updateLastLoginGeo,
		arg.Lat,
		arg.Lng,
		arg.GeoSource,
		arg.AccuracyM,
		arg.ID,
	)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users
SET display_name  = coalesce($1, display_name),
    photo_file_id = coalesce($2, photo_file_id)
WHERE id = $3
`

type UpdateProfileParams struct {
	DisplayName *string
	PhotoFileID *uuid.UUID
	ID          uuid.UUID
}

// PATCH /v1/me: profile columns only (the column guard t_users_self_columns allows the same set).
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.DisplayName, arg.PhotoFileID, arg.ID)
	return err
}
