// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package jobsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimQueuedJob = `-- name: ClaimQueuedJob :one
SELECT id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at FROM jobs
 WHERE type = $1 AND status = 'queued'
 ORDER BY created_at, id
 LIMIT 1
   FOR UPDATE SKIP LOCKED
`

// Jobs the scheduler runs itself (queue.replay): the oldest queued one nobody else holds.
func (q *Queries) ClaimQueuedJob(ctx context.Context, type_ string) (Job, error) {
	row := q.db.QueryRow(ctx, claimQueuedJob, type_)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :one
UPDATE jobs SET status = $1, result = $2, error = $3, finished_at = now(),
                started_at = coalesce(started_at, now())
 WHERE id = $4 AND status IN ('queued', 'running')
RETURNING id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at
`

type FinishJobParams struct {
	Status string
	Result []byte
	Error  *string
	ID     uuid.UUID
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, finishJob,
		arg.Status,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (id, type, owner_user_id, tenant_id, params)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at
`

type InsertJobParams struct {
	ID          uuid.UUID
	Type        string
	OwnerUserID *uuid.UUID
	TenantID    *uuid.UUID
	Params      []byte
}

// The id is minted in Go (uuidv7) so the Redis job lock can hold it before the row commits.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.OwnerUserID,
		arg.TenantID,
		arg.Params,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at FROM jobs
 WHERE ($1::uuid IS NULL OR owner_user_id = $1::uuid)
   AND ($2::text IS NULL OR type = $2::text)
   AND ($3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid))
 ORDER BY created_at DESC, id DESC
 LIMIT $5::int
`

type ListJobsParams struct {
	OwnerUserID     *uuid.UUID
	JobType         *string
	BeforeCreatedAt *time.Time
	BeforeID        *uuid.UUID
	RowLimit        int32
}

// GET /v1/jobs: keyset on (created_at DESC, id DESC); owner NULL = every job (platform callers).
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.OwnerUserID,
		arg.JobType,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.OwnerUserID,
			&i.TenantID,
			&i.Params,
			&i.Progress,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneJobs = `-- name: PruneJobs :execrows
DELETE FROM jobs
 WHERE id IN (SELECT j.id FROM jobs AS j WHERE j.created_at < $1::timestamptz ORDER BY j.created_at LIMIT $2::int)
`

type PruneJobsParams struct {
	Cutoff    time.Time
	BatchSize int32
}

// jobs.prune (Appendix B §B.5.6): rows created before the cutoff, one batch per call.
func (q *Queries) PruneJobs(ctx context.Context, arg PruneJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneJobs, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobProgress = `-- name: SetJobProgress :one
UPDATE jobs SET progress = $1 WHERE id = $2 AND status = 'running'
RETURNING id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at
`

type SetJobProgressParams struct {
	Progress []byte
	ID       uuid.UUID
}

func (q *Queries) SetJobProgress(ctx context.Context, arg SetJobProgressParams) (Job, error) {
	row := q.db.QueryRow(ctx, setJobProgress, arg.Progress, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const startJob = `-- name: StartJob :one
UPDATE jobs SET status = 'running', started_at = coalesce(started_at, now())
 WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, type, status, owner_user_id, tenant_id, params, progress, result, error, created_at, started_at, finished_at
`

func (q *Queries) StartJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, startJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.OwnerUserID,
		&i.TenantID,
		&i.Params,
		&i.Progress,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
