// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package jobsdb

import (
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID          uuid.UUID
	Type        string
	Status      string
	OwnerUserID *uuid.UUID
	TenantID    *uuid.UUID
	Params      []byte
	Progress    []byte
	Result      []byte
	Error       *string
	CreatedAt   time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
}
