// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const idempotencyClaim = `-- name: IdempotencyClaim :one
INSERT INTO idempotency_keys AS k (scope, key, request_hash, status, expires_at)
VALUES ($1, $2, $3, 'in_progress', now() + make_interval(secs => $4::float8))
ON CONFLICT (scope, key) DO UPDATE
   SET request_hash  = EXCLUDED.request_hash,
       status        = 'in_progress',
       response_code = NULL,
       response_body = NULL,
       created_at    = now(),
       expires_at    = EXCLUDED.expires_at
 WHERE k.expires_at <= now()
    OR (k.status = 'in_progress' AND k.created_at < now() - make_interval(secs => $5::float8))
RETURNING k.created_at
`

type IdempotencyClaimParams struct {
	Scope       string
	Key         string
	RequestHash string
	TtlSeconds  float64
	LockSeconds float64
}

// Durable Idempotency-Key records (Appendix B §B.1.5, R53; idempotency_keys is RLS-exempt and only the
// httpx/idempotency middleware touches it). Claims (scope, key) for one execution: inserts an in_progress
// row, or takes over a row that expired (IDEMPOTENCY_TTL) or an in_progress row older than the in-flight
// lock (its holder died). The returned created_at is the claim's fencing token for Complete and Release.
// No row: the key is completed or held by a live request; read it with IdempotencyGet.
func (q *Queries) IdempotencyClaim(ctx context.Context, arg IdempotencyClaimParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, idempotencyClaim,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.TtlSeconds,
		arg.LockSeconds,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const idempotencyComplete = `-- name: IdempotencyComplete :execrows
UPDATE idempotency_keys
   SET status = 'completed', response_code = $1::int, response_body = $2::jsonb
 WHERE scope = $3 AND key = $4 AND status = 'in_progress' AND created_at = $5
`

type IdempotencyCompleteParams struct {
	ResponseCode int32
	ResponseBody []byte
	Scope        string
	Key          string
	ClaimedAt    pgtype.Timestamptz
}

// Stores the response of the claim made at claimed_at.
func (q *Queries) IdempotencyComplete(ctx context.Context, arg IdempotencyCompleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, idempotencyComplete,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Scope,
		arg.Key,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const idempotencyGet = `-- name: IdempotencyGet :one
SELECT request_hash, status, response_code, response_body, created_at, expires_at
FROM idempotency_keys
WHERE scope = $1 AND key = $2 AND expires_at > now()
`

type IdempotencyGetParams struct {
	Scope string
	Key   string
}

type IdempotencyGetRow struct {
	RequestHash  string
	Status       string
	ResponseCode *int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

// The live (not expired) record of (scope, key).
func (q *Queries) IdempotencyGet(ctx context.Context, arg IdempotencyGetParams) (IdempotencyGetRow, error) {
	row := q.db.QueryRow(ctx, idempotencyGet, arg.Scope, arg.Key)
	var i IdempotencyGetRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const idempotencyPrune = `-- name: IdempotencyPrune :execrows
DELETE FROM idempotency_keys
 WHERE (scope, key) IN (SELECT i.scope, i.key FROM idempotency_keys AS i
                         WHERE i.expires_at <= now() ORDER BY i.expires_at LIMIT $1::int)
`

// idempotency.prune (scheduler, Appendix B §B.5.6): deletes up to batch_size expired rows.
func (q *Queries) IdempotencyPrune(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, idempotencyPrune, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const idempotencyRelease = `-- name: IdempotencyRelease :execrows
DELETE FROM idempotency_keys
 WHERE scope = $1 AND key = $2 AND status = 'in_progress' AND created_at = $3
`

type IdempotencyReleaseParams struct {
	Scope     string
	Key       string
	ClaimedAt pgtype.Timestamptz
}

// Drops the claim made at claimed_at: the request failed and committed nothing, so a retry with the
// same key runs again.
func (q *Queries) IdempotencyRelease(ctx context.Context, arg IdempotencyReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, idempotencyRelease, arg.Scope, arg.Key, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
