// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package dbq

import (
	"context"
)

const currentLogin = `-- name: CurrentLogin :one
SELECT r.rolname::text                  AS role_name,
       coalesce(r.rolsuper, false)      AS superuser,
       coalesce(r.rolbypassrls, false)  AS bypass_rls
FROM pg_catalog.pg_roles AS r
WHERE r.rolname = current_user
`

type CurrentLoginRow struct {
	RoleName  string
	Superuser bool
	BypassRls bool
}

// The role this connection runs as (cmd/migrate preflight, R66). Catalog only, no tenant rows.
func (q *Queries) CurrentLogin(ctx context.Context) (CurrentLoginRow, error) {
	row := q.db.QueryRow(ctx, currentLogin)
	var i CurrentLoginRow
	err := row.Scan(&i.RoleName, &i.Superuser, &i.BypassRls)
	return i, err
}
