export const PROVINCES = [
    { value: "Bangkok", label: "Bangkok / กรุงเทพมหานคร" },
    { value: "Samut Prakan", label: "Samut Prakan / สมุทรปราการ" },
    { value: "Nonthaburi", label: "Nonthaburi / นนทบุรี" },
    { value: "Pathum Thani", label: "Pathum Thani / ปทุมธานี" },
    { value: "Phra Nakhon Si Ayutthaya", label: "Phra Nakhon Si Ayutthaya / พระนครศรีอยุธยา" },
    { value: "Ang Thong", label: "Ang Thong / อ่างทอง" },
    { value: "Lopburi", label: "Lopburi / ลพบุรี" },
    { value: "Sing Buri", label: "Sing Buri / สิงห์บุรี" },
    { value: "Chai Nat", label: "Chai Nat / ชัยนาท" },
    { value: "Saraburi", label: "Saraburi / สระบุรี" },
    { value: "Chon Buri", label: "Chon Buri / ชลบุรี" },
    { value: "Rayong", label: "Rayong / ระยอง" },
    { value: "Chanthaburi", label: "Chanthaburi / จันทบุรี" },
    { value: "Trat", label: "Trat / ตราด" },
    { value: "Chachoengsao", label: "Chachoengsao / ฉะเชิงเทรา" },
    { value: "Prachin Buri", label: "Prachin Buri / ปราจีนบุรี" },
    { value: "Nakhon Nayok", label: "Nakhon Nayok / นครนายก" },
    { value: "Sa Kaeo", label: "Sa Kaeo / สระแก้ว" },
    { value: "Nakhon Ratchasima", label: "Nakhon Ratchasima / นครราชสีมา" },
    { value: "Buri Ram", label: "Buri Ram / บุรีรัมย์" },
    { value: "Surin", label: "Surin / สุรินทร์" },
    { value: "Si Sa Ket", label: "Si Sa Ket / ศรีสะเกษ" },
    { value: "Ubon Ratchathani", label: "Ubon Ratchathani / อุบลราชธานี" },
    { value: "Yasothon", label: "Yasothon / ยโสธร" },
    { value: "Chaiyaphum", label: "Chaiyaphum / ชัยภูมิ" },
    { value: "Amnat Charoen", label: "Amnat Charoen / อำนาจเจริญ" },
    { value: "Bueng Kan", label: "Bueng Kan / บึงกาฬ" },
    { value: "Nong Bua Lam Phu", label: "Nong Bua Lam Phu / หนองบัวลำภู" },
    { value: "Khon Kaen", label: "Khon Kaen / ขอนแก่น" },
    { value: "Udon Thani", label: "Udon Thani / อุดรธานี" },
    { value: "Loei", label: "Loei / เลย" },
    { value: "Nong Khai", label: "Nong Khai / หนองคาย" },
    { value: "Maha Sarakham", label: "Maha Sarakham / มหาสารคาม" },
    { value: "Roi Et", label: "Roi Et / ร้อยเอ็ด" },
    { value: "Kalasin", label: "Kalasin / กาฬสินธุ์" },
    { value: "Sakon Nakhon", label: "Sakon Nakhon / สกลนคร" },
    { value: "Nakhon Phanom", label: "Nakhon Phanom / นครพนม" },
    { value: "Mukdahan", label: "Mukdahan / มุกดาหาร" },
    { value: "Chiang Mai", label: "Chiang Mai / เชียงใหม่" },
    { value: "Lamphun", label: "Lamphun / ลำพูน" },
    { value: "Lampang", label: "Lampang / ลำปาง" },
    { value: "Uttaradit", label: "Uttaradit / อุตรดิตถ์" },
    { value: "Phrae", label: "Phrae / แพร่" },
    { value: "Nan", label: "Nan / น่าน" },
    { value: "Phayao", label: "Phayao / พะเยา" },
    { value: "Chiang Rai", label: "Chiang Rai / เชียงราย" },
    { value: "Mae Hong Son", label: "Mae Hong Son / แม่ฮ่องสอน" },
    { value: "Nakhon Sawan", label: "Nakhon Sawan / นครสวรรค์" },
    { value: "Uthai Thani", label: "Uthai Thani / อุทัยธานี" },
    { value: "Kamphaeng Phet", label: "Kamphaeng Phet / กำแพงเพชร" },
    { value: "Tak", label: "Tak / ตาก" },
    { value: "Sukhothai", label: "Sukhothai / สุโขทัย" },
    { value: "Phitsanulok", label: "Phitsanulok / พิษณุโลก" },
    { value: "Phichit", label: "Phichit / พิจิตร" },
    { value: "Phetchabun", label: "Phetchabun / เพชรบูรณ์" },
    { value: "Ratchaburi", label: "Ratchaburi / ราชบุรี" },
    { value: "Kanchanaburi", label: "Kanchanaburi / กาญจนบุรี" },
    { value: "Suphan Buri", label: "Suphan Buri / สุพรรณบุรี" },
    { value: "Nakhon Pathom", label: "Nakhon Pathom / นครปฐม" },
    { value: "Samut Sakhon", label: "Samut Sakhon / สมุทรสาคร" },
    { value: "Samut Songkhram", label: "Samut Songkhram / สมุทรสงคราม" },
    { value: "Phetchaburi", label: "Phetchaburi / เพชรบุรี" },
    { value: "Prachuap Khiri Khan", label: "Prachuap Khiri Khan / ประจวบคีรีขันธ์" },
    { value: "Nakhon Si Thammarat", label: "Nakhon Si Thammarat / นครศรีธรรมราช" },
    { value: "Krabi", label: "Krabi / กระบี่" },
    { value: "Phangnga", label: "Phangnga / พังงา" },
    { value: "Phuket", label: "Phuket / ภูเก็ต" },
    { value: "Surat Thani", label: "Surat Thani / สุราษฎร์ธานี" },
    { value: "Ranong", label: "Ranong / ระนอง" },
    { value: "Chumphon", label: "Chumphon / ชุมพร" },
    { value: "Songkhla", label: "Songkhla / สงขลา" },
    { value: "Satun", label: "Satun / สตูล" },
    { value: "Trang", label: "Trang / ตรัง" },
    { value: "Phatthalung", label: "Phatthalung / พัทลุง" },
    { value: "Pattani", label: "Pattani / ปัตตานี" },
    { value: "Yala", label: "Yala / ยะลา" },
    { value: "Narathiwat", label: "Narathiwat / นราธิวาส" }
];
