package seed

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/smartcode54-bit/logi-track-plateform/logitrack-api/internal/platform/db"
)

// Mode is --mode: insert (the default, after --reset) or upsert (top up a shared database: missing rows only,
// never an UPDATE of an existing row).
type Mode string

// The two load modes.
const (
	ModeInsert Mode = "insert"
	ModeUpsert Mode = "upsert"
)

// LoadResult reports a load.
type LoadResult struct {
	Inserted map[string]int // rows written per table (upsert skips existing ones)
	Counters int            // task_number_counters rows written
	Duration time.Duration
}

// column is what the loader needs to know about one column.
type column struct {
	typ       string // format_type(atttypid, atttypmod)
	array     bool
	json      bool
	generated bool
	identity  bool
	def       string // pg_get_expr of the default
}

// introspect reads the columns of every table in tables.
func introspect(ctx context.Context, q pgx.Tx, tables []string) (map[string]map[string]column, error) {
	rows, err := q.Query(ctx, `SELECT c.relname::text, a.attname::text, format_type(a.atttypid, a.atttypmod),
		t.typcategory = 'A', t.typname IN ('json','jsonb'), a.attgenerated <> '', a.attidentity <> '',
		coalesce(pg_get_expr(d.adbin, d.adrelid), '')
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
		JOIN pg_type t ON t.oid = a.atttypid
		LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
		WHERE c.relname = ANY($1::text[]) AND c.relkind = 'r' AND a.attnum > 0 AND NOT a.attisdropped`, tables)
	if err != nil {
		return nil, err
	}
	out := map[string]map[string]column{}
	err = scanAll(rows, func(r pgx.Rows) error {
		var table, name string
		var c column
		if err := r.Scan(&table, &name, &c.typ, &c.array, &c.json, &c.generated, &c.identity, &c.def); err != nil {
			return err
		}
		if out[table] == nil {
			out[table] = map[string]column{}
		}
		out[table][name] = c
		return nil
	})
	if err != nil {
		return nil, err
	}
	for _, t := range tables {
		if out[t] == nil {
			return nil, fmt.Errorf("seed: table %s does not exist: run make migrate first", t)
		}
	}
	return out, nil
}

// clockDefault reports a default that reads the clock: an omitted column with one gets the row's created_at
// so two runs write the same value (§D.4.1).
func clockDefault(def string) bool {
	d := strings.ToLower(def)
	return strings.Contains(d, "now()") || strings.Contains(d, "current_timestamp") ||
		strings.Contains(d, "statement_timestamp()") || strings.Contains(d, "transaction_timestamp()") ||
		strings.Contains(d, "clock_timestamp()")
}

// randomDefault reports a default that differs on every run.
func randomDefault(def string) bool {
	d := strings.ToLower(def)
	return strings.Contains(d, "uuidv7()") || strings.Contains(d, "gen_random_uuid()") || strings.Contains(d, "random()")
}

// param turns one value into an argument and its placeholder: text cast to the column type, text[] for
// arrays, bytea for bytes, JSON text for json and jsonb.
func param(v any, c column, n int) (any, string, error) {
	cast := fmt.Sprintf("$%d::text::%s", n, c.typ)
	if v == nil {
		return nil, cast, nil
	}
	if c.json {
		b, err := json.Marshal(v)
		if err != nil {
			return nil, "", err
		}
		return string(b), cast, nil
	}
	switch x := v.(type) {
	case bool:
		return strconv.FormatBool(x), cast, nil
	case json.Number:
		return x.String(), cast, nil
	case string:
		if x == unresolved {
			return nil, "", errors.New("a computed value was not resolved (the plan is not materialized)")
		}
		return x, cast, nil
	case []byte:
		return x, fmt.Sprintf("$%d::bytea", n), nil
	case []any:
		if !c.array {
			return nil, "", fmt.Errorf("an array for the %s column", c.typ)
		}
		out := make([]string, len(x))
		for i, e := range x {
			switch s := e.(type) {
			case string:
				out[i] = s
			case json.Number:
				out[i] = s.String()
			default:
				return nil, "", fmt.Errorf("array element of type %T", e)
			}
		}
		return out, fmt.Sprintf("$%d::text[]::%s", n, c.typ), nil
	}
	return nil, "", fmt.Errorf("unsupported value of type %T", v)
}

// insertSQL builds the INSERT of one row and its arguments.
func insertSQL(table string, r Row, cols map[string]column, mode Mode) (string, []any, error) {
	names := r.Columns()
	ph := make([]string, 0, len(names))
	args := make([]any, 0, len(names))
	idents := make([]string, 0, len(names))
	for _, name := range names {
		c, ok := cols[name]
		if !ok {
			return "", nil, fmt.Errorf("%s has no column %s", table, name)
		}
		if c.generated || c.identity {
			return "", nil, fmt.Errorf("%s.%s is generated by the database and never written", table, name)
		}
		arg, p, err := param(r[name], c, len(args)+1)
		if err != nil {
			return "", nil, fmt.Errorf("%s.%s: %w", table, name, err)
		}
		args = append(args, arg)
		ph = append(ph, p)
		idents = append(idents, pgx.Identifier{name}.Sanitize())
	}
	sql := "INSERT INTO " + pgx.Identifier{table}.Sanitize() + " (" + strings.Join(idents, ", ") + ") VALUES (" +
		strings.Join(ph, ", ") + ")"
	if mode == ModeUpsert {
		sql += " ON CONFLICT DO NOTHING"
	}
	return sql, args, nil
}

// prepare completes a row for insert: the clock defaults it omits get its created_at, a random default it
// omits is refused, and the deferred columns are split off for the back-fill.
func prepare(table string, r Row, cols map[string]column) (Row, Row, error) {
	row := r.clone()
	created := row["created_at"]
	if created == nil {
		created = fallbackCreatedAt.Format(time.RFC3339)
	}
	for name, c := range cols {
		if _, ok := row[name]; ok || c.generated || c.identity || c.def == "" {
			continue
		}
		if _, deferred := Deferred[table][name]; deferred {
			continue
		}
		switch {
		case clockDefault(c.def) && strings.HasPrefix(c.typ, "timestamp"):
			row[name] = created
		case randomDefault(c.def):
			return nil, nil, fmt.Errorf("%s omits %s, whose default (%s) differs on every run", table, name, c.def)
		}
	}
	var later Row
	for name, initial := range Deferred[table] {
		v, ok := row[name]
		if !ok {
			continue
		}
		if v != nil {
			if later == nil {
				later = Row{}
			}
			later[name] = v
		}
		if initial == nil {
			delete(row, name)
		} else {
			row[name] = initial
		}
	}
	return row, later, nil
}

// Load writes the plan through the ETL login (logitrack_etl, R87) in one db.WithSystem transaction: the
// tables in load order, then the back-filled forward references, the derived task_number_counters and the
// engine check, so a price the engine does not reproduce rolls everything back (Appendix D §D.1.4, §D.1.5).
func Load(ctx context.Context, etl db.Beginner, p *Plan, mode Mode) (LoadResult, error) {
	start := time.Now()
	res := LoadResult{Inserted: map[string]int{}}
	err := db.WithSystem(ctx, etl, nil, func(tx pgx.Tx) error {
		cols, err := introspect(ctx, tx, append(slices.Clone(LoadOrder), DerivedTable))
		if err != nil {
			return err
		}
		type backfill struct {
			table string
			id    string
			set   Row
		}
		var later []backfill
		inserted := map[string]map[string]bool{} // table -> ids written by this load
		for _, table := range LoadOrder {
			rows := p.Tables[table]
			if mode == ModeUpsert {
				rows = keepWritable(table, rows, inserted)
			}
			if len(rows) == 0 {
				continue
			}
			batch := &pgx.Batch{}
			var pending []backfill
			for i, r := range rows {
				row, set, err := prepare(table, r, cols[table])
				if err != nil {
					return fmt.Errorf("seed: %s row %d: %w", table, i+1, err)
				}
				sql, args, err := insertSQL(table, row, cols[table], mode)
				if err != nil {
					return fmt.Errorf("seed: %s row %d: %w", table, i+1, err)
				}
				batch.Queue(sql, args...)
				pending = append(pending, backfill{table: table, id: r.Str("id"), set: set})
			}
			br := tx.SendBatch(ctx, batch)
			for i := range rows {
				tag, err := br.Exec()
				if err != nil {
					_ = br.Close()
					return fmt.Errorf("seed: insert %s row %d (%s): %w", table, i+1, describe(rows[i]), err)
				}
				if tag.RowsAffected() == 1 {
					res.Inserted[table]++
					if inserted[table] == nil {
						inserted[table] = map[string]bool{}
					}
					inserted[table][rows[i].Str("id")] = true
					if pending[i].set != nil {
						later = append(later, pending[i]) // upsert back-fills only the rows it inserted
					}
				}
			}
			if err := br.Close(); err != nil {
				return fmt.Errorf("seed: insert %s: %w", table, err)
			}
		}
		for _, b := range later {
			if err := backfillRow(ctx, tx, b.table, b.id, b.set, cols[b.table]); err != nil {
				return err
			}
		}
		if res.Counters, err = deriveCounters(ctx, tx, ids(p.Tables["tasks"])); err != nil {
			return err
		}
		mism, err := CheckEngine(ctx, tx, engineTrips(p), engineStandby(p))
		if err != nil {
			return err
		}
		if len(mism) > 0 {
			lines := make([]string, len(mism))
			for i, m := range mism {
				lines[i] = m.String()
			}
			return fmt.Errorf("seed: the billing engine does not reproduce %d seeded value(s), load rolled back:\n  %s",
				len(mism), strings.Join(lines, "\n  "))
		}
		return nil
	})
	res.Duration = time.Since(start)
	return res, err
}

// upsertParents are children whose insert trigger refuses a parent that is no longer a draft: the lines of
// a payroll run are writable only while the run is draft (BEFORE INSERT fires before ON CONFLICT is
// decided), so an upsert writes them only under a run it inserted itself; an existing run keeps its lines.
var upsertParents = map[string][2]string{"payroll_line_items": {"payroll_runs", "payroll_run_id"}}

// keepWritable drops the rows an upsert must not attempt (upsertParents).
func keepWritable(table string, rows []Row, inserted map[string]map[string]bool) []Row {
	parent, ok := upsertParents[table]
	if !ok {
		return rows
	}
	out := make([]Row, 0, len(rows))
	for _, r := range rows {
		if inserted[parent[0]][r.Str(parent[1])] {
			out = append(out, r)
		}
	}
	return out
}

// describe names a row in an error without its values (no credential reaches a log line).
func describe(r Row) string {
	for _, k := range []string{"id", "trip_id", "user_id", "key", "alias", "broadcast_id", "payroll_run_id", "config_id"} {
		if v := r.Str(k); v != "" {
			return k + "=" + v
		}
	}
	return "composite key"
}

// backfillRow writes the deferred columns of one row.
func backfillRow(ctx context.Context, tx pgx.Tx, table, id string, set Row, cols map[string]column) error {
	names := set.Columns()
	parts := make([]string, 0, len(names))
	args := make([]any, 0, len(names)+1)
	for _, name := range names {
		arg, ph, err := param(set[name], cols[name], len(args)+1)
		if err != nil {
			return fmt.Errorf("seed: back-fill %s.%s: %w", table, name, err)
		}
		args = append(args, arg)
		parts = append(parts, pgx.Identifier{name}.Sanitize()+" = "+ph)
	}
	args = append(args, id)
	sql := fmt.Sprintf("UPDATE %s SET %s WHERE id = $%d::uuid", pgx.Identifier{table}.Sanitize(), strings.Join(parts, ", "), len(args))
	tag, err := tx.Exec(ctx, sql, args...)
	if err != nil {
		return fmt.Errorf("seed: back-fill %s %s: %w", table, id, err)
	}
	if tag.RowsAffected() != 1 {
		return fmt.Errorf("seed: back-fill %s %s: row not found", table, id)
	}
	return nil
}

// deriveCounters sets task_number_counters to the highest padded sequence per (task type, Bangkok plan
// date) of the seeded tasks, so the next POST /v1/tasks continues the numbering (R10). Legacy unpadded
// numbers do not count. An existing higher counter (a shared database) is kept.
func deriveCounters(ctx context.Context, tx pgx.Tx, taskIDs []uuid.UUID) (int, error) {
	tag, err := tx.Exec(ctx, `INSERT INTO task_number_counters AS c (task_type, plan_date, last_seq)
		SELECT task_type, plan_date, max((regexp_match(task_no, '-([0-9]{3,})$'))[1]::int)
		FROM tasks WHERE id = ANY($1::uuid[]) AND task_no ~ '^(FM|LH)-[0-9]{8}-[0-9]{3,}$'
		GROUP BY task_type, plan_date
		ON CONFLICT (task_type, plan_date) DO UPDATE SET last_seq = GREATEST(c.last_seq, EXCLUDED.last_seq)`, taskIDs)
	if err != nil {
		return 0, fmt.Errorf("seed: task_number_counters: %w", err)
	}
	return int(tag.RowsAffected()), nil
}

// ids are the ids of rows.
func ids(rows []Row) []uuid.UUID {
	out := make([]uuid.UUID, 0, len(rows))
	for _, r := range rows {
		if id, err := uuid.Parse(r.Str("id")); err == nil {
			out = append(out, id)
		}
	}
	return out
}

// engineTrips are the seeded snapshots the engine must reproduce (computed_by other than etl and
// manual_edit, which stand for legacy writers and are inserted verbatim).
func engineTrips(p *Plan) []uuid.UUID {
	out := []uuid.UUID{}
	for _, r := range p.Tables["trip_billing_snapshots"] {
		if by := r.Str("computed_by"); by == "etl" || by == "manual_edit" {
			continue
		}
		if id, err := uuid.Parse(r.Str("trip_id")); err == nil {
			out = append(out, id)
		}
	}
	return out
}

// engineStandby are the seeded completed standby records with a price or a stored reason.
func engineStandby(p *Plan) []uuid.UUID {
	out := []uuid.UUID{}
	for _, r := range p.Tables["standby_records"] {
		if r.Str("status") != "completed" || (r["billing_estimate_thb"] == nil && r["billing_unpriced_reason"] == nil) {
			continue
		}
		if id, err := uuid.Parse(r.Str("id")); err == nil {
			out = append(out, id)
		}
	}
	return out
}
