"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "th";

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Simple dictionary for translations
const translations = {
    en: {
        // Navigation
        "nav.home": "Home",
        "nav.dashboard": "Dashboard",
        "nav.trucks": "Truck",
        "nav.users": "Users",
        "nav.drivers": "Drivers",
        "nav.packages": "Packages",
        "nav.analytics": "Analytics",
        "nav.settings": "Settings",
        "nav.login": "Login",
        "nav.register": "Join Waitlist",
        "nav.logout": "Logout",
        "nav.myAccount": "My Account",
        "nav.myFavorite": "My Favorite",
        "nav.adminDashboard": "Admin Dashboard",
        "nav.propertyStockSearch": "Property stock search",
        "nav.waitlist": "Waitlist",
        "nav.platform": "Platform",

        "nav.truckManagement": "Truck Management",
        "nav.truckAssignment": "Truck Assignment",
        "nav.truckRenewals": "Truck Renewals",
        "nav.maintenanceCosts": "Maintenance Costs",
        "nav.manageSubcontractors": "Manage Subcontractors",
        "nav.driverManagement": "Driver Management",
        "nav.activeShipments": "Active Shipments",
        "nav.userRoles": "User Roles",
        "nav.reporting": "Reporting",
        "nav.operations": "Operations",
        "nav.firstMileTasks": "First Mile Tasks",
        "nav.sourceManagement": "Source Management",
        "nav.supportCenter": "Support Center",

        "nav.subcontractors": "Subcontractors",
        "nav.mainMenu": "MAIN MENU",
        "nav.system": "SYSTEM",

        // Home
        "home.welcome": "Welcome to Logi Track",

        // Auth
        "auth.login.title": "Login",
        "auth.login.subtitle": "Enter your email below to login to your account",
        "auth.register.title": "Join Waitlist",
        "auth.register.subtitle": "Enter your email to request access",
        "auth.email": "Email",
        "auth.password": "Password",
        "auth.confirmPassword": "Confirm Password",
        "auth.forgotPassword": "Forgot your password?",
        "auth.or": "or",
        "auth.dontHaveAccount": "You need to try our system?",
        "auth.alreadyHaveAccount": "Already have an account? Sign In",
        "auth.passwordsDoNotMatch": "Passwords do not match",
        "auth.passwordMinLength": "Password must be at least 6 characters",
        "auth.creatingAccount": "Creating Account...",
        "auth.signUp": "Join Waitlist",
        "auth.signIn": "Sign In",
        "auth.waitlist.description": "Registration is currently by invitation only. Join the waitlist to request access.",
        "auth.waitlist.submit": "Request Access",
        "auth.signingIn": "Signing in...",
        "auth.waitlist.successTitle": "You're on the list!",
        "auth.waitlist.successDesc": "Thank you for your interest. We'll verify your information and contact you when your account is ready.",
        "auth.backToLogin": "Back to Login",
        "auth.emailRequired": "Please enter your email address",
        "auth.waitlist.successToast": "Successfully joined the waitlist!",
        "auth.waitlist.errorToast": "Failed to join waitlist. Please try again.",

        // Admin Panel
        "admin.panel": "Admin Panel",

        // Dashboard
        "dashboard.title": "Admin Dashboard",
        "dashboard.subtitle": "Manage your logistics operations",
        "dashboard.manageUsers": "Manage Users",
        "dashboard.manageUsersDesc": "View and manage user accounts",
        "dashboard.manageDrivers": "Manage Drivers",
        "dashboard.manageDriversDesc": "View and manage driver accounts",
        "dashboard.managePackages": "Manage Packages",
        "dashboard.managePackagesDesc": "View and manage package deliveries",
        "dashboard.manageTrucks": "Manage Trucks",
        "dashboard.manageTrucksDesc": "View and manage truck fleet",
        "dashboard.analytics": "Analytics",
        "dashboard.analyticsDesc": "View delivery statistics and reports",

        // Trucks
        "trucks.title": "Trucks",
        "trucks.subtitle": "Manage your truck fleet",
        "trucks.addTruck": "Add Truck",
        "trucks.searchPlaceholder": "Search trucks...",
        "trucks.noTrucks": "No trucks yet",
        "trucks.getStarted": "Get started by adding your first truck.",
        "trucks.filter.own": "Own Fleet",
        "trucks.filter.subcontractor": "Subcontractor Trucks",
        "trucks.filter.all": "All Trucks",

        "trucks.monitor": "Monitor and manage all registered trucks in the system",
        "trucks.stats.tax": "Tax & Registration",
        "trucks.stats.insurance": "Insurance Status",
        "trucks.stats.maintenance": "Maintenance Service",
        "trucks.stats.incoming": "INCOMING",
        "trucks.stats.less30Days": "LESS 30 DAYS",
        "trucks.stats.overdue": "OVERDUE",
        "trucks.stats.pmIncoming": "PM INCOMING",
        "trucks.stats.pmDueSoon": "PM DUE SOON",
        "trucks.stats.pmOverdue": "PM OVERDUE",
        "trucks.stats.owner": "Action Owner",
        "trucks.stats.opAdmin": "Operation Admin",
        "trucks.stats.assignedDriver": "Assigned Driver",
        "trucks.filter.search": "Search by Plate Number, ID, or Model...",
        "trucks.filter.allTypes": "All Types",
        "trucks.filter.allStatuses": "All Statuses",
        "trucks.filter.allGroups": "All Groups",
        "trucks.filter.clear": "Clear Filters",
        "trucks.table.id": "ID",
        "trucks.table.plate": "PLATE NUMBER",
        "trucks.table.model": "MODEL",
        "trucks.table.driver": "CURRENT DRIVER",
        "trucks.table.ownership": "OWNERSHIP",
        "trucks.table.taxInsu": "TAX/INSU.",
        "trucks.table.pmStatus": "PM STATUS",
        "trucks.table.status": "STATUS",
        "trucks.export": "Export",
        "trucks.import": "Import Trucks",

        "trucks.import.title": "Import Trucks",
        "trucks.import.desc": "Upload an Excel or CSV file to import multiple trucks at once.",
        "trucks.import.downloadTemplate": "Download Template",
        "trucks.import.selectFile": "Select File",
        "trucks.import.parseError": "Error parsing file. Please check the format.",
        "trucks.import.preview": "Preview Data",
        "trucks.import.importing": "Importing...",
        "trucks.import.success": "Successfully imported {count} trucks",
        "trucks.import.error": "Failed to import trucks",
        "trucks.import.validation.missing": "Missing required fields",
        "trucks.import.confirm": "Confirm Import",

        "trucks.status.active": "Active",
        "trucks.status.maintenance": "Maintenance",
        "trucks.status.inTransit": "In Transit",
        "trucks.status.inactive": "Inactive",
        "trucks.badge.company": "COMPANY",
        "trucks.badge.partner": "PARTNER",
        "trucks.badge.taxInProcess": "Tax: In-process",
        "trucks.badge.taxOverdue": "Tax: Overdue",
        "trucks.badge.insuInProcess": "Insu: In-process",
        "trucks.badge.insuOverdue": "Insu: Overdue",
        "trucks.badge.pmInShop": "In Shop",
        "trucks.badge.pmOverdue": "PM: Overdue",
        "trucks.action.view": "View Details",
        "trucks.action.edit": "Edit Truck",
        "trucks.action.renewTax": "Renew - TAX",
        "trucks.action.renewInsu": "Renew - Insurance",
        "trucks.action.recordMain": "Record Maintenance",

        // Truck Wizard
        "trucks.wizard.title": "Truck Details Form",
        "trucks.wizard.subtitle": "Step {step} of {total}: Please enter the vehicle information below.",
        "trucks.wizard.step1.title": "Vehicle Specs",
        "trucks.wizard.step1.desc": "Make, Model, VIN",
        "trucks.wizard.step2.title": "Compliance",
        "trucks.wizard.step2.desc": "Registration & Insurance",
        "trucks.wizard.step3.title": "Maintenance",
        "trucks.wizard.step3.desc": "Engine & Status",
        "trucks.wizard.step4.title": "Documentation",
        "trucks.wizard.step4.desc": "Review & Save",
        "trucks.wizard.tips": "TIPS",
        "trucks.wizard.tips.vin": "Ensure the VIN matches the chassis engraving exactly for registration compliance.",
        "trucks.wizard.back": "Back",
        "trucks.wizard.cancel": "Cancel",
        "trucks.wizard.next": "Next Step",
        "trucks.wizard.save": "Save and Continue",
        "trucks.wizard.saving": "Saving...",

        "trucks.step1.title": "Step 1: Vehicle Specifications",
        "trucks.step1.appearance": "Vehicle Appearance",

        "trucks.step2.title": "Step 2: Compliance",
        "trucks.step2.desc": "Enter registration and insurance details.",
        "trucks.step2.subOptions": "Registration details are optional for subcontractor vehicles.",
        "trucks.step2.insurance": "Insurance Information",

        "trucks.step3.title": "Step 3: Engine Specifications",
        "trucks.step3.desc": "Details regarding engine specifications and capacity.",
        "trucks.step3.subOptions": "Detailed engine information is optional for subcontractor trucks.",
        "trucks.step3.maintenanceBook": "Maintenance Book",
        "trucks.step3.lastServiceDate": "Last Service Date",
        "trucks.step3.nextServiceDate": "Next Service Date",
        "trucks.step3.nextServiceMileage": "Next Service Mileage (km)",

        "trucks.step4.title": "Step 4: Review & Finalize",
        "trucks.step4.desc": "Please review all information before adding this vehicle to flight.",
        "trucks.step4.specs": "Vehicle Specs",
        "trucks.step4.compliance": "Compliance",
        "trucks.step4.insurance": "Insurance",
        "trucks.step4.ready": "Ready to Submit",
        "trucks.step4.readyDesc": "By clicking \"Save and Continue\", this vehicle will be added to the active fleet registry.",
        "trucks.step4.makeModel": "Make/Model",
        "trucks.step4.plate": "Plate",
        "trucks.step4.vin": "VIN",
        "trucks.step4.type": "Type",
        "trucks.step4.province": "Province",
        "trucks.step4.taxDoc": "Tax Doc",
        "trucks.step4.regDoc": "Reg Doc",
        "trucks.step4.uploaded": "Uploaded",
        "trucks.step4.pending": "Pending",
        "trucks.step4.provider": "Provider",
        "trucks.step4.policy": "Policy #",
        "trucks.step4.expiry": "Expiry",

        // Truck Wizard Sections
        "trucks.section.identification": "Identification",
        "trucks.section.licensePlate": "License Plate",
        "trucks.section.province": "Province",
        "trucks.section.vin": "VIN",
        "trucks.section.engineNumber": "Engine Number",
        "trucks.section.truckStatus": "Truck Status",

        "trucks.section.details": "Details",
        "trucks.section.brand": "Brand",
        "trucks.section.model": "Model",
        "trucks.section.year": "Year",
        "trucks.section.color": "Color",
        "trucks.section.truckType": "Truck Type",
        "trucks.section.seats": "Seats",

        "trucks.section.registration": "Registration",
        "trucks.section.taxExpiry": "Tax (Act) Expiry Date",
        "trucks.section.regDate": "Registration Date",
        "trucks.section.buyingDate": "Buying Date",
        "trucks.section.responsible": "Responsible Person (Tax)",
        "trucks.section.notes": "Notes",

        "trucks.section.insuranceInfo": "Insurance Information",
        "trucks.section.policyId": "Policy ID (Internal)",
        "trucks.section.policyNo": "Policy Number",
        "trucks.section.provider": "Provider",
        "trucks.section.coverageType": "Coverage Type",
        "trucks.section.selectType": "Select type",
        "trucks.section.premium": "Premium (Baht)",
        "trucks.section.startDate": "Start Date",
        "trucks.section.endDate": "End Date",
        "trucks.section.insuranceDocs": "Insurance Documents",
        "trucks.section.upload": "Upload PDF/Img",

        "trucks.section.engineInfo": "Engine Information",
        "trucks.section.fuelType": "Fuel Type",
        "trucks.section.selectFuel": "Select fuel type",
        "trucks.section.engineCap": "Engine Capacity (cc/kW)",
        "trucks.section.fuelCap": "Fuel Capacity (Liters/kWh)",
        "trucks.section.maxLoad": "Max Load Weight",

        // Placeholders
        "trucks.placeholder.licensePlate": "e.g. 1กก-1234",
        "trucks.placeholder.province": "Search province...",
        "trucks.placeholder.vin": "e.g. MMAT...",
        "trucks.placeholder.engineNumber": "e.g. 1KD-...",
        "trucks.placeholder.brand": "e.g. Isuzu, Hino",
        "trucks.placeholder.model": "e.g. NPR 150",
        "trucks.placeholder.selectYear": "Select Year",
        "trucks.placeholder.color": "e.g. White",
        "trucks.placeholder.selectType": "Select Truck Type",
        "trucks.placeholder.seats": "e.g. 2",
        "trucks.placeholder.cc": "e.g. 2999",
        "trucks.placeholder.fuelCapacity": "e.g. 100",
        "trucks.placeholder.weight": "e.g. 5000",
        "trucks.placeholder.adminName": "Name of responsible person",
        "trucks.placeholder.notes": "Additional notes...",
        "trucks.placeholder.policyNumber": "e.g. P-12345678",
        "trucks.placeholder.insurer": "e.g. Viriyah Insurance",
        "trucks.placeholder.premium": "e.g. 15000",
        "trucks.placeholder.coverage": "Coverage details...",

        "trucks.section.photos": "Truck Photos (Required)",
        "trucks.photos.frontRight": "Front-Right View",
        "trucks.photos.frontLeft": "Front-Left View",
        "trucks.photos.backRight": "Back-Right View",
        "trucks.photos.backLeft": "Back-Left View",

        "trucks.section.documents": "Truck Documents (Required)",
        "trucks.documents.tax": "Tax Document",
        "trucks.documents.register": "Truck Register Document",

        "trucks.upload.label": "Choose File",
        "trucks.upload.uploading": "Uploading...",
        "trucks.upload.chooseFile": "Choose File",
        "trucks.upload.noFileChosen": "No file chosen",
        "trucks.upload.acceptedFormats": "Accepted formats: JPG, PNG, PDF",
        "trucks.upload.success": "File uploaded successfully",
        "trucks.upload.error": "Failed to upload file",
        "trucks.upload.document": "Document",

        // Subcontractors
        "subcontractors.title": "Subcontractors",
        "subcontractors.subtitle": "Manage external truck providers",
        "subcontractors.add": "Register Subcontractor",
        "subcontractors.search": "Search name, contact...",
        "subcontractors.table.name": "Name",
        "subcontractors.table.type": "Type",
        "subcontractors.table.contact": "Contact",
        "subcontractors.table.phone": "Phone / Mobile",
        "subcontractors.table.status": "Status",
        "subcontractors.noData": "No subcontractors found",

        // User Management
        "users.title": "User Management",
        "users.subtitle": "Manage users and their permissions.",
        "users.sync": "Sync Database",
        "users.add": "Add User",
        "users.refresh": "Refresh List",
        "users.allUsers": "All Users",
        "users.allUsersDesc": "List of all registered users in the system.",
        "users.table.user": "User",
        "users.table.role": "Role",
        "users.table.providers": "Providers",
        "users.table.lastSignIn": "Last Sign In",
        "users.role.admin": "Admin",
        "users.role.partner": "Partner",
        "users.role.subcontractor": "Subcontractor",
        "users.role.customer": "Customer",
        "users.role.user": "User",
        "users.editRole": "Edit Role",
        "users.createTitle": "Create New User",
        "users.createDesc": "Add a new user to the system. Assign a specific role.",
        "users.form.displayName": "Display Name",
        "users.form.email": "Email",
        "users.form.password": "Password",
        "users.form.role": "Role",
        "users.form.cancel": "Cancel",
        "users.form.create": "Create User",
        "users.form.save": "Save Changes",

        // Waitlist Admin
        "waitlist.title": "Waitlist",
        "waitlist.description": "Manage users who requested access.",
        "waitlist.requests": "Waitlist Requests",
        "waitlist.requestsDesc": "List of emails waiting for an invitation.",
        "waitlist.noRequests": "No pending requests.",
        "waitlist.entryRemoved": "Entry removed",
        "waitlist.deleteFailed": "Failed to delete entry",
        "waitlist.fetchFailed": "Failed to fetch waitlist",
        "waitlist.confirmDelete": "Are you sure you want to remove this entry?",

        // Common
        "common.loading": "Loading...",
        "common.delete": "Delete",
        "common.refresh": "Refresh",
        "common.actions": "Actions",
        "common.joinedAt": "Joined At",
        "common.email": "Email",

        // Landing Page
        "landing.nav.solutions": "Solutions",
        "landing.nav.pricing": "Pricing",
        "landing.nav.about": "About Us",
        "landing.hero.tagline": "Global Logistics Management",
        "landing.hero.title": "Manage Your Supply Chain Professionally",
        "landing.hero.description": "The ultimate dashboard for real-time logistics management and global shipment tracking in one platform.",
        "landing.hero.stat.status": "Status",
        "landing.hero.stat.realtime": "Real-time",
        "landing.hero.stat.security": "Security",
        "landing.hero.stat.enterprise": "Enterprise",
        "landing.hero.login.title": "Admin Login",
        "landing.hero.login.subtitle": "Please sign in to manage your system",
        "auth.continueWithGoogle": "Continue with Google",
        "auth.sso": "Enterprise Login (SSO)",
        "auth.termsPrefix": "By signing in, you agree to our",
        "auth.terms": "Terms of Service",
        "auth.and": "and",
        "auth.privacy": "Privacy Policy",
        "landing.features.title": "Built for the Digital Logistics Age",
        "landing.features.description": "Our platform uses modern technology to provide unprecedented visibility and control over your global operations.",
        "landing.feature.tracking.title": "Real-time Tracking",
        "landing.feature.tracking.desc": "Monitor every shipment in real-time with high precision and live GPS updates.",
        "landing.feature.admin.title": "Admin Management",
        "landing.feature.admin.desc": "Comprehensive tools for fleet management, automated scheduling, and role-based access.",
        "landing.feature.language.title": "Multi-language Support",
        "landing.feature.language.desc": "Localized interfaces including Thai, enabling global partners to collaborate seamlessly.",
        "landing.cta.title": "Ready to optimize your operations?",
        "landing.cta.description": "Join thousands of logistics professionals who choose Logi-Track.",
        "landing.cta.requestDemo": "Request Demo",
        "landing.cta.viewApi": "View API Docs",
        "landing.footer.terms": "Terms of Use",
        "landing.footer.contact": "Contact Us",
        "landing.footer.systemOnline": "System Online",
        "landing.footer.rights": "All rights reserved.",
        "landing.footer.location": "United States",

        "landing.footer.global": "Global",


        // Truck Detail Page
        "trucks.detail.lastUpdated": "Last updated",
        "trucks.detail.maintenance": "Maintenance",
        "trucks.detail.editDetails": "Edit Details",
        "trucks.detail.vehicleSpecs": "Vehicle Specifications",
        "trucks.detail.brand": "Brand",
        "trucks.detail.model": "Model",
        "trucks.detail.year": "Year",
        "trucks.detail.fuelType": "Fuel Type",
        "trucks.detail.maxLoad": "Max Load",
        "trucks.detail.engineReg": "Engine & Registration",
        "trucks.detail.province": "License Plate Province",
        "trucks.detail.engineNo": "Engine Number",
        "trucks.detail.chassisNo": "Chassis Number",
        "trucks.detail.engineCap": "Engine Capacity",
        "trucks.detail.fuelCap": "Fuel Capacity",
        "trucks.detail.regDate": "Registration Date",
        "trucks.detail.buyingDate": "Buying Date",
        "trucks.detail.taxExpiry": "Tax (Act) Expiry",
        "trucks.detail.taxStatus": "Tax Renewal Status",
        "trucks.detail.insuranceDetails": "Insurance & Renewal Details",
        "trucks.detail.insuranceProvider": "Insurance Provider",
        "trucks.detail.policyNo": "Policy Number",
        "trucks.detail.insuranceType": "Type",
        "trucks.detail.premium": "Premium",
        "trucks.detail.startDate": "Start Date",
        "trucks.detail.endDate": "End Date",
        "trucks.detail.renewalStatus": "Renewal Status",
        "trucks.detail.ownershipInfo": "Ownership Info",
        "trucks.detail.subcontractorFleet": "Subcontractor Fleet",
        "trucks.detail.ownFleet": "Own Fleet",
        "trucks.detail.partner": "PARTNER",
        "trucks.detail.managedByPartner": "Managed by",
        "trucks.detail.managedByInternal": "Managed by Internal Logistics Team",
        "trucks.detail.viewPartner": "View Partner Profile",
        "trucks.detail.currentAssignment": "Current Assignment",
        "trucks.detail.assignedSince": "Assigned since",
        "trucks.detail.onDuty": "On Duty",
        "trucks.detail.action": "Action",
        "trucks.detail.active": "Active",
        "trucks.detail.viewProfile": "View Profile",
        "trucks.detail.manage": "Manage",
        "trucks.detail.manageAssignments": "Manage Assignments",
        "trucks.detail.noDriver": "No Driver Assigned",
        "trucks.detail.assignDriverDesc": "Assign a driver to this truck to track performance.",
        "trucks.detail.assignDriver": "Assign Driver",
        "trucks.detail.photos": "Vehicle Photos",
        "trucks.detail.photosCount": "PHOTOS",
        "trucks.detail.taxDoc": "TAX Document",
        "trucks.detail.viewTaxDoc": "View Tax Document",
        "trucks.detail.insuranceDoc": "Insurance Document",
        "trucks.detail.viewInsuranceDoc": "View Insurance Document",
        "trucks.detail.missingImage": "image or file for view",
        "trucks.detail.status.completed": "Completed",
        "trucks.detail.status.inProgress": "In Progress",
        "trucks.detail.status.pending": "Pending",
        "trucks.detail.status.available": "Available",
        "trucks.detail.status.inactive": "Inactive",
        "trucks.detail.status.maintenance": "Maintenance",
        "trucks.detail.status.insuranceClaim": "Insurance Claim",
        "trucks.detail.status.sold": "Sold",

        "trucks.detail.view.frontRight": "Front-Right View",
        "trucks.detail.view.frontLeft": "Front-Left View",
        "trucks.detail.view.backRight": "Back-Right View",
        "trucks.detail.view.backLeft": "Back-Left View",
        "trucks.detail.view.registrationDoc": "Registration Document",
        "trucks.detail.view.legacyImage": "Legacy Image",
        "trucks.detail.loading": "Loading truck data...",
        "trucks.detail.notFound": "Truck not found",
        "trucks.detail.noId": "No truck ID provided",
        "trucks.detail.error": "Failed to load truck data.",

        // Edit Truck
        "trucks.edit.title": "Edit Truck",
        "trucks.edit.subtitle": "Update truck information",
        "trucks.edit.backToDetails": "Back to Details",
        "trucks.edit.ownership": "Ownership",
        "trucks.edit.ownershipType": "Type",
        "trucks.edit.subcontractorRequired": "Subcontractor (Required)",
        "trucks.edit.selectSubcontractor": "Select a subcontractor",
        "trucks.edit.saveChanges": "Save Changes",
        "trucks.edit.saving": "Saving...",
        "trucks.edit.cancel": "Cancel",
        "trucks.edit.success": "Truck updated successfully",
        "trucks.edit.error": "Failed to update truck. Please try again.",

        // Truck Types
        "trucks.type.pickup": "Pickup",
        "trucks.type.4wheels": "4 Wheels",
        "trucks.type.6wheels": "6 Wheels",
        "trucks.type.10wheels": "10 Wheels",
        "trucks.type.18wheels": "18 Wheels",
        "trucks.type.van": "Van",

        // Fuel Types
        "trucks.fuel.diesel": "Diesel",
        "trucks.fuel.gasoline": "Gasoline",
        "trucks.fuel.ngv": "NGV",
        "trucks.fuel.electric": "Electric",
        "trucks.fuel.hybrid": "Hybrid",

        // Insurance Types
        "trucks.insurance.type.1": "Class 1",
        "trucks.insurance.type.2": "Class 2",
        "trucks.insurance.type.2_plus": "Class 2+",
        "trucks.insurance.type.3": "Class 3",
        "trucks.insurance.type.3_plus": "Class 3+",

        // Maintenance Section
        "trucks.maintenance.book": "Maintenance Book",
        "trucks.maintenance.lastDate": "Last Service Date",
        "trucks.maintenance.nextDate": "Next Service Date",
        "trucks.maintenance.nextMileage": "Next Service Mileage (km)",
        "trucks.maintenance.responsible": "Responsible Person (Service)",
        // Truck Assignments
        "assignments.title": "Manage Truck Assignments",
        "assignments.subtitle": "Pair drivers with vehicles and monitor active fleet deployments.",
        "assignments.viewMaps": "View Maps",
        "assignments.quickAction": "Quick Action",
        "assignments.totalTrucks": "Total Trucks",
        "assignments.availableDrivers": "Available Drivers",
        "assignments.activeAssignments": "Active Assignments",
        "assignments.new": "New Assignment",
        "assignments.selectDriver": "1. Select Available Driver",
        "assignments.searchDriver": "Search driver...",
        "assignments.searchDriverPlaceholder": "Search by name...",
        "assignments.noDrivers": "No available drivers found.",
        "assignments.noDriverSelected": "No driver selected",
        "assignments.selectTruck": "2. Select Available Truck",
        "assignments.searchTruck": "Search truck...",
        "assignments.searchTruckPlaceholder": "Search by plate or model...",
        "assignments.noTrucks": "No available trucks found.",
        "assignments.noTruckSelected": "No vehicle selected",
        "assignments.deploy": "Confirm and Deploy Assignment",
        "assignments.deploying": "Deploying...",
        "assignments.syncing": "Syncing live with Firebase database",
        "assignments.history": "Assignment History",
        "assignments.downloadCsv": "Download CSV",
        "assignments.table.timestamp": "Timestamp",
        "assignments.table.driver": "Driver",
        "assignments.table.vehicle": "Vehicle",
        "assignments.table.admin": "Admin",
        "assignments.table.status": "Status",
        "assignments.table.actions": "Actions",
        "assignments.table.loading": "Loading history...",
        "assignments.table.noHistory": "No recent assignments found.",
        "assignments.status.active": "Active",
        "assignments.status.revoked": "Revoked",
        "assignments.action.revoke": "Revoke Assignment",
        "assignments.revoke.title": "Confirm Revocation",
        "assignments.revoke.desc": "Are you sure you want to revoke this assignment?",
        "assignments.revoke.confirm": "Revoke Assignment",
        "assignments.revoke.revoking": "Revoking...",
        "assignments.revoke.cancel": "Cancel",
        "assignments.toast.selectBoth": "Please select both a driver and a truck",
        "assignments.toast.deploySuccess": "Assignment deployed successfully",
        "assignments.toast.deployError": "Failed to deploy assignment",
        "assignments.toast.revokeSuccess": "Assignment revoked successfully",
        "assignments.toast.revokeError": "Failed to revoke assignment",
        "assignments.toast.loadError": "Failed to load dashboard data",
    },
    th: {
        // Navigation
        "nav.home": "หน้าแรก",
        "nav.dashboard": "แดชบอร์ด",
        "nav.trucks": "รถบรรทุก",
        "nav.users": "ผู้ใช้งาน",
        "nav.drivers": "คนขับรถ",
        "nav.packages": "พัสดุ",
        "nav.analytics": "วิเคราะห์ข้อมูล",
        "nav.settings": "ตั้งค่า",
        "nav.login": "เข้าสู่ระบบ",
        "nav.register": "เข้าร่วมรายการรอ",
        "nav.logout": "ออกจากระบบ",
        "nav.myAccount": "บัญชีของฉัน",
        "nav.myFavorite": "รายการโปรด",
        "nav.adminDashboard": "แดชบอร์ดผู้ดูแล",
        "nav.propertyStockSearch": "ค้นหาคลังสินค้า",
        "nav.waitlist": "รายการรอ",
        "nav.platform": "แพลตฟอร์ม",

        "nav.subcontractors": "ผู้รับเหมาช่วง",

        // Home
        "home.welcome": "ยินดีต้อนรับสู่ Logi Track",

        // Auth
        "auth.login.title": "เข้าสู่ระบบ",
        "auth.login.subtitle": "กรอกอีเมลด้านล่างเพื่อเข้าสู่ระบบ",
        "auth.register.title": "เข้าร่วมรายการรอ",
        "auth.register.subtitle": "กรอกอีเมลเพื่อขอเข้าใช้งาน",
        "auth.email": "อีเมล",
        "auth.password": "รหัสผ่าน",
        "auth.confirmPassword": "ยืนยันรหัสผ่าน",
        "auth.forgotPassword": "ลืมรหัสผ่าน?",
        "auth.or": "หรือ",
        "auth.dontHaveAccount": "ต้องการขอทดสอบการใช้งานระบบ?",
        "auth.alreadyHaveAccount": "มีบัญชีอยู่แล้ว? เข้าสู่ระบบ",
        "auth.passwordsDoNotMatch": "รหัสผ่านไม่ตรงกัน",
        "auth.passwordMinLength": "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
        "auth.creatingAccount": "กำลังสร้างบัญชี...",
        "auth.signUp": "เข้าร่วมรายการรอ",
        "auth.signIn": "เข้าสู่ระบบด้วยอีเมล",
        "auth.waitlist.description": "การลงทะเบียนเฉพาะผู้ได้รับเชิญเท่านั้น เข้าร่วมรายการรอเพื่อขอสิทธิ์เข้าใช้งาน",
        "auth.waitlist.submit": "ขอสิทธิ์เข้าใช้งาน",
        "auth.signingIn": "กำลังเข้าสู่ระบบ...",
        "auth.waitlist.successTitle": "คุณอยู่ในรายการแล้ว!",
        "auth.waitlist.successDesc": "ขอบคุณที่สนใจ เราจะตรวจสอบข้อมูลของคุณและติดต่อกลับเมื่อบัญชีของคุณพร้อมใช้งาน",
        "auth.backToLogin": "กลับไปหน้าเข้าสู่ระบบ",
        "auth.emailRequired": "กรุณากรอกอีเมล",
        "auth.waitlist.successToast": "เข้าร่วมรายการรอสำเร็จ!",
        "auth.waitlist.errorToast": "ไม่สามารถเข้าร่วมรายการรอได้ กรุณาลองใหม่อีกครั้ง",

        // Admin Panel
        "admin.panel": "แผงควบคุมผู้ดูแล",

        // Dashboard
        "dashboard.title": "แดชบอร์ดผู้ดูแล",
        "dashboard.subtitle": "จัดการการดำเนินงานโลจิสติกส์ของคุณ",
        "dashboard.manageUsers": "จัดการผู้ใช้งาน",
        "dashboard.manageUsersDesc": "ดูและจัดการบัญชีผู้ใช้งาน",
        "dashboard.manageDrivers": "จัดการคนขับรถ",
        "dashboard.manageDriversDesc": "ดูและจัดการบัญชีคนขับรถ",
        "dashboard.managePackages": "จัดการพัสดุ",
        "dashboard.managePackagesDesc": "ดูและจัดการการจัดส่งพัสดุ",
        "dashboard.manageTrucks": "รถบรรทุก",
        "dashboard.manageTrucksDesc": "ดูและจัดการกองรถบรรทุก",
        "dashboard.analytics": "วิเคราะห์ข้อมูล",
        "dashboard.analyticsDesc": "ดูสถิติและรายงานการจัดส่ง",

        // Trucks
        "trucks.title": "รถบรรทุก",
        "trucks.subtitle": "จัดการกองรถบรรทุกของคุณ",
        "trucks.addTruck": "เพิ่มรถบรรทุก",
        "trucks.searchPlaceholder": "ค้นหารถบรรทุก...",
        "trucks.noTrucks": "ยังไม่มีรถบรรทุก",
        "trucks.getStarted": "เริ่มต้นด้วยการเพิ่มรถบรรทุกคันแรกของคุณ",
        "trucks.filter.own": "กองรถบริษัท",
        "trucks.filter.subcontractor": "รถร่วมบริการ",
        "trucks.filter.all": "รถทั้งหมด",

        "trucks.monitor": "ติดตามและจัดการรถบรรทุกที่ลงทะเบียนทั้งหมดในระบบ",
        "trucks.stats.tax": "ภาษีและทะเบียน",
        "trucks.stats.insurance": "สถานะประกันภัย",
        "trucks.stats.maintenance": "บริการซ่อมบำรุง",
        "trucks.stats.incoming": "กำลังมาถึง",
        "trucks.stats.less30Days": "น้อยกว่า 30 วัน",
        "trucks.stats.overdue": "เกินกำหนด",
        "trucks.stats.pmIncoming": "PM กำลังมาถึง",
        "trucks.stats.pmDueSoon": "PM ใกล้กำหนด",
        "trucks.stats.pmOverdue": "PM เกินกำหนด",
        "trucks.stats.owner": "ผู้รับผิดชอบ",
        "trucks.stats.opAdmin": "ฝ่ายปฏิบัติการ",
        "trucks.stats.assignedDriver": "คนขับที่ได้รับมอบหมาย",
        "trucks.filter.search": "ค้นหาด้วยทะเบียน, ID หรือรุ่น...",
        "trucks.filter.allTypes": "ทุกประเภท",
        "trucks.filter.allStatuses": "ทุกสถานะ",
        "trucks.filter.allGroups": "ทุกกลุ่ม",
        "trucks.filter.clear": "ล้างตัวกรอง",
        "trucks.table.id": "ID",
        "trucks.table.plate": "เลขทะเบียน",
        "trucks.table.model": "รุ่น",
        "trucks.table.driver": "คนขับปัจจุบัน",
        "trucks.table.ownership": "ความเป็นเจ้าของ",
        "trucks.table.taxInsu": "ภาษี/ประกัน",
        "trucks.table.pmStatus": "สถานะ PM",
        "trucks.table.status": "สถานะ",
        "trucks.export": "ส่งออก",
        "trucks.import": "นำเข้าข้อมูลรถ",

        "trucks.import.title": "นำเข้าข้อมูลรถบรรทุก",
        "trucks.import.desc": "อัปโหลดไฟล์ Excel หรือ CSV เพื่อนำเข้าข้อมูลรถบรรทุกจำนวนมาก",
        "trucks.import.downloadTemplate": "ดาวน์โหลดแบบฟอร์ม",
        "trucks.import.selectFile": "เลือกไฟล์",
        "trucks.import.parseError": "เกิดข้อผิดพลาดในการอ่านไฟล์ โปรดตรวจสอบรูปแบบไฟล์",
        "trucks.import.preview": "ตรวจสอบข้อมูล",
        "trucks.import.importing": "กำลังนำเข้า...",
        "trucks.import.success": "นำเข้าข้อมูลสำเร็จ {count} รายการ",
        "trucks.import.error": "เกิดข้อผิดพลาดในการนำเข้าข้อมูล",
        "trucks.import.validation.missing": "ข้อมูลไม่ครบถ้วน",
        "trucks.import.confirm": "ยืนยันการนำเข้า",

        "trucks.status.active": "ใช้งาน",
        "trucks.status.maintenance": "ซ่อมบำรุง",
        "trucks.status.inTransit": "กำลังขนส่ง",
        "trucks.status.inactive": "ไม่ใช้งาน",
        "trucks.badge.company": "บริษัท",
        "trucks.badge.partner": "พาร์ทเนอร์",
        "trucks.badge.taxInProcess": "ภาษี: กำลังดำเนินการ",
        "trucks.badge.taxOverdue": "ภาษี: เกินกำหนด",
        "trucks.badge.insuInProcess": "ประกัน: กำลังดำเนินการ",
        "trucks.badge.insuOverdue": "ประกัน: เกินกำหนด",
        "trucks.badge.pmInShop": "เข้าอู่",
        "trucks.badge.pmOverdue": "PM: เกินกำหนด",
        "trucks.action.view": "ดูรายละเอียด",
        "trucks.action.edit": "แก้ไขข้อมูลรถ",
        "trucks.action.renewTax": "ต่อภาษี",
        "trucks.action.renewInsu": "ต่อประกัน",
        "trucks.action.recordMain": "บันทึกการซ่อมบำรุง",

        // Truck Wizard
        "trucks.wizard.title": "แบบฟอร์มข้อมูลรถบรรทุก",
        "trucks.wizard.subtitle": "ขั้นตอนที่ {step} จาก {total}: กรุณากรอกข้อมูลรถด้านล่าง",
        "trucks.wizard.step1.title": "ข้อมูลรถ",
        "trucks.wizard.step1.desc": "ยี่ห้อ, รุ่น, VIN",
        "trucks.wizard.step2.title": "เอกสารกำกับ",
        "trucks.wizard.step2.desc": "ทะเบียนและประกันภัย",
        "trucks.wizard.step3.title": "การบำรุงรักษา",
        "trucks.wizard.step3.desc": "เครื่องยนต์และสถานะ",
        "trucks.wizard.step4.title": "ตรวจสอบ",
        "trucks.wizard.step4.desc": "ตรวจสอบและบันทึก",
        "trucks.wizard.tips": "เกร็ดความรู้",
        "trucks.wizard.tips.vin": "ตรวจสอบให้แน่ใจว่าเลข VIN ตรงกับเลขตัวถังรถเพื่อความถูกต้องในการจดทะเบียน",
        "trucks.wizard.back": "ย้อนกลับ",
        "trucks.wizard.cancel": "ยกเลิก",
        "trucks.wizard.next": "ถัดไป",
        "trucks.wizard.save": "บันทึกข้อมูล",
        "trucks.wizard.saving": "กำลังบันทึก...",

        "trucks.step1.title": "ขั้นตอนที่ 1: ข้อมูลจำเพาะของรถ",
        "trucks.step1.appearance": "รูปพรรณของรถ",

        "trucks.step2.title": "ขั้นตอนที่ 2: ข้อมูลทางกฎหมาย",
        "trucks.step2.desc": "กรอกข้อมูลทะเบียนและประกันภัย",
        "trucks.step2.subOptions": "รายละเอียดการจดทะเบียนเป็นทางเลือกสำหรับรถร่วมบริการ",
        "trucks.step2.insurance": "ข้อมูลประกันภัย",

        "trucks.step3.title": "ขั้นตอนที่ 3: ข้อมูลเครื่องยนต์",
        "trucks.step3.desc": "รายละเอียดเกี่ยวกับเครื่องยนต์และความจุ",
        "trucks.step3.subOptions": "ข้อมูลเครื่องยนต์โดยละเอียดเป็นทางเลือกสำหรับรถร่วมบริการ",
        "trucks.step3.maintenanceBook": "สมุดบันทึกการซ่อมบำรุง",
        "trucks.step3.lastServiceDate": "วันที่ซ่อมบำรุงล่าสุด",
        "trucks.step3.nextServiceDate": "วันที่ซ่อมบำรุงถัดไป",
        "trucks.step3.nextServiceMileage": "ระยะทางซ่อมบำรุงถัดไป (กม.)",

        "trucks.step4.title": "ขั้นตอนที่ 4: ตรวจสอบและยืนยัน",
        "trucks.step4.desc": "กรุณาตรวจสอบข้อมูลทั้งหมดก่อนเพิ่มรถเข้าสู่ระบบ",
        "trucks.step4.specs": "ข้อมูลจำเพาะรถ",
        "trucks.step4.compliance": "เอกสารกำกับ",
        "trucks.step4.insurance": "ประกันภัย",
        "trucks.step4.ready": "พร้อมส่งข้อมูล",
        "trucks.step4.readyDesc": "เมื่อคลิก \"บันทึกข้อมูล\" รถคันนี้จะถูกเพิ่มเข้าสู่ทะเบียนรถที่ใช้งานอยู่",
        "trucks.step4.makeModel": "ยี่ห้อ/รุ่น",
        "trucks.step4.plate": "ทะเบียน",
        "trucks.step4.vin": "VIN",
        "trucks.step4.type": "ประเภท",
        "trucks.step4.province": "จังหวัด",
        "trucks.step4.taxDoc": "เอกสารภาษี",
        "trucks.step4.regDoc": "เอกสารทะเบียน",
        "trucks.step4.uploaded": "อัปโหลดแล้ว",
        "trucks.step4.pending": "รออัปโหลด",
        "trucks.step4.provider": "ผู้ให้บริการ",
        "trucks.step4.policy": "เลขกรมธรรม์",
        "trucks.step4.expiry": "หมดอายุ",

        // Truck Wizard Sections
        "trucks.section.identification": "ข้อมูลระบุตัวตน",
        "trucks.section.licensePlate": "เลขทะเบียน",
        "trucks.section.province": "จังหวัด",
        "trucks.section.vin": "เลขตัวถัง (VIN)",
        "trucks.section.engineNumber": "เลขเครื่องยนต์",
        "trucks.section.truckStatus": "สถานะรถ",

        "trucks.section.details": "รายละเอียด",
        "trucks.section.brand": "ยี่ห้อ",
        "trucks.section.model": "รุ่น",
        "trucks.section.year": "ปี",
        "trucks.section.color": "สี",
        "trucks.section.truckType": "ประเภทรถ",
        "trucks.section.seats": "จำนวนที่นั่ง",

        "trucks.section.registration": "ข้อมูลการจดทะเบียน",
        "trucks.section.taxExpiry": "วันหมดอายุภาษี (พ.ร.บ.)",
        "trucks.section.regDate": "วันที่จดทะเบียน",
        "trucks.section.buyingDate": "วันที่ซื้อ",
        "trucks.section.responsible": "ผู้รับผิดชอบ (ภาษี)",
        "trucks.section.notes": "หมายเหตุ",

        "trucks.section.insuranceInfo": "ข้อมูลประกันภัย",
        "trucks.section.policyId": "รหัสกรมธรรม์ (ภายใน)",
        "trucks.section.policyNo": "เลขที่กรมธรรม์",
        "trucks.section.provider": "บริษัทประกัน",
        "trucks.section.coverageType": "ประเภทความคุ้มครอง",
        "trucks.section.selectType": "เลือกประเภท",
        "trucks.section.premium": "เบี้ยประกัน (บาท)",
        "trucks.section.startDate": "วันเริ่มคุ้มครอง",
        "trucks.section.endDate": "วันสิ้นสุดคุ้มครอง",
        "trucks.section.insuranceDocs": "เอกสารประกันภัย",
        "trucks.section.upload": "อัปโหลด PDF/รูปภาพ",

        "trucks.section.engineInfo": "ข้อมูลเครื่องยนต์",
        "trucks.section.fuelType": "เชื้อเพลิง",
        "trucks.section.selectFuel": "เลือกเชื้อเพลิง",
        "trucks.section.engineCap": "ความจุเครื่องยนต์ (cc/kW)",
        "trucks.section.fuelCap": "ความจุถังน้ำมัน (ลิตร/kWh)",
        "trucks.section.maxLoad": "น้ำหนักบรรทุกสูงสุด",

        // Placeholders
        "trucks.placeholder.licensePlate": "เช่น 1กก-1234",
        "trucks.placeholder.province": "ค้นหาจังหวัด...",
        "trucks.placeholder.vin": "เช่น MMAT...",
        "trucks.placeholder.engineNumber": "เช่น 1KD-...",
        "trucks.placeholder.brand": "เช่น Isuzu, Hino",
        "trucks.placeholder.model": "เช่น NPR 150",
        "trucks.placeholder.selectYear": "เลือกปี",
        "trucks.placeholder.color": "เช่น สีขาว",
        "trucks.placeholder.selectType": "เลือกประเภทรถ",
        "trucks.placeholder.seats": "เช่น 2",
        "trucks.placeholder.cc": "เช่น 2999",
        "trucks.placeholder.fuelCapacity": "เช่น 100",
        "trucks.placeholder.weight": "เช่น 5000",
        "trucks.placeholder.adminName": "ชื่อผู้รับผิดชอบ",
        "trucks.placeholder.notes": "หมายเหตุเพิ่มเติม...",
        "trucks.placeholder.policyNumber": "เช่น P-12345678",
        "trucks.placeholder.insurer": "เช่น วิริยะประกันภัย",
        "trucks.placeholder.premium": "เช่น 15000",
        "trucks.placeholder.coverage": "รายละเอียดความคุ้มครอง...",

        "trucks.section.photos": "รูปรถบรรทุก (จำเป็น)",
        "trucks.photos.frontRight": "ด้านหน้า-ขวา",
        "trucks.photos.frontLeft": "ด้านหน้า-ซ้าย",
        "trucks.photos.backRight": "ด้านหลัง-ขวา",
        "trucks.photos.backLeft": "ด้านหลัง-ซ้าย",

        "trucks.section.documents": "เอกสารรถบรรทุก (จำเป็น)",
        "trucks.documents.tax": "เอกสารภาษี",
        "trucks.documents.register": "เล่มทะเบียนรถ",

        "trucks.upload.label": "เลือกไฟล์",
        "trucks.upload.uploading": "กำลังอัปโหลด...",
        "trucks.upload.chooseFile": "เลือกไฟล์",
        "trucks.upload.noFileChosen": "ไม่ได้เลือกไฟล์",
        "trucks.upload.acceptedFormats": "รูปแบบไฟล์ที่รองรับ: JPG, PNG, PDF",
        "trucks.upload.success": "อัปโหลดไฟล์สำเร็จ",
        "trucks.upload.error": "อัปโหลดไฟล์ไม่สำเร็จ",
        "trucks.upload.document": "เอกสาร",

        // Subcontractors
        "subcontractors.title": "ผู้รับเหมาช่วง",
        "subcontractors.subtitle": "จัดการผู้ให้บริการขนส่งภายนอก",
        "subcontractors.add": "ลงทะเบียนผู้รับเหมา",
        "subcontractors.search": "ค้นหาชื่อ, ผู้ติดต่อ...",
        "subcontractors.table.name": "ชื่อ",
        "subcontractors.table.type": "ประเภท",
        "subcontractors.table.contact": "ผู้ติดต่อ",
        "subcontractors.table.phone": "โทรศัพท์",
        "subcontractors.table.status": "สถานะ",
        "subcontractors.noData": "ไม่พบข้อมูลผู้รับเหมา",

        // User Management
        "users.title": "จัดการผู้ใช้งาน",
        "users.subtitle": "จัดการผู้ใช้และสิทธิ์การใช้งาน",
        "users.sync": "ซิงค์ฐานข้อมูล",
        "users.add": "เพิ่มผู้ใช้งาน",
        "users.refresh": "รีเฟรชรายการ",
        "users.allUsers": "ผู้ใช้งานทั้งหมด",
        "users.allUsersDesc": "รายชื่อผู้ใช้งานที่ลงทะเบียนทั้งหมดในระบบ",
        "users.table.user": "ผู้ใช้งาน",
        "users.table.role": "บทบาท",
        "users.table.providers": "ผู้ให้บริการ",
        "users.table.lastSignIn": "เข้าสู่ระบบล่าสุด",
        "users.role.admin": "ผู้ดูแลระบบ",
        "users.role.partner": "พาร์ทเนอร์",
        "users.role.subcontractor": "ผู้รับเหมาช่วง",
        "users.role.customer": "ลูกค้า",
        "users.role.user": "ผู้ใช้ทั่วไป",
        "users.editRole": "แก้ไขบทบาท",
        "users.createTitle": "สร้างผู้ใช้งานใหม่",
        "users.createDesc": "เพิ่มผู้ใช้งานใหม่เข้าสู่ระบบ กำหนดบทบาทเฉพาะ",
        "users.form.displayName": "ชื่อที่แสดง",
        "users.form.email": "อีเมล",
        "users.form.password": "รหัสผ่าน",
        "users.form.role": "บทบาท",
        "users.form.cancel": "ยกเลิก",
        "users.form.create": "สร้างผู้ใช้งาน",
        "users.form.save": "บันทึกการเปลี่ยนแปลง",

        // Waitlist Admin
        "waitlist.title": "รายการรอ",
        "waitlist.description": "จัดการผู้ใช้ที่ขอสิทธิ์เข้าใช้งาน",
        "waitlist.requests": "คำขอรายการรอ",
        "waitlist.requestsDesc": "รายชื่ออีเมลที่รอการเชิญ",
        "waitlist.noRequests": "ไม่มีคำขอที่รอดำเนินการ",
        "waitlist.entryRemoved": "ลบรายการแล้ว",
        "waitlist.deleteFailed": "ลบรายการไม่สำเร็จ",
        "waitlist.fetchFailed": "ดึงข้อมูลรายการรอไม่สำเร็จ",
        "waitlist.confirmDelete": "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?",

        // Common
        "common.loading": "กำลังโหลด...",
        "common.delete": "ลบ",
        "common.refresh": "รีเฟรช",
        "common.actions": "การกระทำ",
        "common.joinedAt": "วันที่เข้าร่วม",
        "common.email": "อีเมล",

        // Landing Page
        "landing.nav.solutions": "โซลูชั่น",
        "landing.nav.pricing": "ราคา",
        "landing.nav.about": "เกี่ยวกับเรา",
        "landing.hero.tagline": "การจัดการโลจิสติกส์ระดับโลก",
        "landing.hero.title": "จัดการห่วงโซ่อุปทานของคุณอย่างมืออาชีพ",
        "landing.hero.description": "แดชบอร์ดที่ดีที่สุดสำหรับการจัดการโลจิสติกส์แบบเรียลไทม์และการติดตามการจัดส่งทั่วโลกในแพลตฟอร์มเดียว",
        "landing.hero.stat.status": "สถานะ",
        "landing.hero.stat.realtime": "เรียลไทม์",
        "landing.hero.stat.security": "ความปลอดภัย",
        "landing.hero.stat.enterprise": "องค์กร",
        "landing.hero.login.title": "เข้าสู่ระบบผู้ดูแล",
        "landing.hero.login.subtitle": "กรุณาเข้าสู่ระบบเพื่อจัดการระบบของคุณ",
        "auth.continueWithGoogle": "ดำเนินการต่อด้วย Google",
        "auth.sso": "เข้าสู่ระบบองค์กร (SSO)",
        "auth.termsPrefix": "การเข้าสู่ระบบถือว่าคุณยอมรับ",
        "auth.terms": "เงื่อนไขการให้บริการ",
        "auth.and": "และ",
        "auth.privacy": "นโยบายความเป็นส่วนตัว",
        "landing.features.title": "สร้างขึ้นเพื่อยุคโลจิสติกส์ดิจิทัล",
        "landing.features.description": "แพลตฟอร์มของเราใช้เทคโนโลยีที่ทันสมัยเพื่อให้การมองเห็นและการควบคุมการดำเนินงานทั่วโลกของคุณอย่างที่ไม่เคยมีมาก่อน",
        "landing.feature.tracking.title": "การติดตามแบบเรียลไทม์",
        "landing.feature.tracking.desc": "ติดตามการจัดส่งทุกรายการแบบเรียลไทม์ด้วยความแม่นยำสูงและการอัปเดต GPS สด",
        "landing.feature.admin.title": "การจัดการผู้ดูแล",
        "landing.feature.admin.desc": "เครื่องมือครบวงจรสำหรับการจัดการกองเรือ การจัดตารางอัตโนมัติ และการเข้าถึงตามบทบาท",
        "landing.feature.language.title": "รองรับหลายภาษา",
        "landing.feature.language.desc": "อินเทอร์เฟซที่แปลเป็นภาษาท้องถิ่นรวมถึงภาษาไทย ช่วยให้พันธมิตรทั่วโลกทำงานร่วมกันได้อย่างราบรื่น",
        "landing.cta.title": "พร้อมที่จะเพิ่มประสิทธิภาพการดำเนินงานของคุณหรือยัง?",
        "landing.cta.description": "เข้าร่วมกับผู้เชี่ยวชาญด้านโลจิสติกส์นับพันที่เลือก Logi-Track",
        "landing.cta.requestDemo": "ขอสาธิตการใช้งาน",
        "landing.cta.viewApi": "ดูเอกสาร API",
        "landing.footer.terms": "เงื่อนไขการใช้งาน",
        "landing.footer.contact": "ติดต่อเรา",
        "landing.footer.systemOnline": "ระบบออนไลน์",
        "landing.footer.rights": "สงวนลิขสิทธิ์",
        "landing.footer.location": "สหรัฐอเมริกา",
        "nav.fleets": "กองรถ",
        "nav.truckManagement": "จัดการรถบรรทุก",
        "nav.truckAssignment": "มอบหมายงานรถ",
        "nav.truckRenewals": "การต่อภาษี/พรบ./ประกันภัย",
        "nav.maintenanceCosts": "ค่าใช้จ่ายซ่อมบำรุง",
        "nav.manageSubcontractors": "จัดการผู้รับเหมาช่วง",
        "nav.driverManagement": "จัดการคนขับรถ",
        "nav.activeShipments": "การจัดส่งที่ดำเนินการอยู่",
        "nav.userRoles": "บทบาทผู้ใช้งาน",
        "nav.reporting": "รายงานผล",
        "nav.operations": "ปฏิบัติการ",
        "nav.firstMileTasks": "งาน First Mile",
        "nav.sourceManagement": "จัดการต้นทาง",
        "nav.supportCenter": "ศูนย์ช่วยเหลือ",

        "landing.footer.global": "ทั่วโลก",

        // Truck Detail Page
        "trucks.detail.lastUpdated": "อัปเดตล่าสุด",
        "trucks.detail.maintenance": "ซ่อมบำรุง",
        "trucks.detail.editDetails": "แก้ไขข้อมูล",
        "trucks.detail.vehicleSpecs": "ข้อมูลจำเพาะรถ",
        "trucks.detail.brand": "ยี่ห้อ",
        "trucks.detail.model": "รุ่น",
        "trucks.detail.year": "ปี",
        "trucks.detail.fuelType": "เชื้อเพลิง",
        "trucks.detail.maxLoad": "น้ำหนักบรรทุกสูงสุด",
        "trucks.detail.engineReg": "เครื่องยนต์และทะเบียน",
        "trucks.detail.province": "จังหวัดป้ายทะเบียน",
        "trucks.detail.engineNo": "เลขเครื่องยนต์",
        "trucks.detail.chassisNo": "เลขตัวถัง (Chassis)",
        "trucks.detail.engineCap": "ความจุเครื่องยนต์",
        "trucks.detail.fuelCap": "ความจุถังน้ำมัน",
        "trucks.detail.regDate": "วันที่จดทะเบียน",
        "trucks.detail.buyingDate": "วันที่ซื้อ",
        "trucks.detail.taxExpiry": "วันหมดอายุภาษี",
        "trucks.detail.taxStatus": "สถานะต่อภาษี",
        "trucks.detail.insuranceDetails": "ข้อมูลประกันและการต่ออายุ",
        "trucks.detail.insuranceProvider": "บริษัทผู้รับประกัน",
        "trucks.detail.policyNo": "เลขกรมธรรม์",
        "trucks.detail.insuranceType": "ประเภท",
        "trucks.detail.premium": "เบี้ยประกัน",
        "trucks.detail.startDate": "วันเริ่มคุ้มครอง",
        "trucks.detail.endDate": "วันสิ้นสุดคุ้มครอง",
        "trucks.detail.renewalStatus": "สถานะการต่ออายุ",
        "trucks.detail.ownershipInfo": "ข้อมูลเจ้าของ",
        "trucks.detail.subcontractorFleet": "รถร่วมบริการ",
        "trucks.detail.ownFleet": "กองรถบริษัท",
        "trucks.detail.partner": "พาร์ทเนอร์",
        "trucks.detail.managedByPartner": "บริหารจัดการโดย",
        "trucks.detail.managedByInternal": "บริหารจัดการโดยทีมโลจิสติกส์ภายใน",
        "trucks.detail.viewPartner": "ดูโปรไฟล์พาร์ทเนอร์",
        "trucks.detail.currentAssignment": "งานที่ได้รับมอบหมายปัจจุบัน",
        "trucks.detail.assignedSince": "มอบหมายเมื่อ",
        "trucks.detail.onDuty": "ปฏิบัติงาน",
        "trucks.detail.action": "สถานะ",
        "trucks.detail.active": "กำลังใช้งาน",
        "trucks.detail.viewProfile": "ดูโปรไฟล์",
        "trucks.detail.manage": "จัดการ",
        "trucks.detail.manageAssignments": "จัดการการมอบหมาย",
        "trucks.detail.noDriver": "ยังไม่มีคนขับ",
        "trucks.detail.assignDriverDesc": "มอบหมายคนขับให้กับรถคันนี้เพื่อติดตามประสิทธิภาพ",
        "trucks.detail.assignDriver": "ระบุคนขับ",
        "trucks.detail.photos": "รูปรถ",
        "trucks.detail.photosCount": "รูปภาพ",
        "trucks.detail.taxDoc": "เอกสารภาษี",
        "trucks.detail.viewTaxDoc": "ดูเอกสารภาษี",
        "trucks.detail.insuranceDoc": "เอกสารประกันภัย",
        "trucks.detail.viewInsuranceDoc": "ดูเอกสารประกันภัย",
        "trucks.detail.missingImage": "รูปภาพหรือไฟล์สำหรับดู",
        "trucks.detail.status.completed": "เรียบร้อย",
        "trucks.detail.status.inProgress": "กำลังดำเนินการ",
        "trucks.detail.status.pending": "รอดำเนินการ",
        "trucks.detail.status.available": "ว่าง",
        "trucks.detail.status.inactive": "ไม่ใช้งาน",
        "trucks.detail.status.maintenance": "ซ่อมบำรุง",
        "trucks.detail.status.insuranceClaim": "เคลมประกัน",
        "trucks.detail.status.sold": "ขายแล้ว",

        "trucks.detail.view.frontRight": "มุมหน้าขวา",
        "trucks.detail.view.frontLeft": "มุมหน้าซ้าย",
        "trucks.detail.view.backRight": "มุมหลังขวา",
        "trucks.detail.view.backLeft": "มุมหลังซ้าย",
        "trucks.detail.view.registrationDoc": "เอกสารจดทะเบียน",
        "trucks.detail.view.legacyImage": "รูปภาพเดิม",
        "trucks.detail.loading": "กำลังโหลดข้อมูลรถ...",
        "trucks.detail.notFound": "ไม่พบข้อมูลรถ",
        "trucks.detail.noId": "ไม่พบรหัสรถ",
        "trucks.detail.error": "โหลดข้อมูลรถล้มเหลว",

        // Edit Truck
        "trucks.edit.title": "แก้ไขข้อมูลรถ",
        "trucks.edit.subtitle": "อัปเดตข้อมูลรถบรรทุก",
        "trucks.edit.backToDetails": "กลับไปหน้ารายละเอียด",
        "trucks.edit.ownership": "ความเป็นเจ้าของ",
        "trucks.edit.ownershipType": "ประเภท",
        "trucks.edit.subcontractorRequired": "ผู้รับเหมาช่วง (จำเป็น)",
        "trucks.edit.selectSubcontractor": "เลือกผู้รับเหมาช่วง",
        "trucks.edit.saveChanges": "บันทึกการเปลี่ยนแปลง",
        "trucks.edit.saving": "กำลังบันทึก...",
        "trucks.edit.cancel": "ยกเลิก",
        "trucks.edit.success": "อัปเดตข้อมูลรถสำเร็จ",
        "trucks.edit.error": "อัปเดตข้อมูลรถล้มเหลว โปรดลองอีกครั้ง",

        // Truck Types
        "trucks.type.pickup": "รถกระบะ",
        "trucks.type.4wheels": "4 ล้อ",
        "trucks.type.6wheels": "6 ล้อ",
        "trucks.type.10wheels": "10 ล้อ",
        "trucks.type.18wheels": "18 ล้อ",
        "trucks.type.van": "รถตู้",

        // Fuel Types
        "trucks.fuel.diesel": "ดีเซล",
        "trucks.fuel.gasoline": "เบนซิน",
        "trucks.fuel.ngv": "NGV",
        "trucks.fuel.electric": "ไฟฟ้า",
        "trucks.fuel.hybrid": "ไฮบริด",

        // Insurance Types
        "trucks.insurance.type.1": "ประกันชั้น 1",
        "trucks.insurance.type.2": "ประกันชั้น 2",
        "trucks.insurance.type.2_plus": "ประกันชั้น 2+",
        "trucks.insurance.type.3": "ประกันชั้น 3",
        "trucks.insurance.type.3_plus": "ประกันชั้น 3+",

        // Maintenance Section
        "trucks.maintenance.book": "สมุดบันทึกการซ่อมบำรุง",
        "trucks.maintenance.lastDate": "วันที่เข้าศูนย์ล่าสุด",
        "trucks.maintenance.nextDate": "วันที่นัดเข้าศูนย์ถัดไป",
        "trucks.maintenance.nextMileage": "ระยะทางที่ต้องเข้าศูนย์ถัดไป (กม.)",
        "trucks.maintenance.responsible": "ผู้รับผิดชอบ (ซ่อมบำรุง)",
        "nav.mainMenu": "เมนูหลัก",
        "nav.system": "ระบบ",
        // Truck Assignments
        "assignments.title": "จัดการการมอบหมายงานรถ",
        "assignments.subtitle": "จับคู่คนขับกับรถและติดตามการใช้งานรถ",
        "assignments.viewMaps": "ดูแผนที่",
        "assignments.quickAction": "การดำเนินการด่วน",
        "assignments.totalTrucks": "รถทั้งหมด",
        "assignments.availableDrivers": "คนขับที่ว่าง",
        "assignments.activeAssignments": "งานที่มอบหมายปัจจุบัน",
        "assignments.new": "มอบหมายงานใหม่",
        "assignments.selectDriver": "1. เลือกคนขับที่ว่าง",
        "assignments.searchDriver": "ค้นหาคนขับ...",
        "assignments.searchDriverPlaceholder": "ค้นหาด้วยชื่อ...",
        "assignments.noDrivers": "ไม่พบคนขับที่ว่าง",
        "assignments.noDriverSelected": "ไม่ได้เลือกคนขับ",
        "assignments.selectTruck": "2. เลือกรถที่ว่าง",
        "assignments.searchTruck": "ค้นหารถ...",
        "assignments.searchTruckPlaceholder": "ค้นหาด้วยทะเบียนหรือรุ่น...",
        "assignments.noTrucks": "ไม่พบรถที่ว่าง",
        "assignments.noTruckSelected": "ไม่ได้เลือกรถ",
        "assignments.deploy": "ยืนยันและมอบหมายงาน",
        "assignments.deploying": "กำลังมอบหมาย...",
        "assignments.syncing": "ซิงค์ข้อมูลกับ Firebase แบบเรียลไทม์",
        "assignments.history": "ประวัติการมอบหมายงาน",
        "assignments.downloadCsv": "ดาวน์โหลด CSV",
        "assignments.table.timestamp": "เวลา",
        "assignments.table.driver": "คนขับ",
        "assignments.table.vehicle": "รถ",
        "assignments.table.admin": "ผู้ดูแล",
        "assignments.table.status": "สถานะ",
        "assignments.table.actions": "การกระทำ",
        "assignments.table.loading": "กำลังโหลดประวัติ...",
        "assignments.table.noHistory": "ไม่พบประวัติการมอบหมายงานล่าสุด",
        "assignments.status.active": "ใช้งาน",
        "assignments.status.revoked": "ยกเลิกแล้ว",
        "assignments.action.revoke": "ยกเลิกการมอบหมาย",
        "assignments.revoke.title": "ยืนยันการยกเลิก",
        "assignments.revoke.desc": "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการมอบหมายนี้?",
        "assignments.revoke.confirm": "ยกเลิกการมอบหมาย",
        "assignments.revoke.revoking": "กำลังยกเลิก...",
        "assignments.revoke.cancel": "ยกเลิก",
        "assignments.toast.selectBoth": "กรุณาเลือกทั้งคนขับและรถ",
        "assignments.toast.deploySuccess": "มอบหมายงานสำเร็จ",
        "assignments.toast.deployError": "มอบหมายงานล้มเหลว",
        "assignments.toast.revokeSuccess": "ยกเลิกการมอบหมายสำเร็จ",
        "assignments.toast.revokeError": "ยกเลิกการมอบหมายล้มเหลว",
        "assignments.toast.loadError": "โหลดข้อมูลแดชบอร์ดล้มเหลว",
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("language") as Language;
        if (savedLanguage) {
            setLanguage(savedLanguage);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations["en"]] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
