// Command tsgen writes the capability catalog of internal/authz as TypeScript for the web
// (shared-docs/schemas/capabilities.ts, R27): the 81 keys with module, class and titles, the default
// role matrix, the steward keys and ROUTE_CAPABILITIES of the edge gate. go generate ./internal/authz
// runs it; make gen-check fails when the committed file is stale. The web never edits the file.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"github.com/smartcode54-bit/logi-track-plateform/logitrack-api/internal/authz"
)

func main() {
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()
	b, err := render()
	if err == nil {
		if *out == "" {
			_, err = os.Stdout.Write(b)
		} else {
			err = os.WriteFile(*out, b, 0o644)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "tsgen:", err)
		os.Exit(1)
	}
}

func js(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(b)
}

func render() ([]byte, error) {
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	p("// Code generated by logitrack-api/internal/authz/tsgen (go generate ./internal/authz). DO NOT EDIT.\n")
	p("// Source: logitrack-api/internal/authz (Appendix C §C.2.3 catalog, §C.2.4 defaults, §C.2.7 routes).\n\n")
	p("export type CapabilityClass = \"tenant\" | \"global\" | \"self\" | \"scope\" | \"platform\";\n\n")

	cat := authz.Catalog()
	p("/** The %d capability keys (77 + 4 platform, R73), colon form. */\n", len(cat))
	p("export const CAPABILITY_KEYS = [\n")
	for _, e := range cat {
		p("  %s,\n", js(e.Key))
	}
	p("] as const;\n\n")
	p("export type CapabilityKey = (typeof CAPABILITY_KEYS)[number];\n\n")

	p("export interface CapabilityInfo {\n  key: CapabilityKey;\n  module: string;\n  class: CapabilityClass;\n  titleEn: string;\n  titleTh: string;\n}\n\n")
	p("/** Catalog metadata (also served by GET /v1/roles). */\n")
	p("export const CAPABILITY_CATALOG: readonly CapabilityInfo[] = [\n")
	for _, e := range cat {
		p("  { key: %s, module: %s, class: %s, titleEn: %s, titleTh: %s },\n",
			js(e.Key), js(e.Module), js(e.Class), js(e.TitleEn), js(e.TitleTh))
	}
	p("];\n\n")

	p("export type RoleAxis = \"tenant\" | \"scope\" | \"platform\";\n\n")
	p("/** Default sets before overrides and the steward rule (Appendix C §C.2.4). */\n")
	p("export const ROLE_DEFAULT_CAPABILITIES: readonly { role: string; axis: RoleAxis; capabilities: readonly CapabilityKey[] }[] = [\n")
	for _, r := range authz.DefaultMatrix() {
		p("  { role: %s, axis: %s, capabilities: %s },\n", js(r.Role), js(r.Axis), js(r.Capabilities))
	}
	p("];\n\n")

	p("/** Global keys: effective only for own-fleet staff and platform_admin (R60). */\n")
	p("export const STEWARD_CAPABILITIES: readonly CapabilityKey[] = %s;\n\n", js(authz.GlobalCaps()))

	routes := authz.WebRoutes()
	p("/**\n * The web edge gate (proxy.ts, R39): exact path, else the longest mapped prefix; an unmapped path is\n")
	p(" * denied; an empty list admits every signed-in principal; otherwise any-of. Go authorises every\n * request again.\n */\n")
	p("export const ROUTE_CAPABILITIES: Readonly<Record<string, readonly CapabilityKey[]>> = {\n")
	for _, path := range authz.WebRoutePaths() {
		caps := routes[path]
		if caps == nil {
			caps = []authz.Cap{}
		}
		p("  %s: %s,\n", js(path), js(caps))
	}
	p("};\n")
	return b.Bytes(), nil
}
