// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCm7dBuw7x_GVVSmzZhRWdKJ3jL_J4pxA',
    appId: '1:841355267296:web:6bdb2b5292889fa7f25485',
    messagingSenderId: '841355267296',
    projectId: 'logi-track-wrt-dev',
    authDomain: 'logi-track-wrt-dev.firebaseapp.com',
    storageBucket: 'logi-track-wrt-dev.firebasestorage.app',
    measurementId: 'G-224HJTVS7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCm7dBuw7x_GVVSmzZhRWdKJ3jL_J4pxA',
    appId:
        '1:841355267296:web:6bdb2b5292889fa7f25485', // Using web app ID for now as placeholder or hybrid
    messagingSenderId: '841355267296',
    projectId: 'logi-track-wrt-dev',
    storageBucket: 'logi-track-wrt-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCm7dBuw7x_GVVSmzZhRWdKJ3jL_J4pxA',
    appId:
        '1:841355267296:web:6bdb2b5292889fa7f25485', // Using web app ID for now as placeholder or hybrid
    messagingSenderId: '841355267296',
    projectId: 'logi-track-wrt-dev',
    storageBucket: 'logi-track-wrt-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCm7dBuw7x_GVVSmzZhRWdKJ3jL_J4pxA',
    appId:
        '1:841355267296:web:6bdb2b5292889fa7f25485', // Using web app ID for now as placeholder or hybrid
    messagingSenderId: '841355267296',
    projectId: 'logi-track-wrt-dev',
    storageBucket: 'logi-track-wrt-dev.firebasestorage.app',
  );
}
