// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package notifydb

import (
	"context"

	"github.com/google/uuid"
)

const getRecipient = `-- name: GetRecipient :one
SELECT id, coalesce(email::text, '')::text AS email, display_name, status FROM users WHERE id = $1
`

type GetRecipientRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName *string
	Status      string
}

// notify.email reads the address server-side: recipients are never taken from a message (main spec §7.6).
func (q *Queries) GetRecipient(ctx context.Context, id uuid.UUID) (GetRecipientRow, error) {
	row := q.db.QueryRow(ctx, getRecipient, id)
	var i GetRecipientRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
	)
	return i, err
}
