// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fcm.sql

package notifydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteInvalidToken = `-- name: DeleteInvalidToken :execrows
DELETE FROM device_tokens WHERE user_id = $1 AND install_id = $2 AND token = $3
`

type DeleteInvalidTokenParams struct {
	UserID    uuid.UUID
	InstallID string
	Token     string
}

// FCM said UNREGISTERED (or INVALID_ARGUMENT naming the token): the row goes, unless the device has
// registered another token since.
func (q *Queries) DeleteInvalidToken(ctx context.Context, arg DeleteInvalidTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvalidToken, arg.UserID, arg.InstallID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const driverDevices = `-- name: DriverDevices :many
SELECT d.id AS driver_id, coalesce(d.legacy_doc_id, d.id::text)::text AS driver_ref,
       dt.user_id, dt.install_id, dt.token
FROM drivers d
JOIN device_tokens dt ON dt.user_id = d.user_id
WHERE d.id = ANY ($1::uuid[])
ORDER BY d.id, dt.install_id
`

type DriverDevicesRow struct {
	DriverID  uuid.UUID
	DriverRef string
	UserID    uuid.UUID
	InstallID string
	Token     string
}

// The devices of drivers: the device_tokens rows of each driver's linked user (drivers.user_id), so a
// driver re-linked to another user never reaches the old user's phone. driver_ref is the id the app
// knows (legacy_doc_id, else the uuid).
func (q *Queries) DriverDevices(ctx context.Context, driverIds []uuid.UUID) ([]DriverDevicesRow, error) {
	rows, err := q.db.Query(ctx, driverDevices, driverIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverDevicesRow{}
	for rows.Next() {
		var i DriverDevicesRow
		if err := rows.Scan(
			&i.DriverID,
			&i.DriverRef,
			&i.UserID,
			&i.InstallID,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskForPush = `-- name: GetTaskForPush :one
SELECT id, coalesce(legacy_doc_id, id::text)::text AS task_ref, task_type, status, driver_id, helper_driver_id,
       source_hub_raw, destination_raw, to_char(plan_date, 'YYYY-MM-DD')::text AS plan_date,
       coalesce(plan_time, '')::text AS plan_time
FROM tasks
WHERE id = $1
`

type GetTaskForPushRow struct {
	ID             uuid.UUID
	TaskRef        string
	TaskType       string
	Status         string
	DriverID       *uuid.UUID
	HelperDriverID *uuid.UUID
	SourceHubRaw   string
	DestinationRaw string
	PlanDate       string
	PlanTime       string
}

// task_ref is the id the app knows: the Firestore document id while APK 3.x is installed (legacy_doc_id,
// else the uuid write-back mints as the document id, R25).
func (q *Queries) GetTaskForPush(ctx context.Context, id uuid.UUID) (GetTaskForPushRow, error) {
	row := q.db.QueryRow(ctx, getTaskForPush, id)
	var i GetTaskForPushRow
	err := row.Scan(
		&i.ID,
		&i.TaskRef,
		&i.TaskType,
		&i.Status,
		&i.DriverID,
		&i.HelperDriverID,
		&i.SourceHubRaw,
		&i.DestinationRaw,
		&i.PlanDate,
		&i.PlanTime,
	)
	return i, err
}

const inboxClaimed = `-- name: InboxClaimed :one

SELECT EXISTS (SELECT 1 FROM consumer_inbox WHERE consumer = $1 AND message_id = $2)::boolean AS claimed
`

type InboxClaimedParams struct {
	Consumer  string
	MessageID string
}

// notify.fcm (main spec §7.6, Appendix B §B.5.3): recipients are read server-side from the entity the
// event names, devices from device_tokens (R4); every push is logged in notification_deliveries.
// A message whose deliveries were already recorded (its consumer_inbox row committed) is acked at once.
func (q *Queries) InboxClaimed(ctx context.Context, arg InboxClaimedParams) (bool, error) {
	row := q.db.QueryRow(ctx, inboxClaimed, arg.Consumer, arg.MessageID)
	var claimed bool
	err := row.Scan(&claimed)
	return claimed, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO notification_deliveries (outbox_event_id, user_id, install_id, kind, payload, status, error, created_at, sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9)
`

type InsertDeliveryParams struct {
	OutboxEventID *int64
	UserID        *uuid.UUID
	InstallID     *string
	Kind          string
	Payload       []byte
	Status        string
	Error         *string
	CreatedAt     time.Time
	SentAt        *time.Time
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.OutboxEventID,
		arg.UserID,
		arg.InstallID,
		arg.Kind,
		arg.Payload,
		arg.Status,
		arg.Error,
		arg.CreatedAt,
		arg.SentAt,
	)
	return err
}

const revokedSessionDevices = `-- name: RevokedSessionDevices :many
SELECT DISTINCT ON (dt.install_id) s.id AS session_id, dt.install_id, dt.token
FROM sessions s
JOIN device_tokens dt ON dt.user_id = s.user_id AND dt.install_id = s.install_id
WHERE s.user_id = $1
  AND s.id = ANY ($2::uuid[])
  AND s.revoked_at IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM sessions live
                  WHERE live.user_id = s.user_id AND live.install_id = s.install_id
                    AND live.revoked_at IS NULL AND live.absolute_expires_at > now())
ORDER BY dt.install_id, s.revoked_at DESC, s.id
`

type RevokedSessionDevicesParams struct {
	UserID     uuid.UUID
	SessionIds []uuid.UUID
}

type RevokedSessionDevicesRow struct {
	SessionID uuid.UUID
	InstallID string
	Token     string
}

// R50, R83, R84: the device of each revoked session is the device_tokens row of the same user and
// install. An install signed in again since (it holds a live session, at most one per install) gets
// nothing: the push would end the new session.
func (q *Queries) RevokedSessionDevices(ctx context.Context, arg RevokedSessionDevicesParams) ([]RevokedSessionDevicesRow, error) {
	rows, err := q.db.Query(ctx, revokedSessionDevices, arg.UserID, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokedSessionDevicesRow{}
	for rows.Next() {
		var i RevokedSessionDevicesRow
		if err := rows.Scan(&i.SessionID, &i.InstallID, &i.Token); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
