// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package iamdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bootstrapEligibility = `-- name: BootstrapEligibility :one
SELECT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id AND r.role = 'platform_admin')::boolean AS held,
       (EXISTS (SELECT 1 FROM auth_identities i
                WHERE i.user_id = u.id AND i.provider = 'firebase_legacy' AND i.email_at_link = u.email)
        OR coalesce((SELECT CASE WHEN e.actor_user_id IS NULL
                                 THEN e.event_type = 'user_created' AND e.details->>'source' = 'bootstrap'
                                 ELSE EXISTS (SELECT 1 FROM user_platform_roles r
                                              WHERE r.user_id = e.actor_user_id AND r.role = 'platform_admin') END
                     FROM security_events e
                     WHERE e.target_user_id = u.id AND e.legacy_doc_id IS NULL
                       AND (e.event_type = 'user_created'
                         OR (e.event_type = 'user_updated' AND e.details->>'emailChanged' = 'true'))
                     ORDER BY e.created_at DESC, e.id DESC
                     LIMIT 1), false))::boolean AS address_proven,
       EXISTS (SELECT 1 FROM memberships m JOIN tenants t ON t.id = m.tenant_id
               WHERE m.user_id = u.id AND t.kind <> 'own_fleet')::boolean AS other_tenant,
       EXISTS (SELECT 1 FROM user_scopes s WHERE s.user_id = u.id)::boolean AS has_scope
FROM users u
WHERE u.id = $1
`

type BootstrapEligibilityRow struct {
	Held          bool
	AddressProven bool
	OtherTenant   bool
	HasScope      bool
}

// Whether the bootstrap may grant platform_admin to the user that holds a listed address (Appendix C §C.5.5). Anyone
// who creates or renames users (a carrier tenant_admin included) could otherwise claim a listed address before its
// owner has an account. The address must be proven: it is the address of the user's firebase_legacy identity (the
// import, unchanged since), or the latest Go event that set it (user_updated with emailChanged, else user_created)
// was written by the bootstrap itself or by a platform admin. The user must also belong to no tenant other than the
// own fleet and hold no scope.
func (q *Queries) BootstrapEligibility(ctx context.Context, id uuid.UUID) (BootstrapEligibilityRow, error) {
	row := q.db.QueryRow(ctx, bootstrapEligibility, id)
	var i BootstrapEligibilityRow
	err := row.Scan(
		&i.Held,
		&i.AddressProven,
		&i.OtherTenant,
		&i.HasScope,
	)
	return i, err
}

const bootstrapUserByEmail = `-- name: BootstrapUserByEmail :one

SELECT id, password_hash, status, must_change_password
FROM users
WHERE email = $1::text::citext AND status <> 'deleted'
FOR NO KEY UPDATE
`

type BootstrapUserByEmailRow struct {
	ID                 uuid.UUID
	PasswordHash       *string
	Status             string
	MustChangePassword bool
}

// Platform bootstrap (T19, Appendix C §C.1.6, §C.5.5; owner addition 2026-10-10): cmd/seed
// bootstrap-platform-admins grants platform_admin to the PLATFORM_ADMIN_EMAILS users, and seed --bootstrap-admin
// creates or updates the super admin of a fresh deployment from BOOTSTRAP_ADMIN_EMAIL / _PASSWORD. Both run in
// the seed's db.WithSystem transaction.
func (q *Queries) BootstrapUserByEmail(ctx context.Context, email string) (BootstrapUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, bootstrapUserByEmail, email)
	var i BootstrapUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Status,
		&i.MustChangePassword,
	)
	return i, err
}

const bumpUserVersion = `-- name: BumpUserVersion :one
UPDATE users SET auth_version = auth_version + 1 WHERE id = $1 RETURNING auth_version
`

// A claims change made by the bootstrap (platform_admin granted): tokens issued before are refreshed.
func (q *Queries) BumpUserVersion(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, bumpUserVersion, id)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const insertBootstrapUser = `-- name: InsertBootstrapUser :one
INSERT INTO users (email, email_verified, display_name, password_hash, must_change_password, password_changed_at)
VALUES ($1::text::citext, true, $2::text, $3::text, false,
        $4::timestamptz)
RETURNING id
`

type InsertBootstrapUserParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
	ChangedAt    time.Time
}

func (q *Queries) InsertBootstrapUser(ctx context.Context, arg InsertBootstrapUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBootstrapUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.ChangedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const platformAdminsOutside = `-- name: PlatformAdminsOutside :many
SELECT u.id, coalesce(u.email::text, '')::text AS email
FROM user_platform_roles r
JOIN users u ON u.id = r.user_id
WHERE r.role = 'platform_admin' AND (u.email IS NULL OR NOT (u.email = ANY ($1::text[]::citext[])))
ORDER BY u.email, u.id
`

type PlatformAdminsOutsideRow struct {
	ID    uuid.UUID
	Email string
}

// platform_admin holders whose address is not in the list (Appendix C §C.5.9: no user holds platform_admin
// unless listed in PLATFORM_ADMIN_EMAILS). Reported, never revoked: a later grant through the API is legitimate.
func (q *Queries) PlatformAdminsOutside(ctx context.Context, emails []string) ([]PlatformAdminsOutsideRow, error) {
	rows, err := q.db.Query(ctx, platformAdminsOutside, emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAdminsOutsideRow{}
	for rows.Next() {
		var i PlatformAdminsOutsideRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateBootstrapUser = `-- name: ReactivateBootstrapUser :one
UPDATE users
SET status = 'active', disabled_at = NULL, must_change_password = false, auth_version = auth_version + 1
WHERE id = $1
RETURNING auth_version
`

// The password is unchanged but the account was disabled, reset_required or flagged: make it usable.
func (q *Queries) ReactivateBootstrapUser(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, reactivateBootstrapUser, id)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const revokeAllSessions = `-- name: RevokeAllSessions :many
UPDATE sessions
SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE user_id = $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeAllSessionsParams struct {
	At     time.Time
	Reason string
	UserID uuid.UUID
}

func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllSessions, arg.At, arg.Reason, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTokensOfSessions = `-- name: RevokeTokensOfSessions :exec
UPDATE refresh_tokens SET revoked_at = $1::timestamptz, revoked_reason = $2::text
WHERE session_id = ANY ($3::uuid[]) AND revoked_at IS NULL
`

type RevokeTokensOfSessionsParams struct {
	At         time.Time
	Reason     string
	SessionIds []uuid.UUID
}

func (q *Queries) RevokeTokensOfSessions(ctx context.Context, arg RevokeTokensOfSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeTokensOfSessions, arg.At, arg.Reason, arg.SessionIds)
	return err
}

const setBootstrapPassword = `-- name: SetBootstrapPassword :one
UPDATE users
SET password_hash        = $1::text,
    legacy_scrypt_hash   = NULL,
    legacy_scrypt_salt   = NULL,
    must_change_password = false,
    password_changed_at  = $2::timestamptz,
    status               = 'active',
    disabled_at          = NULL,
    auth_version         = auth_version + 1
WHERE id = $3
RETURNING auth_version
`

type SetBootstrapPasswordParams struct {
	PasswordHash string
	ChangedAt    time.Time
	ID           uuid.UUID
}

// A new password for the bootstrap admin: the account becomes usable again (active, no legacy hash, no
// must-change flag) and every token issued before is judged by the new auth_version.
func (q *Queries) SetBootstrapPassword(ctx context.Context, arg SetBootstrapPasswordParams) (int32, error) {
	row := q.db.QueryRow(ctx, setBootstrapPassword, arg.PasswordHash, arg.ChangedAt, arg.ID)
	var auth_version int32
	err := row.Scan(&auth_version)
	return auth_version, err
}

const usersByEmails = `-- name: UsersByEmails :many
SELECT id, email::text AS email FROM users
WHERE email = ANY ($1::text[]::citext[]) AND status <> 'deleted'
ORDER BY email
`

type UsersByEmailsRow struct {
	ID    uuid.UUID
	Email string
}

func (q *Queries) UsersByEmails(ctx context.Context, emails []string) ([]UsersByEmailsRow, error) {
	rows, err := q.db.Query(ctx, usersByEmails, emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersByEmailsRow{}
	for rows.Next() {
		var i UsersByEmailsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
