// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package iamdb

import (
	"context"

	"github.com/google/uuid"
)

const ownFleetTenant = `-- name: OwnFleetTenant :one
SELECT id FROM tenants WHERE kind = 'own_fleet'
`

func (q *Queries) OwnFleetTenant(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, ownFleetTenant)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const roleOverrides = `-- name: RoleOverrides :many

SELECT tenant_id, capability, allowed
  FROM role_capability_overrides
 WHERE role = $1 AND (tenant_id IS NULL OR tenant_id = $2::uuid)
 ORDER BY tenant_id NULLS FIRST, capability
`

type RoleOverridesParams struct {
	Role     string
	TenantID uuid.UUID
}

type RoleOverridesRow struct {
	TenantID   *uuid.UUID
	Capability string
	Allowed    bool
}

// Inputs of the per-request authorization (Appendix C §C.2.5, §C.3.4, §C.3.9). The identity tables are
// platform-only under RLS, so the RBAC service reads them in db.WithSystem; nothing here is returned to a
// caller as data.
// The override rows of one role that apply in one tenant: the platform-wide rows (tenant_id NULL) and the
// rows of that tenant.
func (q *Queries) RoleOverrides(ctx context.Context, arg RoleOverridesParams) ([]RoleOverridesRow, error) {
	rows, err := q.db.Query(ctx, roleOverrides, arg.Role, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleOverridesRow{}
	for rows.Next() {
		var i RoleOverridesRow
		if err := rows.Scan(&i.TenantID, &i.Capability, &i.Allowed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtenants = `-- name: Subtenants :many
SELECT id FROM tenants WHERE contractor_tenant_id = $1::uuid ORDER BY id
`

// Contractor reach (R60): the carrier tenants that work for tenant_id; one level, never transitive.
func (q *Queries) Subtenants(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, subtenants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantKind = `-- name: TenantKind :one
SELECT kind FROM tenants WHERE id = $1::uuid
`

func (q *Queries) TenantKind(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, tenantKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}
