// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package iamdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTenant = `-- name: GetTenant :one
SELECT t.id, t.kind, t.code, t.name_th, t.name_en, t.legal_type, t.id_card_number, t.tax_id,
       t.contact_person, t.phone, t.email, t.website, t.address, t.designation, t.fleet_size,
       t.dispatch_center, t.service_regions, t.vehicle_types, t.line_group_id, t.contractor_tenant_id, t.status,
       t.created_at, t.updated_at, bp.id AS billing_party_id, bp.billing_date_basis
FROM tenants t
LEFT JOIN billing_parties bp ON bp.tenant_id = t.id
WHERE t.id = $1
`

type GetTenantRow struct {
	ID                 uuid.UUID
	Kind               string
	Code               *string
	NameTh             string
	NameEn             *string
	LegalType          *string
	IDCardNumber       *string
	TaxID              *string
	ContactPerson      *string
	Phone              *string
	Email              *string
	Website            *string
	Address            *string
	Designation        *string
	FleetSize          int32
	DispatchCenter     *string
	ServiceRegions     []string
	VehicleTypes       []string
	LineGroupID        *string
	ContractorTenantID *uuid.UUID
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	BillingPartyID     *uuid.UUID
	BillingDateBasis   *string
}

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Code,
		&i.NameTh,
		&i.NameEn,
		&i.LegalType,
		&i.IDCardNumber,
		&i.TaxID,
		&i.ContactPerson,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Address,
		&i.Designation,
		&i.FleetSize,
		&i.DispatchCenter,
		&i.ServiceRegions,
		&i.VehicleTypes,
		&i.LineGroupID,
		&i.ContractorTenantID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingPartyID,
		&i.BillingDateBasis,
	)
	return i, err
}

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (kind, code, name_th, name_en, legal_type, id_card_number, tax_id, contact_person, phone, email,
                     website, address, designation, fleet_size, dispatch_center, service_regions, vehicle_types,
                     line_group_id, contractor_tenant_id, status)
VALUES ('carrier', $1::text::citext, $2, $3, $4,
        $5, $6, $7, $8,
        $9::text::citext, $10, $11, $12,
        $13, $14, $15::text[],
        $16::text[], $17, $18, $19)
RETURNING id, kind, code, name_th, name_en, status, legal_type, contractor_tenant_id, created_at
`

type InsertTenantParams struct {
	Code               *string
	NameTh             string
	NameEn             *string
	LegalType          *string
	IDCardNumber       *string
	TaxID              *string
	ContactPerson      *string
	Phone              *string
	Email              *string
	Website            *string
	Address            *string
	Designation        *string
	FleetSize          int32
	DispatchCenter     *string
	ServiceRegions     []string
	VehicleTypes       []string
	LineGroupID        *string
	ContractorTenantID *uuid.UUID
	Status             string
}

type InsertTenantRow struct {
	ID                 uuid.UUID
	Kind               string
	Code               *string
	NameTh             string
	NameEn             *string
	Status             string
	LegalType          *string
	ContractorTenantID *uuid.UUID
	CreatedAt          time.Time
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (InsertTenantRow, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.Code,
		arg.NameTh,
		arg.NameEn,
		arg.LegalType,
		arg.IDCardNumber,
		arg.TaxID,
		arg.ContactPerson,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Address,
		arg.Designation,
		arg.FleetSize,
		arg.DispatchCenter,
		arg.ServiceRegions,
		arg.VehicleTypes,
		arg.LineGroupID,
		arg.ContractorTenantID,
		arg.Status,
	)
	var i InsertTenantRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Code,
		&i.NameTh,
		&i.NameEn,
		&i.Status,
		&i.LegalType,
		&i.ContractorTenantID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTenantParty = `-- name: InsertTenantParty :one
INSERT INTO billing_parties (kind, tenant_id) VALUES ('tenant', $1) RETURNING id
`

// The tenant's billing party (R6): every carrier is billable as a party of kind 'tenant'.
func (q *Queries) InsertTenantParty(ctx context.Context, tenantID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTenantParty, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTenantStatusHistory = `-- name: InsertTenantStatusHistory :exec
INSERT INTO status_history (entity_type, entity_id, status, previous_status, changed_at, changed_by_user_id, reason)
VALUES ('tenant', $1, $2, $3, $4::timestamptz,
        $5, $6)
`

type InsertTenantStatusHistoryParams struct {
	EntityID        uuid.UUID
	Status          string
	PreviousStatus  *string
	ChangedAt       time.Time
	ChangedByUserID *uuid.UUID
	Reason          *string
}

func (q *Queries) InsertTenantStatusHistory(ctx context.Context, arg InsertTenantStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertTenantStatusHistory,
		arg.EntityID,
		arg.Status,
		arg.PreviousStatus,
		arg.ChangedAt,
		arg.ChangedByUserID,
		arg.Reason,
	)
	return err
}

const isActiveMember = `-- name: IsActiveMember :one
SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = $1 AND tenant_id = $2
               AND status = 'active')::boolean AS member
`

type IsActiveMemberParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) IsActiveMember(ctx context.Context, arg IsActiveMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveMember, arg.UserID, arg.TenantID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const listTenants = `-- name: ListTenants :many

SELECT id, kind, code, name_th, name_en, status, legal_type, contractor_tenant_id, created_at
FROM tenants
WHERE ($1::text IS NULL OR kind = $1)
  AND (NOT $2::boolean OR kind = 'carrier')
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL
    OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListTenantsParams struct {
	Kind         *string
	CarriersOnly bool
	Status       *string
	AfterCreated *time.Time
	AfterID      uuid.UUID
	RowLimit     int32
}

type ListTenantsRow struct {
	ID                 uuid.UUID
	Kind               string
	Code               *string
	NameTh             string
	NameEn             *string
	Status             string
	LegalType          *string
	ContractorTenantID *uuid.UUID
	CreatedAt          time.Time
}

// Tenants administration (T19 owner addition, Appendix B §B.2.4, Appendix C §C.8): carrier tenants created
// and edited by platform admins, with their billing_parties row and status history. Run in db.WithSystem
// after Go authorization (the structural columns are platform-only, trigger t_tenant_admin_columns).
// GET /v1/tenants, newest first; carriers_only for the steward view of fleet:manage_subcontractors.
func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Kind,
		arg.CarriersOnly,
		arg.Status,
		arg.AfterCreated,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Code,
			&i.NameTh,
			&i.NameEn,
			&i.Status,
			&i.LegalType,
			&i.ContractorTenantID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTenant = `-- name: LockTenant :one
SELECT id, kind, code, name_th, name_en, status, legal_type, contractor_tenant_id, created_at
FROM tenants WHERE id = $1 FOR UPDATE
`

type LockTenantRow struct {
	ID                 uuid.UUID
	Kind               string
	Code               *string
	NameTh             string
	NameEn             *string
	Status             string
	LegalType          *string
	ContractorTenantID *uuid.UUID
	CreatedAt          time.Time
}

func (q *Queries) LockTenant(ctx context.Context, id uuid.UUID) (LockTenantRow, error) {
	row := q.db.QueryRow(ctx, lockTenant, id)
	var i LockTenantRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Code,
		&i.NameTh,
		&i.NameEn,
		&i.Status,
		&i.LegalType,
		&i.ContractorTenantID,
		&i.CreatedAt,
	)
	return i, err
}

const tenantStatusHistory = `-- name: TenantStatusHistory :many
SELECT status, previous_status, changed_at, changed_by_user_id, changed_by_label, reason
FROM status_history
WHERE entity_type = 'tenant' AND entity_id = $1
ORDER BY changed_at DESC, id DESC
LIMIT 50
`

type TenantStatusHistoryRow struct {
	Status          string
	PreviousStatus  *string
	ChangedAt       time.Time
	ChangedByUserID *uuid.UUID
	ChangedByLabel  *string
	Reason          *string
}

func (q *Queries) TenantStatusHistory(ctx context.Context, id uuid.UUID) ([]TenantStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, tenantStatusHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantStatusHistoryRow{}
	for rows.Next() {
		var i TenantStatusHistoryRow
		if err := rows.Scan(
			&i.Status,
			&i.PreviousStatus,
			&i.ChangedAt,
			&i.ChangedByUserID,
			&i.ChangedByLabel,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET code    = CASE WHEN $1::boolean THEN $2::text::citext ELSE code END,
    name_th = coalesce($3::text, name_th),
    name_en = CASE WHEN $4::boolean THEN $5::text ELSE name_en END,
    status  = coalesce($6::text, status),
    contractor_tenant_id = CASE WHEN $7::boolean THEN $8::uuid
                                ELSE contractor_tenant_id END
WHERE id = $9
RETURNING id, kind, code, name_th, name_en, status, legal_type, contractor_tenant_id, created_at
`

type UpdateTenantParams struct {
	SetCode            bool
	Code               *string
	NameTh             *string
	SetNameEn          bool
	NameEn             *string
	Status             *string
	SetContractor      bool
	ContractorTenantID *uuid.UUID
	ID                 uuid.UUID
}

type UpdateTenantRow struct {
	ID                 uuid.UUID
	Kind               string
	Code               *string
	NameTh             string
	NameEn             *string
	Status             string
	LegalType          *string
	ContractorTenantID *uuid.UUID
	CreatedAt          time.Time
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (UpdateTenantRow, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.SetCode,
		arg.Code,
		arg.NameTh,
		arg.SetNameEn,
		arg.NameEn,
		arg.Status,
		arg.SetContractor,
		arg.ContractorTenantID,
		arg.ID,
	)
	var i UpdateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Code,
		&i.NameTh,
		&i.NameEn,
		&i.Status,
		&i.LegalType,
		&i.ContractorTenantID,
		&i.CreatedAt,
	)
	return i, err
}
