// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package iamdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeTenantMembers = `-- name: ActiveTenantMembers :many
SELECT user_id FROM memberships WHERE tenant_id = $1 AND status = 'active' ORDER BY user_id
`

// The active members of a tenant whose claims a status change alters (PATCH /v1/tenants/{id} suspend or reactivate),
// in user id order (the users rows are locked in that order).
func (q *Queries) ActiveTenantMembers(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOtherScopes = `-- name: CountOtherScopes :one
SELECT count(*)::int FROM user_scopes WHERE user_id = $1 AND kind <> $2
`

type CountOtherScopesParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) CountOtherScopes(ctx context.Context, arg CountOtherScopesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOtherScopes, arg.UserID, arg.Kind)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMembership = `-- name: DeleteMembership :one
DELETE FROM memberships WHERE user_id = $1 AND tenant_id = $2 RETURNING role
`

type DeleteMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteMembership, arg.UserID, arg.TenantID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const deletePlatformRole = `-- name: DeletePlatformRole :execrows
DELETE FROM user_platform_roles WHERE user_id = $1 AND role = $2
`

type DeletePlatformRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) DeletePlatformRole(ctx context.Context, arg DeletePlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatformRole, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScopesNotIn = `-- name: DeleteScopesNotIn :exec
DELETE FROM user_scopes
WHERE user_id = $1 AND kind = $2
  AND NOT (billing_party_id = ANY ($3::uuid[]))
`

type DeleteScopesNotInParams struct {
	UserID uuid.UUID
	Kind   string
	Keep   []uuid.UUID
}

func (q *Queries) DeleteScopesNotIn(ctx context.Context, arg DeleteScopesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteScopesNotIn, arg.UserID, arg.Kind, arg.Keep)
	return err
}

const driverOfUser = `-- name: DriverOfUser :one
SELECT id, tenant_id FROM drivers WHERE user_id = $1::uuid FOR UPDATE
`

type DriverOfUserRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DriverOfUser(ctx context.Context, userID uuid.UUID) (DriverOfUserRow, error) {
	row := q.db.QueryRow(ctx, driverOfUser, userID)
	var i DriverOfUserRow
	err := row.Scan(&i.ID, &i.TenantID)
	return i, err
}

const existingParties = `-- name: ExistingParties :many
SELECT id FROM billing_parties WHERE id = ANY ($1::uuid[])
`

func (q *Queries) ExistingParties(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, existingParties, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT u.id, u.email, u.display_name, u.photo_file_id, u.status, u.must_change_password, u.last_login_at,
       u.created_at, u.legacy_auth_uid
FROM users u
WHERE u.id = $1
  AND ($2::boolean
    OR EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.tenant_id = ANY ($3::uuid[]))
    OR ($4::boolean AND NOT EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id)
        AND NOT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id)))
`

type GetAdminUserParams struct {
	ID        uuid.UUID
	AllUsers  bool
	TenantIds []uuid.UUID
	ScopeOnly bool
}

type GetAdminUserRow struct {
	ID                 uuid.UUID
	Email              *string
	DisplayName        *string
	PhotoFileID        *uuid.UUID
	Status             string
	MustChangePassword bool
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	LegacyAuthUid      *string
}

func (q *Queries) GetAdminUser(ctx context.Context, arg GetAdminUserParams) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser,
		arg.ID,
		arg.AllUsers,
		arg.TenantIds,
		arg.ScopeOnly,
	)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoFileID,
		&i.Status,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.LegacyAuthUid,
	)
	return i, err
}

const getLinkDriver = `-- name: GetLinkDriver :one
SELECT id, tenant_id, user_id FROM drivers WHERE id = $1 FOR UPDATE
`

type GetLinkDriverRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   *uuid.UUID
}

func (q *Queries) GetLinkDriver(ctx context.Context, id uuid.UUID) (GetLinkDriverRow, error) {
	row := q.db.QueryRow(ctx, getLinkDriver, id)
	var i GetLinkDriverRow
	err := row.Scan(&i.ID, &i.TenantID, &i.UserID)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT role, status FROM memberships WHERE user_id = $1 AND tenant_id = $2
`

type GetMembershipParams struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
}

type GetMembershipRow struct {
	Role   string
	Status string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i GetMembershipRow
	err := row.Scan(&i.Role, &i.Status)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :one
INSERT INTO users (email, email_verified, display_name, password_hash, must_change_password, password_changed_at)
VALUES ($1::text, false, $2::text, $3::text,
        $4::boolean, $5::timestamptz)
RETURNING id
`

type InsertAdminUserParams struct {
	Email              string
	DisplayName        string
	PasswordHash       *string
	MustChangePassword bool
	PasswordChangedAt  *time.Time
}

// POST /v1/users: a temporary password (must change at the first sign-in, R29, R79) or none (an invite).
func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAdminUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.PasswordChangedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPlatformRole = `-- name: InsertPlatformRole :execrows
INSERT INTO user_platform_roles (user_id, role, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role) DO NOTHING
`

type InsertPlatformRoleParams struct {
	UserID    uuid.UUID
	Role      string
	GrantedBy *uuid.UUID
}

func (q *Queries) InsertPlatformRole(ctx context.Context, arg InsertPlatformRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPlatformRole, arg.UserID, arg.Role, arg.GrantedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertScope = `-- name: InsertScope :exec
INSERT INTO user_scopes (user_id, kind, billing_party_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT user_scopes_key DO NOTHING
`

type InsertScopeParams struct {
	UserID         uuid.UUID
	Kind           string
	BillingPartyID uuid.UUID
	CreatedBy      *uuid.UUID
}

func (q *Queries) InsertScope(ctx context.Context, arg InsertScopeParams) error {
	_, err := q.db.Exec(ctx, insertScope,
		arg.UserID,
		arg.Kind,
		arg.BillingPartyID,
		arg.CreatedBy,
	)
	return err
}

const listAdminSessions = `-- name: ListAdminSessions :many
SELECT id, platform, amr, install_id, device_label, app_version, coalesce(host(ip), '')::text AS ip, user_agent,
       created_at, last_seen_at
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND absolute_expires_at > $2::timestamptz
ORDER BY last_seen_at DESC, id DESC
`

type ListAdminSessionsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

type ListAdminSessionsRow struct {
	ID          uuid.UUID
	Platform    string
	Amr         string
	InstallID   *string
	DeviceLabel *string
	AppVersion  *string
	Ip          string
	UserAgent   *string
	CreatedAt   time.Time
	LastSeenAt  time.Time
}

// GET /v1/users/{id}/sessions: the live sessions of the user, most recently used first.
func (q *Queries) ListAdminSessions(ctx context.Context, arg ListAdminSessionsParams) ([]ListAdminSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAdminSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSessionsRow{}
	for rows.Next() {
		var i ListAdminSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Amr,
			&i.InstallID,
			&i.DeviceLabel,
			&i.AppVersion,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeParties = `-- name: ListScopeParties :many
SELECT billing_party_id FROM user_scopes WHERE user_id = $1 AND kind = $2
ORDER BY created_at, billing_party_id
`

type ListScopePartiesParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) ListScopeParties(ctx context.Context, arg ListScopePartiesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listScopeParties, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var billing_party_id uuid.UUID
		if err := rows.Scan(&billing_party_id); err != nil {
			return nil, err
		}
		items = append(items, billing_party_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT m.user_id, u.email, u.display_name, m.role, m.status, u.last_login_at, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
  AND ($2::text IS NULL OR m.role = $2)
  AND ($3::timestamptz IS NULL
    OR (m.created_at, m.user_id) < ($3::timestamptz, $4::uuid))
ORDER BY m.created_at DESC, m.user_id DESC
LIMIT $5
`

type ListTenantMembersParams struct {
	TenantID     uuid.UUID
	Role         *string
	AfterCreated *time.Time
	AfterID      uuid.UUID
	RowLimit     int32
}

type ListTenantMembersRow struct {
	UserID      uuid.UUID
	Email       *string
	DisplayName *string
	Role        string
	Status      string
	LastLoginAt *time.Time
	CreatedAt   time.Time
}

// GET /v1/tenants/{id}/members: members newest first (membership created_at DESC, user id DESC).
func (q *Queries) ListTenantMembers(ctx context.Context, arg ListTenantMembersParams) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers,
		arg.TenantID,
		arg.Role,
		arg.AfterCreated,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDrivers = `-- name: ListUserDrivers :many
SELECT d.user_id::uuid AS user_id, d.id, d.tenant_id,
       coalesce(nullif(btrim(d.full_name_th), ''), btrim(d.first_name || ' ' || d.last_name))::text AS display_name
FROM drivers d
WHERE d.user_id = ANY ($1::uuid[])
  AND ($2::boolean OR d.tenant_id = ANY ($3::uuid[]))
`

type ListUserDriversParams struct {
	UserIds   []uuid.UUID
	AllUsers  bool
	TenantIds []uuid.UUID
}

type ListUserDriversRow struct {
	UserID      uuid.UUID
	ID          uuid.UUID
	TenantID    uuid.UUID
	DisplayName string
}

// The driver row linked to each listed user, when its tenant is in reach.
func (q *Queries) ListUserDrivers(ctx context.Context, arg ListUserDriversParams) ([]ListUserDriversRow, error) {
	rows, err := q.db.Query(ctx, listUserDrivers, arg.UserIds, arg.AllUsers, arg.TenantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDriversRow{}
	for rows.Next() {
		var i ListUserDriversRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.TenantID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT m.user_id, m.tenant_id, t.name_th, t.name_en, t.kind, m.role, m.status
FROM memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.user_id = ANY ($1::uuid[])
  AND ($2::boolean OR m.tenant_id = ANY ($3::uuid[]))
ORDER BY m.user_id, (t.kind = 'own_fleet') DESC, t.name_th, m.tenant_id
`

type ListUserMembershipsParams struct {
	UserIds   []uuid.UUID
	AllUsers  bool
	TenantIds []uuid.UUID
}

type ListUserMembershipsRow struct {
	UserID   uuid.UUID
	TenantID uuid.UUID
	NameTh   string
	NameEn   *string
	Kind     string
	Role     string
	Status   string
}

// Memberships of the listed users within the reach (every membership for all_users), own fleet first.
func (q *Queries) ListUserMemberships(ctx context.Context, arg ListUserMembershipsParams) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, arg.UserIds, arg.AllUsers, arg.TenantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserMembershipsRow{}
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.UserID,
			&i.TenantID,
			&i.NameTh,
			&i.NameEn,
			&i.Kind,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPlatformRoles = `-- name: ListUserPlatformRoles :many
SELECT user_id, role FROM user_platform_roles WHERE user_id = ANY ($1::uuid[]) ORDER BY user_id, role
`

type ListUserPlatformRolesRow struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) ListUserPlatformRoles(ctx context.Context, userIds []uuid.UUID) ([]ListUserPlatformRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserPlatformRoles, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPlatformRolesRow{}
	for rows.Next() {
		var i ListUserPlatformRolesRow
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserScopes = `-- name: ListUserScopes :many
SELECT s.user_id, s.kind, s.billing_party_id, coalesce(c.name, t.name_th, '')::text AS party_name
FROM user_scopes s
JOIN billing_parties bp ON bp.id = s.billing_party_id
LEFT JOIN customers c ON c.id = bp.customer_id
LEFT JOIN tenants t ON t.id = bp.tenant_id
WHERE s.user_id = ANY ($1::uuid[])
ORDER BY s.user_id, s.kind, s.created_at, s.billing_party_id
`

type ListUserScopesRow struct {
	UserID         uuid.UUID
	Kind           string
	BillingPartyID uuid.UUID
	PartyName      string
}

func (q *Queries) ListUserScopes(ctx context.Context, userIds []uuid.UUID) ([]ListUserScopesRow, error) {
	rows, err := q.db.Query(ctx, listUserScopes, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserScopesRow{}
	for rows.Next() {
		var i ListUserScopesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.BillingPartyID,
			&i.PartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByCreated = `-- name: ListUsersByCreated :many
SELECT u.id, u.email, u.display_name, u.photo_file_id, u.status, u.must_change_password, u.last_login_at,
       u.created_at, u.legacy_auth_uid
FROM users u
WHERE ($1::boolean
    OR EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.tenant_id = ANY ($2::uuid[]))
    OR ($3::boolean AND NOT EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id)
        AND NOT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id)))
  AND ($4::text IS NULL OR u.email::text ILIKE $4 ESCAPE '\' OR u.display_name ILIKE $4 ESCAPE '\')
  AND (($5::text IS NULL AND u.status <> 'deleted') OR u.status = $5)
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.role = $6
          AND ($1 OR m.tenant_id = ANY ($2::uuid[]))))
  AND ($7::text IS NULL OR EXISTS (
        SELECT 1 FROM user_scopes s WHERE s.user_id = u.id AND s.kind = $7))
  AND ($8::text IS NULL OR EXISTS (
        SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id AND r.role = $8))
  AND ($9::timestamptz IS NULL
    OR (u.created_at, u.id) < ($9::timestamptz, $10::uuid))
ORDER BY u.created_at DESC, u.id DESC
LIMIT $11
`

type ListUsersByCreatedParams struct {
	AllUsers     bool
	TenantIds    []uuid.UUID
	ScopeOnly    bool
	Q            *string
	Status       *string
	MemberRole   *string
	ScopeKind    *string
	PlatformRole *string
	AfterCreated *time.Time
	AfterID      uuid.UUID
	RowLimit     int32
}

type ListUsersByCreatedRow struct {
	ID                 uuid.UUID
	Email              *string
	DisplayName        *string
	PhotoFileID        *uuid.UUID
	Status             string
	MustChangePassword bool
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	LegacyAuthUid      *string
}

// GET /v1/users, default order created_at DESC, id DESC (Appendix B §B.1.5). q matches email or display name
// (the caller escapes LIKE wildcards); member_role, scope_kind and platform_role filter by the role axis.
func (q *Queries) ListUsersByCreated(ctx context.Context, arg ListUsersByCreatedParams) ([]ListUsersByCreatedRow, error) {
	rows, err := q.db.Query(ctx, listUsersByCreated,
		arg.AllUsers,
		arg.TenantIds,
		arg.ScopeOnly,
		arg.Q,
		arg.Status,
		arg.MemberRole,
		arg.ScopeKind,
		arg.PlatformRole,
		arg.AfterCreated,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByCreatedRow{}
	for rows.Next() {
		var i ListUsersByCreatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PhotoFileID,
			&i.Status,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.LegacyAuthUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByLastLogin = `-- name: ListUsersByLastLogin :many
SELECT u.id, u.email, u.display_name, u.photo_file_id, u.status, u.must_change_password, u.last_login_at,
       u.created_at, u.legacy_auth_uid
FROM users u
WHERE ($1::boolean
    OR EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.tenant_id = ANY ($2::uuid[]))
    OR ($3::boolean AND NOT EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id)
        AND NOT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id)))
  AND ($4::text IS NULL OR u.email::text ILIKE $4 ESCAPE '\' OR u.display_name ILIKE $4 ESCAPE '\')
  AND (($5::text IS NULL AND u.status <> 'deleted') OR u.status = $5)
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.role = $6
          AND ($1 OR m.tenant_id = ANY ($2::uuid[]))))
  AND ($7::text IS NULL OR EXISTS (
        SELECT 1 FROM user_scopes s WHERE s.user_id = u.id AND s.kind = $7))
  AND ($8::text IS NULL OR EXISTS (
        SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id AND r.role = $8))
  AND (NOT $9::boolean
    OR ($10::timestamptz IS NOT NULL
        AND (u.last_login_at < $10::timestamptz
          OR (u.last_login_at = $10::timestamptz AND u.id < $11::uuid)
          OR u.last_login_at IS NULL))
    OR ($10::timestamptz IS NULL AND u.last_login_at IS NULL AND u.id < $11::uuid))
ORDER BY u.last_login_at DESC NULLS LAST, u.id DESC
LIMIT $12
`

type ListUsersByLastLoginParams struct {
	AllUsers     bool
	TenantIds    []uuid.UUID
	ScopeOnly    bool
	Q            *string
	Status       *string
	MemberRole   *string
	ScopeKind    *string
	PlatformRole *string
	HasCursor    bool
	AfterLogin   *time.Time
	AfterID      uuid.UUID
	RowLimit     int32
}

type ListUsersByLastLoginRow struct {
	ID                 uuid.UUID
	Email              *string
	DisplayName        *string
	PhotoFileID        *uuid.UUID
	Status             string
	MustChangePassword bool
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	LegacyAuthUid      *string
}

// GET /v1/users?sort=last_login_at: last_login_at DESC NULLS LAST, id DESC (index users_last_login); a cursor
// on a never-signed-in user carries a NULL time.
func (q *Queries) ListUsersByLastLogin(ctx context.Context, arg ListUsersByLastLoginParams) ([]ListUsersByLastLoginRow, error) {
	rows, err := q.db.Query(ctx, listUsersByLastLogin,
		arg.AllUsers,
		arg.TenantIds,
		arg.ScopeOnly,
		arg.Q,
		arg.Status,
		arg.MemberRole,
		arg.ScopeKind,
		arg.PlatformRole,
		arg.HasCursor,
		arg.AfterLogin,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByLastLoginRow{}
	for rows.Next() {
		var i ListUsersByLastLoginRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PhotoFileID,
			&i.Status,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.LegacyAuthUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminUser = `-- name: LockAdminUser :one

SELECT id, email, display_name, status, auth_version, legacy_auth_uid
FROM users
WHERE id = $1
FOR NO KEY UPDATE
`

type LockAdminUserRow struct {
	ID            uuid.UUID
	Email         *string
	DisplayName   *string
	Status        string
	AuthVersion   int32
	LegacyAuthUid *string
}

// Users administration (T19, Appendix B §B.2.5, Appendix C §C.8): the identity tables are platform-only under
// RLS, so iam reads and writes them in db.WithSystem after Go authorization. Every read names the principal's
// reach explicitly (all_users, tenant_ids, scope_only), the same rule RLS p_staff_read applies to tenant staff,
// widened for stewards to the accounts that belong to no tenant (customer scopes are global master data, R60).
// The users row first (lock order users -> sessions -> refresh_tokens, Appendix C §C.4.4).
func (q *Queries) LockAdminUser(ctx context.Context, id uuid.UUID) (LockAdminUserRow, error) {
	row := q.db.QueryRow(ctx, lockAdminUser, id)
	var i LockAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.AuthVersion,
		&i.LegacyAuthUid,
	)
	return i, err
}

const setDriverUser = `-- name: SetDriverUser :exec
UPDATE drivers SET user_id = $1 WHERE id = $2
`

type SetDriverUserParams struct {
	UserID *uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) SetDriverUser(ctx context.Context, arg SetDriverUserParams) error {
	_, err := q.db.Exec(ctx, setDriverUser, arg.UserID, arg.ID)
	return err
}

const targetPrivileges = `-- name: TargetPrivileges :one
SELECT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = $1::uuid)::boolean AS platform_role,
       array(SELECT m.tenant_id FROM memberships m WHERE m.user_id = $1::uuid ORDER BY m.tenant_id)::uuid[] AS tenant_ids,
       array(SELECT m.tenant_id FROM memberships m WHERE m.user_id = $1::uuid AND m.role = 'tenant_admin'
             ORDER BY m.tenant_id)::uuid[] AS admin_tenant_ids,
       EXISTS (SELECT 1 FROM user_scopes s WHERE s.user_id = $1::uuid AND s.kind = 'dispatcher')::boolean AS dispatcher,
       EXISTS (SELECT 1 FROM user_scopes s WHERE s.user_id = $1::uuid AND s.kind = 'customer')::boolean AS customer
`

type TargetPrivilegesRow struct {
	PlatformRole   bool
	TenantIds      []uuid.UUID
	AdminTenantIds []uuid.UUID
	Dispatcher     bool
	Customer       bool
}

// What the target holds beyond the caller's reach (Appendix C §C.8 "Reach": an admin route acts only on a user it
// outranks): a platform role, every membership tenant and the tenants it administers (any status, unfiltered by
// reach), and its scope kinds.
func (q *Queries) TargetPrivileges(ctx context.Context, id uuid.UUID) (TargetPrivilegesRow, error) {
	row := q.db.QueryRow(ctx, targetPrivileges, id)
	var i TargetPrivilegesRow
	err := row.Scan(
		&i.PlatformRole,
		&i.TenantIds,
		&i.AdminTenantIds,
		&i.Dispatcher,
		&i.Customer,
	)
	return i, err
}

const tenantExists = `-- name: TenantExists :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE id = $1)::boolean AS found
`

// The read of GET /v1/tenants/{id}/members (no lock).
func (q *Queries) TenantExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const tenantForMembership = `-- name: TenantForMembership :one
SELECT kind, status FROM tenants WHERE id = $1 FOR KEY SHARE
`

type TenantForMembershipRow struct {
	Kind   string
	Status string
}

// FOR KEY SHARE: a membership write takes the tenant before the user (the order of PATCH /v1/tenants/{id}, which
// locks the tenant and then bumps its members), and the membership's foreign key needs this lock anyway.
func (q *Queries) TenantForMembership(ctx context.Context, id uuid.UUID) (TenantForMembershipRow, error) {
	row := q.db.QueryRow(ctx, tenantForMembership, id)
	var i TenantForMembershipRow
	err := row.Scan(&i.Kind, &i.Status)
	return i, err
}

const updateAdminUser = `-- name: UpdateAdminUser :exec
UPDATE users
SET display_name = CASE WHEN $1::boolean THEN $2::text ELSE display_name END,
    email        = CASE WHEN $3::boolean THEN $4::text::citext ELSE email END,
    email_verified = CASE WHEN $3::boolean THEN false ELSE email_verified END
WHERE id = $5
`

type UpdateAdminUserParams struct {
	SetDisplayName bool
	DisplayName    *string
	SetEmail       bool
	Email          *string
	ID             uuid.UUID
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) error {
	_, err := q.db.Exec(ctx, updateAdminUser,
		arg.SetDisplayName,
		arg.DisplayName,
		arg.SetEmail,
		arg.Email,
		arg.ID,
	)
	return err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (user_id, tenant_id, role, status, created_by)
VALUES ($1, $2, $3, 'active', $4)
ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role, status = 'active'
`

type UpsertMembershipParams struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	Role      string
	CreatedBy *uuid.UUID
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership,
		arg.UserID,
		arg.TenantID,
		arg.Role,
		arg.CreatedBy,
	)
	return err
}

const userHasMembership = `-- name: UserHasMembership :one
SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = $1)::boolean AS has_membership
`

func (q *Queries) UserHasMembership(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasMembership, userID)
	var has_membership bool
	err := row.Scan(&has_membership)
	return has_membership, err
}

const userInReach = `-- name: UserInReach :one
SELECT EXISTS (
  SELECT 1 FROM users u
  WHERE u.id = $1
    AND ($2::boolean
      OR EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id AND m.tenant_id = ANY ($3::uuid[]))
      OR ($4::boolean AND NOT EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = u.id)
        AND NOT EXISTS (SELECT 1 FROM user_platform_roles r WHERE r.user_id = u.id)))
)::boolean AS in_reach
`

type UserInReachParams struct {
	ID        uuid.UUID
	AllUsers  bool
	TenantIds []uuid.UUID
	ScopeOnly bool
}

func (q *Queries) UserInReach(ctx context.Context, arg UserInReachParams) (bool, error) {
	row := q.db.QueryRow(ctx, userInReach,
		arg.ID,
		arg.AllUsers,
		arg.TenantIds,
		arg.ScopeOnly,
	)
	var in_reach bool
	err := row.Scan(&in_reach)
	return in_reach, err
}

const userIsDriver = `-- name: UserIsDriver :one
SELECT (EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = $1::uuid AND m.role = 'driver')
     OR EXISTS (SELECT 1 FROM drivers d WHERE d.user_id = $1::uuid))::boolean AS is_driver
`

// A driver account: a driver membership or a linked drivers row (POST /v1/users/{id}/password/temporary then
// also needs drivers:set_password).
func (q *Queries) UserIsDriver(ctx context.Context, uid uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userIsDriver, uid)
	var is_driver bool
	err := row.Scan(&is_driver)
	return is_driver, err
}
