// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: housekeeping.sql

package schedulerdb

import (
	"context"
	"time"
)

const deleteEndedSessions = `-- name: DeleteEndedSessions :execrows
DELETE FROM sessions WHERE revoked_at < $1::timestamptz OR absolute_expires_at < $1::timestamptz
`

// auth.token-cleanup: sessions revoked, or past absolute_expires_at, more than 30 days ago (their
// refresh tokens go with them, ON DELETE CASCADE).
func (q *Queries) DeleteEndedSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens AS r
 WHERE r.expires_at < $1::timestamptz
   AND NOT EXISTS (SELECT 1 FROM refresh_tokens AS p WHERE p.replaced_by = r.id AND p.expires_at >= $1::timestamptz)
`

// auth.token-cleanup (main spec §7.4, R2): refresh tokens expired more than a day ago. A rotated token
// points at its successor (replaced_by); a token stays while the one it replaced is kept, so the self
// reference never blocks the delete.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSpentPasswordResetTokens = `-- name: DeleteSpentPasswordResetTokens :execrows
DELETE FROM password_reset_tokens WHERE used_at IS NOT NULL OR expires_at < $1::timestamptz
`

// auth.token-cleanup: used or expired reset and invite links.
func (q *Queries) DeleteSpentPasswordResetTokens(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpentPasswordResetTokens, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
